openshift/cluster-node-tuning-operator

- Makefile
- pkg/controller/tuned/tuned_controller.go
WIP
What do you think @jmencak about the syncDaemonSet. I changed the secondary watch as well but it still doesn't work yet. Will expand to monitor the whole cluster.
Suggest rolling out a similar sync to the other objects to short circuit on get, and update after comparison.
> Changing pattern & small build changes

- manifests/03-rbac.yaml
- pkg/controller/tuned/tuned_controller.go
Also removing some logging which will be reported in case of a failure.
> Adding owner references to objects created by the operator.

- Makefile
See https://github.com/openshift/cluster-nfd-operator/pull/2
> Makefile: remove GOARCH=amd64

- README.md
> Manifests application clarification.

- assets/tuned/06-ds-tuned.yaml
- manifests/04-operator.yaml
@smarterclayton @jeremyeder @derekwaynecarr
> set cpu request for pod and operator

- pkg/client/client.go
- pkg/controller/tuned/status.go
- pkg/controller/tuned/tuned_controller.go
Report ClusterOperator status more in line with:
https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md
This PR also improves error reporting for GetConfig() (pulled from
openshift-tuned).
> Fix Operator status condition reporting.

- assets/tuned/06-ds-tuned.yaml
ref: https://jira.coreos.com/browse/POD-114
> use GA kubelet OS label

- Makefile
- pkg/controller/tuned/tuned_controller.go
This commit:
- replaces default tuned CR on operator restart (e.g. upgrade)
- makes sure bindata is regenerated out of modified assets
in case an old version of bindata is already present
- removes extraneous "for" from logging messages
In the presence of custom CRs not to replace the default CR shipped with the
operator (especially on operator upgrade) is a bug and is addressed by this
commit.  Users should create their own custom CRs instead of modifying the
default one.
> Replace default tuned CR on operator restart.

- README.md
Documentation for:
- profile settings rollback on profile changes
- the default operator's CR being overwritten
- a complete example of using custom profiles
Minor fixes and improvements.
> Documenting recent operator functionality.

- OWNERS
OWNERS file changes wrt. new PSAP team
> OWNERS file changes wrt. new PSAP team

- Dockerfile
- Dockerfile.rhel7
- Makefile
- README.md
- assets/bin/run
- assets/patches/010-reapply_sysctl.diff
- assets/patches/020-fix_sighup_hang.diff
- cmd/cluster-node-tuning-operator/main.go
- manifests/04-operator.yaml
- pkg/tuned/tuned.go
Added assets and pkg from openshift-tuned repo, calling wholesale from main based on symbolic link name. This pass has the minimal changes required to function.
> Merge openshift-tuned

- Makefile
- cmd/cluster-node-tuning-operator/main.go
- pkg/operator/controller.go
- pkg/operator/profilecalculator.go
- pkg/operator/status.go
- pkg/tuned/tuned.go
Added "vet" target to Makefile and fixed vet-reported issue.
Fixed `-version` reporting for openshift-tuned.
> Adding "vet" target to Makefile.

- Dockerfile
- Dockerfile.rhel7
- assets/patches/060-realtime.diff
- assets/patches/070-irqbalance-restart.diff
- assets/patches/080-cpu-partitioning-upstream.diff
- examples/cpu-partitioning.yaml
- examples/elasticsearch.yaml
- examples/hugepages.yaml
- examples/ingress.yaml
- examples/realtime.yaml
Changes;
- add a preliminary support for the realtime profile
- cleanup custom profiles in `examples/`
- try-restart irqbalance systemd unit
> Bug 1796633: Adding preliminary realtime profile support.

- OWNERS
@dagrayvid 
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
> Add dagrayvid to reviewers

- pkg/tuned/tuned.go
The code that disables system tuned daemon was not reachable.
Fixes rhbz#1834693
> Bug 1834693: Fix issues with profile application on non-RHCOS platforms with host tuned.

- assets/patches/120-plugin-irqbalance.diff
See https://github.com/redhat-performance/tuned/pull/274 for detail.
> Support for the upstream tuned [irqbalance] plugin.

- OWNERS
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
> add kpouget to OWNERS file

- test/e2e/basic/sysctl_d_override.go
New e2e test for `/etc/sysctl.d/*.conf` override.
> Added new e2e test for /etc/sysctl.d/*.conf override.

- README.md
Documents the Operator Management state and backport fixes and adjustments from the product documentation.
> Document Operator Management state.

- Dockerfile
- Dockerfile.rhel7
- Dockerfile.rhel8
A separate file is required, as the changes necessary for building with
RHEL 8 content are not compatible with RHEL 7.
> Add Dockerfile.rhel8

- pkg/operator/profilecalculator.go
When two or more profiles have the same priority and they match a node, the
profile selection between these used to be random.  This PR adds some determinism
to the way profile selection is done based on Tuned CR names and also issues a
warning about this to help cluster administrators to discover this problem.
> Bug 1881422: Issue a warning when two or more profiles use the same priority.

- Dockerfile
- Dockerfile.rhel7
- Dockerfile.rhel8
See https://bugzilla.redhat.com/show_bug.cgi?id=1885419
> Remove traces of unsigned RPMs from the image.

- assets/tuned/stalld/Makefile
- assets/tuned/stalld/src/stalld.c
- assets/tuned/stalld/src/stalld.h
- assets/tuned/stalld/src/throttling.c
- assets/tuned/stalld/src/utils.c
- Shipping https://git.kernel.org/pub/scm/utils/stalld/stalld.git/
c35b62722ffebb3cf16ad6b470d9275f007f6fa2
> Ship the latest version of stalld.

- manifests/01-namespace.yaml
- manifests/02-crd-profile.yaml
- manifests/02-crd-tuned.yaml
- manifests/03-rbac.yaml
- manifests/04-operator.yaml
- manifests/05-clusteroperator.yaml
This matches https://github.com/openshift/enhancements/pull/445 and does
not change behavior.
> Add IBM Cloud managed annotations to CVO manifests

- manifests/30-monitoring.yaml
So this is one of those things how did this even happen and how did this pass a review. :)
> Bug 1917327: Fix annotation message for NTOPodsNotReady message.

- pkg/tuned/tuned.go
Added an additional state to `openshift-tuned` "status" indicating whether Tuned profile application was successful or applied with warnings/errors.  If it was applied with errors and a Profile change is detected, Tuned daemon is reloaded.
> Bug 1919970: Recover gracefully after Tuned errors.

- assets/tuned/patches/020-netdev.diff
See upstream PR: https://github.com/redhat-performance/tuned/pull/320
> Support for adjusting netdev queue count.

- Dockerfile
- Dockerfile.rhel7
- Dockerfile.rhel8
- manifests/50-operator.yaml
- manifests/image-references
Update things that the bot didn't
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
> Updating cluster-node-tuning-operator images to be consistent with new ART images

- assets/tuned/stalld/Makefile
- assets/tuned/stalld/src/stalld.c
- assets/tuned/stalld/src/stalld.h
- assets/tuned/stalld/src/utils.c
Changes:
- updated https://gitlab.com/rt-linux-tools/stalld.git to v1.9.0
(8c6fe4b4da167086328fe7ed3c8681f985b68c37)
> Updating to the latest stalld v1.9.0.

- pkg/operator/controller.go
- pkg/tuned/tuned.go
For simplicity, `openshift-tuned` used to process changes in 1s intervals.  While this made the code simpler, it also introduced unnecessary wakeups to process these changes.  These wakeups, of course, cost CPU time and are, therefore, undesirable.
This PR removes the unnecessary wakeups and introduces event-driven processing of these changes.
Other changes:
- address a potential goroutine leak
- address a potential case of not-processing Profile object change
- `s/Tuned/TuneD/` (as per the upstream project) where appropriate
- logging improvements
- comments review
> openshift-tuned event-driven change processing

- test/e2e/reboots/stalld.go
The race was sometimes causing the TuneD daemon re-enable and start `stalld` service after it was intentionally stopped by the test itself using systemctl.
> Address a race in the stalld e2e test.

- pkg/operator/status.go
Fixes gathering all of Tuned CRs with oc adm inspect/must-gather.
> Bug 1986739: gather all Tuned CRs

- go.mod
- go.sum
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
- vendor/modules.txt
> Bug 2067743: Bump client_golang to v1.11.1

- test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Test case IDs to execute based on current cluster toplogy:
* SNO vs non-SNO
* Hyper-Threading enabled vs disbled
* SNO with Workload Partitioning enabled vs disabled
>  Add Hyper-threading aware scheduling test cases for PerformanceProfile.

- test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Add e2e test to check cpus are set offline after perfromanceProfile change and revert back to default status
- [x ] Add e2e test
- Launch config default PerformanceProfile
- Change PefromanceProfile adding offlined cpus
- Check cpus in perfromance profile are offline in selected nodes
- Revert back to default config without offlined cpus
> Add e2e offlined cpus

- test/e2e/performanceprofile/functests/README.md
- test/e2e/performanceprofile/functests/README.txt
Clarify the functional tests layout and purpose
> PAO: update README.txt

- test/e2e/performanceprofile/functests/2_performance_update/kubelet.go
"Should not override performance-addon-operator values"
is failing due mcp its not getting changes in profile.
Fix test as previous ones in order to correct execution
> Fix wrong PAO upgrading kubelet test

- docs/performanceprofile/performance_profile.md
Re generate performance_profile.md to fix old error in doc
Delete forgotten trash file
> Clean up file and fix API docs

- pkg/tuned/controller.go
Initially, `openshift-tuned` was aimed to be as staleless as possible.
For the state information it needed, commands such as `tuned-adm recommend`
were used.  Over time, we realized we need to keep state one
way or another in `openshift-tuned`.  Recent rhbz#2114779 shows, that the
output from `tuned-adm recommend` can sometimes be misleading.  We did
not yet find a root cause for this.  Therefore, we remember the
recommended profile for TuneD, rather than querying for it via
`tuned-adm recommend` command.  This should have a nice side effect of
using less CPU as we do not need to run an external command.
Other fixes/changes:
- Fix the initial timeout for tunedTicker.
Resolves rhbz#2114779
> Bug 2114779: openshift-tuned: remember recommended profile

- manifests/30-monitoring.yaml
Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md
> Add client certificate and key to service monitor

- test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
> e2e: performance: update path of latency binary

- test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Test should be skipped if onlineCPUS is less than 8.
Sometimes when the nodes where the test is executed have 4 CPUs, and we set offline 2 to check the normal behavior, the test are so slow and timeout is reach. 
To avoid this situation, we check onlineCPUs are enough.
> Skip should set offline cpus after deploy PAO test

- HACKING.md
Create a very basic HACKING.md file with instructions for building the NTO and running very basic tests. The intent is that this will
be a starting point for others to add content in the future. I based this on the HACKING.md file from openshift/machine-config-operator.
I know this isn't much, but thought it would be good to at least get started.
> Create HACKING.md file

- assets/performanceprofile/scripts/clear-irqbalance-banned-cpus.sh
- pkg/performanceprofile/controller/performanceprofile/components/assets_scripts_test.go
- pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
- pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
- test/e2e/performanceprofile/functests/1_performance/irqbalance.go
- test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Manual cherry pick from https://github.com/openshift/cluster-node-tuning-operator/pull/444
> OCPBUGS-1126: [release-4.11] irqbalance: add unit to clear the cpu ban list

- pkg/operator/controller.go
- pkg/operator/profilecalculator.go
This PR has two changes to be more careful about when MachineConfigs are created by NTO when running in HyperShift:
* In HyperShift never create MachineConfigs for default profile. Previously this would only happen if an admin user on the hosted cluster manually edits the profile to add status.bootcmdline, but with this PR it should never happen.
* In HyperShift never create or update MachineConfigs when Profile.generation is greater than generation when last updated by the operator + 1.
> HyperShift: avoid unnecessary mcfg creation

- cmd/cluster-node-tuning-operator/main.go
OCPBUGS-2437: Clusters with large numbers of CSVs can cause crashloop,block upgrades.
This bug is caused since in upgrade procedure NTO lists all CSVs in all namespaces in order to remove PAO CSV.
Since PAO CSV is targeted to all namespaces and thus has a copy of its CSV in every namespace the list operation is expensive.
Using a filtered list to get the original non copied CSV should relieve the load.
> OCPBUGS-2437: Filter out copied csvs when removing pao CSV

- OWNERS
Signed-off-by: Francesco Romani <fromani@redhat.com>
> update owners 20230109

- .ci-operator.yaml
- Dockerfile
- Dockerfile.rhel8
- go.mod
- pkg/client/client.go
- pkg/generated/clientset/versioned/fake/register.go
- pkg/generated/clientset/versioned/scheme/register.go
- pkg/operator/profilecalculator.go
- pkg/performanceprofile/cmd/render/render.go
- pkg/tuned/controller.go
- test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
- test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
- test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
- test/e2e/performanceprofile/functests/utils/nodes/nodes.go
- test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go
Fixing [PR477](https://github.com/openshift/cluster-node-tuning-operator/pull/477) opened by openshift-bot to be mergeable into 4.12 release branch.
/cc @Tal-or
> OCPBUGS-6822: Update NTO images to be consistent with ART

- test/e2e/performanceprofile/functests/1_performance/irqbalance.go
> remove BZ 2181546 from pao e2e skip list

- pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
- pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
> OCPBUGS-11535: tuned: Handle UserLevelNetworking nil pointer gracefully

- pkg/tuned/controller.go
We revert the removal of optimizations done in #567 which were added as a way of addressing OCPBUGS-7384.  However, we later found OCPBUGS-7384 was a user configuration issue so the change is not really needed at this point as we ran with it since OCP 4.5 with no issues.
This reverts commit 8da149d157675464194f3cabc2899fa7023307d0.
> [release-4.12] OCPBUGS-14958: Revert "Remove optimization to allow full resync (#569)"

- OWNERS
> Modify owners file

- .ci-operator.yaml
- Dockerfile
- Dockerfile.rhel9
> Use RHEL9 as a base

- test/e2e/performanceprofile/functests/9_reboot/devices.go
address pending comments from #697
> e2e: devmgr: fine tune kubelet restart test

- test/e2e/performanceprofile/functests/1_performance/irqbalance.go
There was a subtle bug in the previous implementaion, where if the `tunedv1.TunedProfileApplied` does not exits in the slice we still return `true`
This behavior is logically wrong.
We should return `true` only if the condition
was found and it's condition status is positive.
> OCPBUGS-15044:e2e:irqbalance: applied condition exists

- test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Add traces and makes it easier to troubleshoot test flakes. These changes are not meant to fix the flakes yet - still investigating.
> e2e: irqbalance: improve test troubleshooting

- test/e2e/performanceprofile/functests/1_performance/cpu_management.go
- test/e2e/performanceprofile/functests/1_performance/hugepages.go
- test/e2e/performanceprofile/functests/1_performance/irqbalance.go
- test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
- test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
- test/e2e/performanceprofile/functests/4_latency/latency.go
- test/e2e/performanceprofile/functests/utils/pods/pods.go
Manual cherry pick of: #744, #729 
for fixing the ht aware test.
> [release-4.13] [manual] OCPBUGS-17845: deflake ht aware test

- test/e2e/performanceprofile/functests/1_performance/irqbalance.go
In the test we were reverting the profile but didn't wait for it to catch up and apply all the changes.
This led to pollution of the next tests execution which in turn leads to flaky tests.
In addition, we move the `defer` call into the highest point possible in the scope, so it won't get missed by the reader.
> OCPBUGS-15044: e2e:irqloadbalance: wait for profile revert

- pkg/operator/controller.go
NTO reconcilation loop assumed that it is only necessary to update operand's DaemonSet only when the RELEASE_VERSION changes.  However, during upgrades, with the introduction of multi-arch OCP, RELEASE_VERSION doesn't necessarily changes, whereas the operator and operand image can.
This change adds a condition to also update operand's DaemonSet on operand image changes.
Resolves: OCPBUGS-18480
> OCPBUGS-18480: Sync DaemonSet if operand image changes

- cmd/cluster-node-tuning-operator/main.go
This reverts commit c2ba8019450443a58652d82f94b59142ab0442ce.
/cc @sdodson
> OCPBUGS-18000: Revert "Revert "Release leader election on manager exit (#773)" (#797)"

- test/e2e/performanceprofile/functests/8_reboot/devices.go
- test/e2e/performanceprofile/functests/8_reboot/test_suite_reboot_test.go
- test/e2e/performanceprofile/functests/utils/nodes/nodes.go
- test/e2e/performanceprofile/functests/utils/pods/pods.go
manual cherry-pick of https://github.com/openshift/cluster-node-tuning-operator/pull/653
> OCPBUGS-14148: e2e: perfprof: add SNO device recovery test (#653)

- pkg/operator/controller.go
- pkg/operator/status.go
This change improves reporting of operand version in the ClusterOperator/node-tuning object.  A total number of scheduled operands with operator's version is reported.  The change also fixes a potential brief period of false operand version reporting during upgrades.
> Improve co/node-tuning operand version reporting

- test/e2e/performanceprofile/functests/1_performance/irqbalance.go
- test/e2e/performanceprofile/functests/utils/tuned/tuned.go
Manual cherry-pick of couple of PRs in order to deflake the IRQ load-balancing test
> [release-4.13][manual]  OCPBUGS-18493: e2e: deflake IRQ load-balancing

- cmd/cluster-node-tuning-operator/main.go
- pkg/performanceprofile/controller/utils.go
- test/e2e/basic/csvs.go
- test/e2e/basic/operator_test.go
- test/e2e/testing_manifests/csv-dummy.yaml
This is a manual cherry-pick of https://github.com/openshift/cluster-node-tuning-operator/pull/818 
supersedes #830
> [release-4.12] OCPBUGS-21837: nto: pao avoid timeout when there are too many CSV

- pkg/apis/performanceprofile/v2/performanceprofile_types.go
- pkg/performanceprofile/controller/performanceprofile/components/manifestset/manifestset.go
- pkg/performanceprofile/controller/performanceprofile/components/profile/profile.go
- pkg/performanceprofile/controller/performanceprofile/components/profile/profile_test.go
- pkg/performanceprofile/controller/performanceprofile_controller.go
- pkg/performanceprofile/controller/performanceprofile_controller_test.go
- pkg/performanceprofile/controller/resources.go
- pkg/performanceprofile/controller/status.go
- pkg/performanceprofile/node/helper.go
- pkg/performanceprofile/utils/testing/testing.go
- test/e2e/performanceprofile/functests/1_performance/performance.go
- test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
- test/e2e/performanceprofile/testdata/render-expected-output/default/manual_node.yaml
This is a manual cherry pick of "Fix Racing Machine Configs and add Day 0 Support"(https://github.com/openshift/cluster-node-tuning-operator/pull/854)
> OCPBUGS-25115: Fix Racing Machine Configs and add Day 0 Support (#854)

- README.md
Fixed link and matched text syntax for labels.
> NO-JIRA: README Doc Typo Fix

- pkg/operator/profilecalculator.go
This fix addresses a false warning that is dumped to logs in the NTO tuned profile selection process.
Deploying 2 performance profiles on two different nodes, resulting in false priority warnings that were dumped to logs. As part of the profile selection process, NTO checks if there are profiles that share the same priority, regardless of their associated node!
The current solution fixes this and priority warnings are raised only when multiple profiles with matching priorities are associated with the same node.
Note that the fixes address both the Openshift and hypershift platforms separately.
> OCPBUGS-24636: Report duplicate priority only for multiple matching profiles

- test/e2e/performanceprofile/functests/utils/label/label.go
> NO-JIRA: e2e: fix typo in label name

- test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
- test/e2e/performanceprofile/functests/1_performance/hugepages.go
- test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
- test/e2e/performanceprofile/functests/utils/cgroup/cgroup.go
- test/e2e/performanceprofile/functests/utils/cgroup/controller/controller.go
- test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
- test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
- test/e2e/performanceprofile/functests/utils/cgroup/v2/v2.go
- test/e2e/performanceprofile/functests/utils/pods/pods.go
Manual backport of https://github.com/openshift/cluster-node-tuning-operator/pull/906
> [release-4.15] [manual]  OCPBUGS-29376: e2e: cgroups: introduce cgroup package

- test/e2e/performanceprofile/functests/11_mixedcpus/11_mixedcpus_suite_test.go
- test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
- test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
- test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
- test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
- test/e2e/performanceprofile/functests/utils/nodes/nodes.go
- test/e2e/performanceprofile/functests/utils/profiles/profiles.go
Manual backport of:
* https://github.com/openshift/cluster-node-tuning-operator/pull/892 
* https://github.com/openshift/cluster-node-tuning-operator/pull/912 
* https://github.com/openshift/cluster-node-tuning-operator/pull/914
> [release-4.15][manual] OCPBUGS-29376: Mixed CPUs e2e tests

- test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
We had a bug (https://github.com/cri-o/cri-o/pull/7710) in CRI-O on which the Mixed-CPUs environment variables were injected to all processes but the init process.
The test has been modified to verify that the env variables are injected to the init process as well. From this point all child processes would inherit the Mixed-CPUs environment variables, unless removed explicitly, but we double check the child process anyway.
> NO-JIRA: e2e:mixedcpus: check env variables of init process

- hack/render-sync.sh
Missed hunk to update the no-ref testdata in PRs #966 #989
> OCPBUGS-31042: [release-4.15][manual] hack: fix backport of render-sync.sh

- assets/performanceprofile/tuned/openshift-node-performance
- test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
- test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Manual Cherry pick of https://github.com/openshift/cluster-node-tuning-operator/pull/983
> [release-4.14] OCPBUGS-31844: Scheduler plugin: ignore IRQs

- assets/performanceprofile/tuned/openshift-node-performance
- test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Manual cherry pick of https://github.com/openshift/cluster-node-tuning-operator/pull/1023
> [release-4.13] OCPBUGS-31936: Scheduler plugin: ignore IRQs

- assets/performanceprofile/tuned/openshift-node-performance
- test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
manual cherry pick of https://github.com/openshift/cluster-node-tuning-operator/pull/1027
> [release-4.12] OCPBUGS-32205: Scheduler plugin: ignore IRQs

- test/e2e/performanceprofile/functests/4_latency/latency.go
Currently, after executing the latency test with OSLAT/cyclictest, if latency exceeds the maximum latency threshold, we display the first exceeding measured latency rather than the maximum latency measured. It is more informative to display the maximum latency measured, therefore we made this change.
> CNF-11985: Enhance latency cnf-tests UX

- test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Adapt #1041 by fixing the expected failure message.
> NO-JIRA: perfprof: latency e2e: adjust failure message

- test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
Added the following tests:
* A best-effort pod effort can't be deployed with shared-cpus resource
* A burstable pod can't be deployed with shared-cpus resource
* A pod with shared-cpus resource can't be deployed in ns without mixedcpus annotation.
* A pod with an invalid resource openshift.io/enable-shared-cpus != 1, should fail.
> CNF-11977: e2e: Added mixed cpus negative tests

- pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
- pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift_test.go
This PR has been split  from #1084 and is a prerequisite for it.
It implements missing API calls that are needed during the e2e tests adjustments
Co-authored-by: Ronny Baturov <rbaturov@redhat.com>
> NO-JIRA: hypershift: implements missing client calls needed for e2e tests 

- test/e2e/performanceprofile/functests/1_performance/performance.go
Add a test to verify that ocp-tuned-one-shot.service end time is before kubelet.service start time.
> NO-JIRA: e2e: performance: verify tuned one-shot service vs kubelet

- test/e2e/performanceprofile/functests/1_performance/cpu_management.go
- test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Some CIs run the tests on an environment that has exactly 2 isolated
cpus, but that doesn't mean that these are completely free cpus as there
is a node base load (cpu consumption of burstable and besteffort
pods).The problem is that this test will always fail on such
environments while it's irrelevant to run.
Skip the test by adding a condition to verify whether the requested cpus
are greater than what the node can provide.
> NO-JIRA: e2e: performance: skip test on env with insufficient cpus

- Makefile
- test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go
It includes adjustments required to run the mustgather suite on a hypershift hosted cluster.
> CNF-13756: Adjust mustgather test suite for hypershift

- pkg/operator/controller.go
- pkg/tuned/controller.go
https://github.com/openshift/cluster-node-tuning-operator/pull/1195 introduced a k8s bump which deprecated some methods.  Stop using those methods to fix the linter warnings.
> PSAP-1567: Fix linter warnings

- cmd/performance-profile-creator/cmd/root.go
- pkg/performanceprofile/profilecreator/helper.go
- pkg/performanceprofile/profilecreator/profilecreator.go
- pkg/performanceprofile/profilecreator/profilecreator_test.go
manual cherry-pick of:
#1213 
#1223
#1236
> [release-4.17] OCPBUGS-44644: cmd: PPC: support tolerating heterogeneous core IDs

- docs/performanceprofile/performance_profile.md
> NO-JIRA: Update performance_profile.md

- pkg/metrics/server.go
This PR fixes the behaviour of the metrics server to return "401 Unauthorized" when no or an invalid (e.g. expired) client certificate is passed to the metrics server.
Resolves: OCPBUGS-60258
> OCPBUGS-60258: Return 401 Unauthorized without client cert

- test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
- test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Some commits are actual fixes and some are just an application of best practices.
Details inside.
> NO-JIRA:e2e: set of fixes/changes to ovs pinning testing
