openshift/cluster-node-tuning-operator

assets/tuned/06-cm-tuned-recommend.yaml
assets/tuned/07-ds-tuned.yaml

Current tectonic 4.0 installer also uses node labels with empty values.  Adjust ConfigMaps.

Tolerate all taints so that tuned is always present on all nodes.

---

manifests/03-cr.yaml

fixes CVO error
```
I1022 15:33:33.401829       1 reflector.go:286] github.com/openshift/cluster-version-operator/vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go:117: forcing resync
E1022 15:33:39.000690       1 sync.go:52] error running apply for (tuned.openshift.io/v1alpha1, Kind=Tuned) /default: Namespace parameter required.
I1022 15:33:41.730935       1 reflector.go:286] github.com/openshift/cluster-version-operator/pkg/generated/informers/externalversions/factory.go:118: forcing resync
I1022 15:33:43.394037       1 leaderelection.go:209] successfully renewed lease openshift-cluster-version/cluster-version-operator
I1022 15:33:47.648483       1 reflector.go:286] github.com/openshift/cluster-version-operator/vendor/k8s.io/apiextensions-apiserver/pk …
```

add namespace to Tuned CR

---

manifests/05-operator.yaml
manifests/image-references

@derekwaynecarr @bparees 
`cluster-node-tuning-operator` is in the 4.0 release image stream
```
$ release-image-stream.sh cluster-node-tuning-operator
Image Name:	sha256:ceb2f2719a4d11e8adf8e27bcb7d6e178c4a8fa04a7ec54b92cab93725b723c5
Image Created:	3 days ago
io.openshift.build.commit.id=f8011e1e5160364e4aec9b111e40ea1a9c830ef3
```
but there is currently no `image-references` file that allows the operator deployment to be rendered by the `oc adm release new` command.
The PR adds it.

add image refs to allow release rendering

---

manifests/04-rbac.yaml
manifests/05-operator.yaml

Current error in the CVO trying to apply
```
E1023 14:22:17.230519       1 sync.go:52] error running apply for (/v1, Kind=ServiceAccount) /cluster-node-tuning-operator: an empty namespace may not be set when a resource name is provided
```
@bparees @wking 
Testing this now to make sure we don't just fall through to another error after this one

add namespace to manifests

---

assets/tuned/07-cr-tuned.yaml

Documented here:  https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html#timeout-nvme-ebs-volumes
@gnufied @eparis

nvme timeout and retry increase per AWS documentation

---

manifests/04-operator.yaml

An operator deployed by the CVO should run on the master.
Applied a minimal memory request.

CVO managed operator should deploy to masters

---

manifests/04-operator.yaml
pkg/config/config.go

As per request from Clayton, we "need to drop “-operator” from the ClusterOperator object name."

Rename cluster-node-tuning ClusterOperator

---

manifests/04-operator.yaml
manifests/05-clusteroperator.yaml
pkg/controller/tuned/status.go

Every operator shall report a version with name=operator whose value is equal to the RELEASE_VERSION provided by the cluster version operator.
will be enforced via https://github.com/openshift/origin/pull/22156

status: report cluster operator version from payload

---

manifests/04-operator.yaml

In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …

Fix tolerations

---

assets/tuned/06-ds-tuned.yaml

This commit increases memory requests for the tuned daemon
to a more realistic 50Mi and adds a preStop hook to fascilitate
operand's settings rollback at pod termination.
This PR needs to be merged prior to merging https://github.com/openshift/openshift-tuned/pull/17.

Increase operand's memory request and allow settings rollback.

---

pkg/controller/tuned/tuned_controller.go

Updating tuned ServiceAccount leads to a creation of new secrets,
which accumulate in openshift-cluster-node-tuning-operator namespace.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1714484

Do not update service account when it is already created.

---

manifests/04-operator.yaml
pkg/controller/tuned/status.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1717739
`openshift-must-gather inspect clusteroperator/node-tuning` now exits successfully (0) and returns all resources created by the operator.

Add more RelatedObjects for the must-gather tool.

---

assets/tuned/06-ds-tuned.yaml
manifests/03-rbac.yaml
pkg/controller/tuned/tuned_controller.go
pkg/manifests/manifests.go

This commit adds support for automatic removal of detached tuned
secrets which might have accumulated in the operator namespace
prior to commit 014900fe.
Associated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1714484

Bug 1718842: Operator-assisted removal of detached tuned secrets.

---

Gopkg.lock
cmd/manager/main.go
vendor/github.com/operator-framework/operator-sdk/pkg/leader/doc.go
vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1719967

Bug 1719967: Implement leader-for-life election.

---

pkg/manifests/manifests.go

In cases any of the profile priorities were undefined, it was possible to have
incorrect ordering of tuned profiles in tuned-recommend ConfigMap.  This PR
fixes this issue.

Fix custom profiles ordering based on their priorities.

---

manifests/02-crd.yaml

This is necessary to enable basic custom CR formatting checks.
Outstanding issues:
- unknown fields are not dropped from CRs
- only one level of "match:" sections is validated due to recursive
nature of the tuned CRD spec

Basic CR validation using openAPIV3Schema

---

pkg/controller/tuned/status.go

This commit:
- adds the "Reason" condition for the ClusterOperator status
- sets the Degraded condition when the operator is Unavailable
for an extensive period of time
See: RH BZ1741067 and BZ1717617

Report the "Reason" condition for the ClusterOperator status.

---

pkg/controller/tuned/status.go

This commit:
- adds the "Reason" condition for the ClusterOperator status
- sets the Degraded condition when the operator is Unavailable for an extensive period of time
This is a backport of https://github.com/openshift/cluster-node-tuning-operator/pull/77 into release-4.1 branch.

Bug 1741067: Report the "Reason" condition for the ClusterOperator status.

---

assets/tuned/default-cr-tuned.yaml

@RobertKrawitz was testing some large workloads, and we found pid limits were blocking some pods running. This PR bumps the pid limits to 524288.

[4.3] bump pid limits

---

assets/tuned/default-cr-tuned.yaml

Adapting a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1758552 from OCP 3.11.

Use net.ipv4.conf.all.arp_announce=2 in the openshift profile.

---

examples/hugepages.yaml
examples/ingress.yaml
test/e2e/operator_test.go

The current Node Tuning Operator's e2e tests include only tests for:
- availability of the ClusterOperator node-tuning object
- existence of the default tuned CR
The e2e tests are enhanced to check basic functionality of the operator's operands, i.e. the functionality of requested tuning on OpenShift nodes.
The following three tests are added:
- the basic functionality of NTO and its operands (check for an application of a default sysctl)
- the application (and rollback) of a custom profile via pod labelling
- the application (and rollback) of a custom profile via node labelling

Add more e2e tests.

---

pkg/controller/tuned/tuned_controller.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/doc.go

This PR sets owner references for the default tuned CR only.
Additional owner references in the tuned daemonset were triggering garbage collector to delete the tuned daemonset unnecessarily on deletion of custom tuned CRs.

Do not add ownerReferences for custom CRs.

---

manifests/02-crd.yaml

preserveUnknownFields: false is now required on a global level.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1769468

Use "preserveUnknownFields: false" for the CRD.

---

assets/tuned/default-cr-tuned.yaml

Adapting a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1758552 from
OCP 3.11.

Bug 1769470: Use net.ipv4.conf.all.arp_announce=2 in the openshift profile.

---

assets/tuned/default-cr-tuned.yaml

Adapting a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1758552 from
OCP 3.11.

Bug 1769471: Use net.ipv4.conf.all.arp_announce=2 in the openshift profile.

---

assets/tuned/cm-tuned-profiles.yaml
examples/elasticsearch.yaml
pkg/apis/tuned/v1/tuned_types.go
pkg/client/listers.go
pkg/manifests/manifests.go
pkg/operator/bootstrap.go
pkg/operator/controller.go
test/e2e/operator_test.go

For faster operator to operand change propagation, remove the last ConfigMap
used by the NTO's operand.  An associated operand's PR will use a "rendered"
Tuned resource to get informed about the default and all custom tuned profile
changes.
Elasticsearch e2e custom profile test was added, replacing the original
"ingress" one.  E2e tests were improved to include removal of custom profiles
at different test stages.

Remove "tuned-profiles" ConfigMap.

---

Dockerfile
Dockerfile.rhel7
assets/patches/010-reapply_sysctl.diff
assets/patches/020-fix_sighup_hang.diff
assets/patches/030-variable-expansion.diff
assets/patches/040-profile-inheritance.diff
assets/tuned/ds-tuned.yaml
examples/cpu-partitioning.yaml

Changes:
- allow patches to modify tuned profiles too (see rhbz#1781664)
- mount host directories to allow:
* persistent changes to /etc/sysconfig/irqbalance
* tuned to populate /etc/modprobe.d directory with module
options (see kvm.rt.tuned.conf)
* persistent changes to host's /etc/systemd/system.conf
by tuned setting CPUAffinity
- create /etc/grub.d/, /boot to make tuned's [bootloader] plugin
pass and generate /etc/tuned/bootcmdline
- include tuned patch for rhbz#1781664 (variable expansion)
- include tuned patch to enable multiple profile inheritance
(tuned 2.13 feature)
- include an example custom openshift-cpu-partitioning profile
Note that the [bootloader] plugin does not do any host modifications,
however, the variables in /etc/tuned/bootcmdline should be set
correctly.

Add preliminary support for the cpu-partitioning profile.

---

assets/tuned/default-cr-tuned.yaml

This addition closes a gap by missing the second inotify tuning
that was present in OCP 3.x.  See:
https://github.com/openshift/openshift-ansible/pull/9204

Set fs.inotify.max_user_instances=8192 in openshift-node profile.

---

assets/patches/050-latency-cstate.diff

Backporting tuned-2.12 functionality to allow specification of latency
as a C-state.

plugin_cpu: latency can be now specified as cstate

---

README.md
assets/tuned/default-cr-tuned.yaml
pkg/operator/controller.go
pkg/operator/profilecalculator.go

Changes:
- Remove leftover profiles on node deletions.
- On clusters with many thousands of pods, the operator can take large
amounts of memory.  Also, clusters with a lot of "pod churn" (pods
started/deleted, pod labels changed, ...) can show CPU utilization spikes
on a node the operator runs.  Disable pod support by default.  While pod
support is automatically re-enabled when a custom CR with pod label match
is detected, it is discouraged to use this feature especially in
large-scale clusters.
- A pod label matching fix for pods with the same labels as other pods running 
on the same node.
- More consistent logging.

Bug 1801797: Pod-label support optimizations.

---

Dockerfile.rhel7
pkg/controller/tuned/tuned_controller.go

Fixes bug 1795665 which causes race conditions on upgrade from 4.x -> 4.3.
This PR removes owner reference from the ServiceAccount.

Bug 1795665: Do not set owner references on tuned ServiceAccount

---

Dockerfile.rhel7
pkg/controller/tuned/tuned_controller.go

Fixes bug 1795671 which causes race conditions on upgrade from 4.x -> 4.2.
This PR removes owner reference from the ServiceAccount.

Bug 1795671: Do not set owner references on tuned ServiceAccount (4.2)

---

Makefile
pkg/tuned/tuned.go

A race condition exists between extracting tuned daemon profiles CR into
`/etc/tuned` directory and applying the pre-calculated profile CR.  If the pre-calculated
profile CR is set and processed prior to the tuned profiles being present in
`/etc/tuned` a possibility exists the calculated profile will not be set.
This change fixes the issue and corrects a `Makefile` prerequisite name.

Retry handling of profile changes on errors.

---

OWNERS

The "component:" field is now required for all OpenShift GitHub repositories
which contribute directly to the product (i.e. they contain a Dockerfile or
.spec file which ART consumes).

Add component field to OWNERS file.

---

assets/patches/020-fix_sighup_hang.diff
pkg/tuned/tuned.go

This PR fixes the behaviour when reloading tuned daemon on SIGHUP.  Tuned pods
will now correctly display error messages from tuned pods when invalid tuned
profile is detected.  More importantly, upon correcting the custom tuned
profile the new profile itself will be reloaded.
Detection whether it is necessary to reload tuned on a profile change is now
based on recommended, rather than the active profile.  The reason is that the
active profile is not set by the tuned daemon when an invalid tuned profile is
encountered.
Lastly, cluster administrators will now see error messages from tuned pods
indicating non-existence of a tuned profile directories.

Fix tuned reload behaviour on SIGHUP for invalid tuned profiles.

---

assets/patches/055-realtime-regex_search_ternary.diff
assets/patches/060-realtime.diff
assets/patches/070-irqbalance-restart.diff
assets/patches/080-cpu-partitioning-upstream.diff
examples/realtime-mc.yaml
pkg/tuned/tuned.go

This PR supports the new isolate_managed_irq functionality in the upstream realtime profile and prepares ground for tuned-2.11.0-9.el7.noarch

Support isolate_managed_irq in the realtime profile.

---

assets/patches/020-fix_sighup_hang.diff
pkg/tuned/tuned.go

This PR fixes the behaviour when reloading tuned daemon on SIGHUP.  Tuned pods
will now correctly display error messages from tuned pods when invalid tuned
profile is detected.  More importantly, upon correcting the custom tuned
profile the new profile itself will be reloaded.
Detection whether it is necessary to reload tuned on a profile change is now
based on recommended, rather than the active profile.  The reason is that the
active profile is not set by the tuned daemon when an invalid tuned profile is
encountered.
Lastly, cluster administrators will now see error messages from tuned pods
indicating non-existence of a tuned profile directories.

Bug 1824473: Fix tuned reload behaviour on SIGHUP for invalid tuned profiles.

---

assets/tuned/06-ds-tuned.yaml

Cause: 
Tuned pods did not mount `/etc/sysctl.{conf,d/}` from the host.
Consequence: 
Settings provided by the host can be overriden by tuned profiles even though this is no longer the standard behaviour of tuned as shipped in RHEL 7.3.
Fix: 
Mount `/etc/sysctl.{conf,d/}` from the host in tuned pods.
Result: 
Tuned profiles no longer override the host sysctl settings in `/etc/sysctl.{conf,d/}`.

Bug 1826167: Mount host's /etc/sysctl.{conf,d/} to enable sysctl override from the host.

---

assets/patches/100-bootcmdline-inheritance.diff

Child profiles can now use:
```
[bootloader]
cmdline_suffix=-parameter_to_remove
```
See: rhbz#1816168, https://github.com/redhat-performance/tuned/pull/265

Bug 1833440: Resolve tuned issue with removing parent profile cmdline parameters.

---

pkg/operator/status.go

The `resource` property of the `relatedObjects` stanza in the ClusterOperator object needs lowercase plurals.

Bug 1851214: use lowercase plurals in resource property of relatedObjects

---

assets/patches/110-cpuinfo-regexp.diff

This is a backport of a functionality introduced by
https://github.com/redhat-performance/tuned/commit/8d9cd00387426ed0
in tuned 2.13.

Support cpuinfo_regex and uname_regex matching.

---

test/e2e/basic/sysctl_d_override.go
test/e2e/reboots/kernel_parameter_add_rm.go

- Make e2e tests possible to be run outside the NTO namespace.
- 5 minutes may not be enough for a machine reboot.  Adjust the `kernel_parameter_add_rm` test accordingly.

e2e test fixes.

---

Dockerfile
Dockerfile.rhel7
Dockerfile.rhel8
assets/tuned/patches/030-realtime-virt-host-drop_lapic_calc.diff
assets/tuned/patches/040-tuned-plugin-rtentsk.diff

Thanks to the upstream tuned patch it is now possible to ship tuned-profiles-nfv profiles.
This PR adds tuned patches which enable full support of tuned-profiles-nfv.  Add `[rtentsk]` plugin support:
https://github.com/redhat-performance/tuned/pull/289

Enable tuned-profiles-nfv profiles, add rtentsk plugin.

---

assets/tuned/patches/050-tuned-2.14.0-amd-performance-regression-fix.diff
assets/tuned/patches/060-tuned-2.14.0-scheduler-isolated-cores-cgroups-fix.diff

This PR adds two fixes that resolve rhbz#1746957 and rhbz#1784648 on top of tuned 2.14.  The same fixes that ship with the Tuned daemon in RHEL 8.3.

Tuned daemon fixes.

---

assets/tuned/manifests/ds-tuned.yaml

This daemonset isn't critical for ensuring availability so allow up to
10% to be updated at once
On a 250 node cluster we're seeing about 5 pods per minute
upgrading from 4.5.4 to 4.5.5 which isn't horrible, but we can surely
upgrade more than one at a time.

Set maxUnavailable on ds/tuned to 10%

---

Dockerfile
Dockerfile.rhel7
Dockerfile.rhel8
test/e2e/util/util.go

Apart from `Dockerfile.rhel8` updates to match `ocp-build-data` config, adding procps-ng as a dependency for e2e tests and better error reporting when sysctls during e2e tests fail to be applied.
Obsoleting: https://github.com/openshift/cluster-node-tuning-operator/pull/150

Bug 1872080: Updating Dockerfile.rhel8 baseimages to mach ocp-build-data config.

---

Makefile

Remove docker as as image build engine, replace for podman
also perperly tag images with the short git commit hash
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

Remove Docker as image build engine

---

Dockerfile.rhel8

Updating cluster-node-tuning-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/cluster-node-tuning-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating cluster-node-tuning-operator builder & base images to be consistent with ART

---

manifests/image-references

Per https://issues.redhat.com/browse/ART-2044 the tuned container is obsolete. However it is still referred to in cluster-node-tuning-operator (and thus the CVO) as cluster-node-tuned. This blocks forming a nightly.

Bug 1887088: image-references: no longer require cluster-node-tuned

---

manifests/01-namespace.yaml
manifests/02-crd-profile.yaml
manifests/02-crd-tuned.yaml
manifests/03-rbac.yaml
manifests/04-operator.yaml
manifests/05-clusteroperator.yaml

This is matches openshift/enhancements#414 and doesn't change existing behavior

add current profile annotations to CVO manifests

---

pkg/tuned/host_payload.go

See: https://bugzilla.redhat.com/show_bug.cgi?id=1887568#c26

Set scheduling policy to SCHED_FIFO to stalld and lower threshold.

---

Makefile
manifests/02-crd-tuned.yaml
manifests/02-crd-tuned.yaml-patch
pkg/apis/tuned/v1/tuned_types.go

`make crd-schema-gen` will now create correct tuned CRD without needing any manual intervention.

Generating tuned CRD without any manual intervention.

---

examples/cpu-partitioning.yaml
examples/elasticsearch.yaml
examples/hugepages.yaml
examples/ingress.yaml
examples/realtime-mc.yaml
examples/realtime.yaml
test/e2e/testing_manifests/kernel_parameter_add_rm-child.yaml
test/e2e/testing_manifests/kernel_parameter_add_rm-parent.yaml
test/e2e/testing_manifests/stalld.yaml

The default Tuned CR ships with two profiles with priority 30 and 40.  While the application of profiles with the same priority is now deterministic, using the same priority (30) in the examples and e2e tests is not a good idea.  Increase the priority of these profiles by lowering the priority number to 20 (and 10 where needed).

Change the priorities of example and e2e test profiles.

---

assets/tuned/patches/090-kmod-weak-dependency.diff
test/e2e/basic/modules.go
test/e2e/reboots/stalld.go
test/e2e/testing_manifests/tuned_modules_load.yaml
test/e2e/util/util.go

This fixes an issue in the tuned daemon with a missing
dependency on the kmod package.  The `[modules]` plugin uses
modprobe from the kmod package to load kernel modules.
Other changes:
- Added e2e tests to test this functionality for the loop kernel
module.
- Reused PollExecCmdInPod() for GetFileInPod()
- Removed an unused constant from stalld.go e2e test.

Bug 1895919: Add a weak dependency on kmod to tuned.

---

Dockerfile
Dockerfile.rhel8

Other changes: cleanup of the `Dockerfile.rhel8` to rely on the Tuned daemon rpm dependency spec file.

Switch the upstream Dockerfile to CentOS 8.

---

pkg/tuned/host_payload.go

Add "Restart=always" to the stalld unit to restart the stalld service even if
it exits successfully.
Resolves rhbz#1900196.

Bug 1900196: Automatically restart stalld after exit.

---

manifests/50-operator.yaml
test/e2e/basic/available.go
test/e2e/basic/custom_node_labels.go
test/e2e/basic/custom_pod_labels.go
test/e2e/basic/default_irq_smp_affinity.go
test/e2e/basic/default_node_sysctl.go
test/e2e/basic/modules.go
test/e2e/basic/sysctl_d_override.go
test/e2e/reboots/kernel_parameter_add_rm.go
test/e2e/reboots/machine_config_labels.go
test/e2e/reboots/stalld.go
test/e2e/util/util.go

Changes:
- removing code duplication in `test/e2e/util/util.go`
- documentation for functions in `test/e2e/util/util.go`
- more expressive function names where `poll.Wait()` is used
- more flexibility in terms of specifying the interval and
timeout for `poll.Wait()`
- for two e2e tests involving reboots removed a check for the
original kernel command line parameters as the reboots can now
cause changes not only to "ostree", but also to "root",
"rhcos.root", "rw";  this would be difficult to maintain in the
future
- adhere more to k8s naming conventions ([Pp]od, ...)

E2e test cleanup.

---

manifests/10-namespace.yaml
manifests/20-crd-profile.yaml
manifests/20-crd-tuned.yaml
manifests/30-monitoring.yaml
manifests/40-rbac.yaml
manifests/50-operator.yaml
manifests/60-clusteroperator.yaml

This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-node-tuning-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.

Annotate manifests for single-node-developer cluster profile

---

manifests/30-monitoring.yaml

`service.alpha.openshift.io/serving-cert-secret-name` should be `service.beta.openshift.io/serving-cert-secret-name` now

Adjusting annotation.

---

manifests/10-namespace.yaml
manifests/20-crd-profile.yaml
manifests/20-crd-tuned.yaml
manifests/30-monitoring.yaml
manifests/40-rbac.yaml
manifests/50-operator.yaml
manifests/60-clusteroperator.yaml

This adds annotations for the single-node-production-edge cluster profile. There's a growing requirement from several customers to enable creation of single-node (not high-available) Openshift clusters.
In stage one (following openshift/enhancements#504) there should be no implication on components logic.
In the next stage, the component's behavior will match a non high-availability profile if the customer is specifically interested in one.
This PR is separate from the 'single-node-developer' work, which will implement a different behavior and is currently on another stage of implementation.
For more info, please refer to the enhancement link and participate in the discussion.

add 'single-node-production-edge' annotations to CVO manifests.

---

pkg/metrics/metrics.go
pkg/metrics/server.go
pkg/operator/controller.go

Previously, the metric `nto_profile_set_total` was used to indicate the number of times a profile was "set" for a particular node.  This was inaccurate, mostly due to the lack of reporting a profile applied on a given node.  Change to metric name and the code to report the metric accurately.

Bug 1907936: Switch to nto_profile_calculated_total.

---

Dockerfile
Dockerfile.rhel7
Dockerfile.rhel8
assets/bin/run
assets/tuned/patches/010-terminate.diff
pkg/tuned/tuned.go
test/e2e/basic/rollback.go

Changes:
- Reviewed openshift-tuned signal handling.  The Tuned daemon is now more "supervised" by openshift-tuned in terms of termination.
- Replace socat with nmap-ncat.  Neither `-t<timeout>` nor `-T<timeout>` for socat seemed to be working reliably to quit trying after `<timeout>` socket inactivity.  nmap-ncat with `-i<timeout>`, on the other hand does exactly what is needed, i.e. sets an idle (read/write) timeout.
- Be less aggressive wrt. restarting the Tuned daemon and quitting the supervisor process.  Sometimes it is actually desirable not to restart and quit (e.g. system shutdown/reboot).
- Added an e2e test to test the functionality of the container lifecycle preStop hook (Tuned daemon profile settings rollback).
- Added a patch for the Tuned daemon to resolve the issue with …

Bug 1906228: openshift-tuned and Tuned daemon signal handling fixes.

---

pkg/tuned/tuned.go

Fixes openshift-tuned panic on turning debugging on/off introduced by:
https://github.com/openshift/cluster-node-tuning-operator/pull/192

Bug 1920438: Fix openshift-tuned panic on turning debugging on/off.

---

Dockerfile
Dockerfile.rhel7
Dockerfile.rhel8
assets/tuned/stalld/Makefile
assets/tuned/stalld/README.md
assets/tuned/stalld/scripts/throttlectl.sh
assets/tuned/stalld/src/stalld.c
assets/tuned/stalld/src/stalld.h
assets/tuned/stalld/src/throttling.c
assets/tuned/stalld/src/utils.c
pkg/tuned/host_payload.go

Changes:
- updated https://gitlab.com/rt-linux-tools/stalld.git to v1.7.0
(9ed8ff901c378a1e17041411e78d14b0fa9ed64e)
- included throttlectl.sh from the repo above to disable/enable
RT throttling reliably.  The disable of RT throttling was moved
into the script to run before stalld is started and the enabling
of it to be run in the script after the stalld service is stopped.

Bug 1925072: Updating to the latest stalld v1.7.0.

---

assets/tuned/stalld/Makefile

The `-mtune=generic` is IA32/AMD64/EM64T processor specific.  Also, with `-fcf-protection` GCC fails to build `stalld` on other architectures such as ppc64/s390x.

Bug 1925072: Remove architecture specific gcc flags.

---

pkg/operator/status.go

Add all objects from the "tuned.openshift.io" API group.  All Profiles
and Tuneds will now be collected during `oc adm must-gather`.

Add more related objects to ClusterOperator.

---

assets/tuned/stalld/Makefile

aarch64 is not a multilib architecture, therefore -m64 is not accepted.
It is already the default on the 64-bit multilib-enabled architectures,
so there is really no need for it anyway.
/cc @jmencak

stalld: Remove another architecture specific gcc flag

---

assets/tuned/patches/030-service-enable-disable.diff
pkg/tuned/host_payload.go
test/e2e/reboots/stalld.go
test/e2e/testing_manifests/stalld-disable.yaml
test/e2e/util/util.go

Leave the start/enablement of the stalld daemon entirely up to the Tuned `[service]` plugin.  This resolves the race between systemd starting the stall daemon and the Tuned `[service]` plugin running too early.
Other changes:
- Improving e2e tests for the stalld functionality.
- Better logging for e2e tests failures.
Resolves rhbz#1926903.

Bug 1926903: Instantiate the stalld systemd unit as disabled.

---

pkg/tuned/tuned.go

Added an additional state to `openshift-tuned` "status" indicating whether Tuned profile application was successful or applied with warnings/errors. If it was applied with errors and a Profile change is detected, Tuned daemon is reloaded.

Bug 1920525: Recover gracefully after Tuned errors.

---

assets/tuned/patches/030-no-bootloader-errors.diff

NTO currently supports the bootloader plugin only on RHCOS via the
integration with MCO.  Disable patching of BLS entries and grub
configuration files so that error messages from the tuned daemon are
eliminated and their presence not reported further on in k8s objects.

Do not manupulate BLS entries and grub config

---

Makefile
test/e2e/core/cluster_version.go
test/e2e/core/operator_test.go

The core e2e tests are checking the ability to retrieve:
- host and container OS release
- cluster version
This information is also useful for debugging e2e test failures in cases the developer has no access to the cluster e2e tests are running on.

Add "core" e2e tests.

---

manifests/20-crd-profile.yaml
pkg/operator/controller.go
pkg/tuned/tuned.go

Changes:
- add additionalPrinterColumns Tuned, Applied and Degraded
to profiles.tuned.openshift.io; this will help with quick
identification which Tuned profile is applied on which node
and what is the status of the application.
- fix an issue with profile status not being synced when
manually changed or removed
- always initialize TunedProfile's status conditions after NTO
calculates new Tuned profile to be applied or we know Tuned
daemon will be necessary in situations such as toggling Tuned
daemon's debugging.

Add additionalPrinterColumns to profiles CRD.

---

assets/tuned/patches/040-explicitly_sort_udev_properties.diff

Although udev properties are sorted by libudev, according
to libudev/systemd upstream this behavior cannot be relied
upon. Sort them explicitly for consistent behavior.
See upstream TuneD patch:
https://github.com/redhat-performance/tuned/pull/333

TuneD: udev: explicitly sort udev properties

---

assets/tuned/manifests/ds-tuned.yaml
manifests/10-namespace.yaml
manifests/50-operator.yaml

In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

Add management workload annotations

---

assets/tuned/manifests/ds-tuned.yaml
manifests/50-operator.yaml

As per openshift/enhancements#739, the workload annotations names are changing.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged

Rename workload annotations

---

manifests/30-monitoring.yaml

Invalid spec in ServiceMonitor makes CVO attempt to apply this manifest on every sync loop.

Bug 1960337: manifests: fix selector in node-tuning-operator ServiceMonitor

---

README.md

The documentation was not precise when it came to two or more
MachineConfigPools with nodeSelector matching the same node(s).  This
can happen (e.g. when a node has both master and worker role), but a
single node will always be assigned (a member of) only one or no
MachineConfigPool.

More precise description of MCP matching.

---

pkg/tuned/tuned.go

RHCOS-shipped stalld units do not ship with chrt changing the SCHED_FIFO scheduling policy for stalld causing starvation of the boosting threads.  Until this is fixed in RHCOS, use the NTO-provided stalld.

Bug 1973154: Switch back to NTO-shipped stalld.

---

assets/tuned/patches/050-net-device-conditional-order.diff

The conditional for setting a net device parameter in TuneD has a wrong order where it can potentially try to first cast a string to int in a wrong manner and only then check if the value is a specific integer value.
Upstream TuneD fix: https://github.com/redhat-performance/tuned/pull/360
Resolves rhbz#1974277.

Bug 1974277: Fix conditional order for setting net device param.

---

assets/tuned/stalld/Makefile
assets/tuned/stalld/src/stalld.c
assets/tuned/stalld/src/stalld.h
assets/tuned/stalld/src/utils.c

Changes:
- updated https://gitlab.com/rt-linux-tools/stalld.git to v1.13.0

Updating to the latest stalld v1.13.0.

---

assets/tuned/patches/040-cgroup_ps_blacklist.diff

This PR adds support to prevent TuneD to affine containers to house keeping cpus.
Example:
```
[scheduler]
isolated_cores=1
cgroup_ps_blacklist=/kubepods\.slice/
```
See: rhbz#1979352

scheduler: new option cgroup_ps_blacklist

---

pkg/operator/controller.go

This PR increases leader-election timeouts as per the recommendation in:
https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md
to tolerate 60s worth of disruption.
Resolves rhbz#1986477.

Bug 1986477: Handle kube-apiserver disruption more gracefully.

---

manifests/30-monitoring.yaml

Adding more verbose description to alerts and moving
message -> summary based on OpenShift alerting guidelines:
https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#documentation-required
Removing {{ $labels.node }} as it produced empty output in alerts
and is redundant anyway.
Resolves: rhbz#1992560

Bug 1992560: monitoring: comply with OpenShift alerting guidelines

---

pkg/tuned/tuned.go
test/e2e/basic/tuned_errors_and_recovery.go
test/e2e/testing_manifests/cause_tuned_failure.yaml
test/e2e/testing_manifests/dummy.yaml

This change fixes operand's behavior during administrator-initiated changes of TuneD profiles that the currently recommended TuneD profile depends on.  Now, changes to any such dependent profile and changes to the recommended TuneD profile will cause TuneD daemon reload.
Resolves rhbz#1998247.

Bug 1998247: Reload when deps of recommended profile change.

---

test/e2e/basic/custom_node_labels.go
test/e2e/basic/custom_pod_labels.go
test/e2e/basic/default_irq_smp_affinity.go
test/e2e/basic/default_node_sysctl.go
test/e2e/basic/modules.go
test/e2e/basic/netdev_set_channels.go
test/e2e/basic/rollback.go
test/e2e/basic/sysctl_d_override.go
test/e2e/basic/tuned_errors_and_recovery.go
test/e2e/core/cluster_version.go
test/e2e/reboots/kernel_parameter_add_rm.go
test/e2e/reboots/machine_config_labels.go
test/e2e/reboots/stalld.go
test/e2e/util/util.go

This is a cleanup PR.  Where appropriate (e.g. not Tuned CR), references to the TuneD were fixed for e2e tests as per the upstream project.

e2e tests: s/plugin/plug-in/ and TuneD renaming

---

pkg/tuned/tuned.go
test/e2e/basic/tuned_errors_and_recovery.go
test/e2e/testing_manifests/cause_tuned_failure.yaml
test/e2e/testing_manifests/dummy.yaml

This change fixes operand's behavior during administrator-initiated changes of TuneD profiles that the currently recommended TuneD profile depends on.  Now, changes to any such dependent profile and changes to the recommended TuneD profile will cause TuneD daemon reload.

Bug 1999608: Reload when deps of recommended profile change.

---

assets/tuned/manifests/default-cr-tuned.yaml

Add a cgroup blacklisting rule to parent openshift profile to prevent the `[scheduler]` plug-in from handling containers; see rhbz#1998120.

Bug 1998120: Add a cgroup blacklisting rule to parent openshift profile.

---

manifests/10-namespace.yaml

Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `cluster-node-tuning-operator` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz

podsecurity: enforce privileged for openshift-cluster-node-tuning-operator namespace

---

pkg/tuned/tuned.go

TuneD profile application typically takes ~0.5s and should never take
more than ~5s.  However, there were cases where TuneD daemon got stuck
during application of a profile.  Experience shows that subsequent
restarts of TuneD can resolve this in certain situations.  TuneD itself,
however, has no mechanism for restarting a profile application that is
taking too long.
This change implements full restarts for TuneD daemon.
Other changes:
- tunedStop() is now fully synchronous.  Previously, when TuneD
refused to terminate within 10s, SIGKILL was sent without waiting
for TuneD process to terminate.
Also see: rhbz#2013940

Bug 2018053: tuned: add timeout and restarts

---

pkg/tuned/tuned.go

TuneD profile application typically takes ~0.5s and should never take
more than ~5s.  However, there were cases where TuneD daemon got stuck
during application of a profile.  Experience shows that subsequent
restarts of TuneD can resolve this in certain situations.  TuneD itself,
however, has no mechanism for restarting a profile application that is
taking too long.
This change implements full restarts for TuneD daemon.
Other changes:
- tunedStop() is now fully synchronous.  Previously, when TuneD
refused to terminate within 10s, SIGKILL was sent without waiting
for TuneD process to terminate.
Also see: rhbz#2013940

Bug 2020518: tuned: add timeout and restarts

---

manifests/30-monitoring.yaml

This PR adds a metric to count the number of custom Profiles in the cluster. Put another way, it counts the number of nodes that are using a TuneD profile other than `openshift-node`, `openshift-control-plane`. and `openshift`. 
We can get this information from the existing `nto_profile_calculated_total` metric using the query:
`count(nto_profile_calculated_total{profile!~"openshift-node",profile!~"openshift-control-plane",profile!~"openshift"})`
I was hoping to add this query directly to the telemetry rules, but it seems telemetry requires that metrics be specified by name only, so using this full query is not possible. Fortunately we can add a "new metric" just by using a PrometheusRule. 
Once we get this added the PR to the cluster-monitoring-operator will be quite simple to add this …

Add nto_custom_profiles:count metric via PrometheusRule

---

pkg/operator/controller.go
pkg/operator/status.go

Tuned Profiles are created by NTO operator and updated by both the
operator and its operand.  The operand's updates are the source of truth
for information such as kernel command-line parameters and presence of
the stalld daemon.  The operator is informed about this via the status
field of the a Tuned Profile that corresponds to a given node.  Operator
updates are the source of truth about which TuneD profile should be
applied.
When a new cluster node is added (for example during a cluster
scale-up), a new Tuned Profile is created.  If the node is quickly added
to a MachinePool for which an NTO-managed MachineConfig already exists,
this addition will cause NTO to overwrite/update the MachineConfig with
data that is incorrectly initialized.  If the operand was too slow to
correct this …

Bug 2029371: controller: update MC after application by TuneD

---

pkg/operator/controller.go

Controller has a sync loop that creates Tuned Profiles for every node on
the cluster.  As TuneD supports only Linux hosts, there is no point in
creating Profiles for hosts other than Linux.

controller: ignore non-linux hosts

---

go.mod
go.sum
vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
vendor/modules.txt

The current version of build-machinery-go fixes the problems with
yaml-patch missing github repository.

build-machinery-go: bump to the latest version

---

Makefile
pkg/tuned/controller.go
pkg/tuned/tuned_parser.go
pkg/tuned/tuned_parser_test.go
test/e2e/basic/tuned_builtin_expand.go
test/e2e/testing_manifests/tuned_builtin_expand.yaml

Implemented a very basic and (yet) incomplete parser of TuneD built-in functions in the form `${f:function(:argN)*}`.  Supported built-ins are now `${f:virt_check:profile-a:profile-b}` and `${f:exec(:argN)}`.  These are being expanded only in the TuneD "include" statements to discover whether the TuneD process needs to be reloaded due to a custom profile change that uses these built-ins.
Other changes:
- minor refactoring to lift TuneD profile parser specific code
from the operand
- fixed/renamed the target for unit tests, use `make test-unit`

openshift-tuned: TuneD built-in function support

---

test/e2e/basic/sysctl_d_override.go
test/e2e/reboots/stalld.go

Simplify the e2e stalld test.  It is unnecessarily complex and only adds
to the time it takes to pass all e2e tests by approximately 1 node
reboot.  Add more debugging for any future troubleshooting.
Adjust the sysctl_d_override golang e2e test to show the contents of the
sysctl override file for debugging and synchronize [fsync()] it to
persistent storage after write.

e2e: stalld and sysctl_d_override e2e test changes

---

Dockerfile.rhel8

All TuneD profiles packages are now being correctly shipped via CDN --
use them.

TuneD profiles: switch to FDP TuneD delivery completely

---

pkg/metrics/metrics.go
pkg/metrics/server.go
test/e2e/basic/metrics_cert_rotation.go
test/e2e/util/util.go

This  PR is intended to solve RHBZ#2026387. 
With this change, a file watcher is added to the metrics server using the fsnotify package, to watch for changes to the TLS certificate for the metrics endpoint. I took some inspiration from https://github.com/openshift/cluster-ingress-operator/pull/334/. Instead of restarting the operator when the certificate changes as is done in that PR, the server will be shut down and restarted.
These changes have been tested by editing the node-tuning-operator-tls secret (comments can be added to the certificate / key by putting them outside of the `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`   lines) and by deleting the secret altogether which results in a new key pair being created.
After some review, I will do more testing using the …

Bug 2026387: Handle certificate rotation in pkg/metrics/server.go

---

go.mod
go.sum
vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
vendor/modules.txt

The current version of build-machinery-go fixes the problems with the missing
yaml-patch github repository, which breaks some CI tests.
This is meant to be a manual cherrypick of https://github.com/openshift/cluster-node-tuning-operator/pull/299.

[release-4.9] Bug 2033755: build-machinery-go: bump to the latest version

---

assets/bin/grub2-editenv

Workaround for `TuneD` running in the container not to emit
```
ERROR    tuned.utils.commands: Executing grub2-editenv error: [Errno 2] No such file or directory: 'grub2-editenv': 'grub2-editenv'
```
message while keeping the `[bootloader]` plug-in functional.

Bug 2037036: grub2-editenv: no errors when using [bootloader] plug-in

---

assets/tuned/patches/050-no-ksm-errors.diff

Adding upstream TuneD patch:
https://github.com/redhat-performance/tuned/pull/331
The patch checks the presence of `ksm` and `ksmtuned` units before (un)masking them.
The change prevents messages in the logs such as:
```
2021-02-24 14:46:52,399 ERROR    tuned.plugins.plugin_script: script '/usr/lib/tuned/cpu-partitioning/script.sh' error output: 'Unit ksm.service does not exist, proceeding anyway.
```
which caused per-node Profiles go into Degraded state.
Resolves: rhbz#2036303

Bug 2036303: Prevent unnecessary ksm* error log messages.

---

Dockerfile
Dockerfile.rhel8
assets/tuned/manifests/default-cr-tuned.yaml
assets/tuned/patches/040-cloud-profiles.diff
manifests/20-profile.crd.yaml
pkg/apis/tuned/v1/tuned_types.go
pkg/generated/clientset/versioned/clientset.go
pkg/generated/clientset/versioned/typed/tuned/v1/fake/fake_profile.go
pkg/generated/clientset/versioned/typed/tuned/v1/fake/fake_tuned.go
pkg/generated/clientset/versioned/typed/tuned/v1/tuned_client.go
pkg/operator/controller.go
pkg/operator/profilecalculator.go
pkg/tuned/controller.go
pkg/tuned/tuned_parser.go
pkg/tuned/tuned_parser_test.go
pkg/util/provider_id.go

Add support for Cloud provider specific tuning.  This functionality
takes advantage of the node `spec.providerID` values in the form of:
`<cloud-provider>://<cloud-provider-specific-id>` and writes file
`/var/lib/tuned/provider` with value `<cloud-provider>` in openshift-tuned
containers.
The default openshift profile has been adjusted to take advantage of
this functionality by using conditional profile loading.  At this point,
there are no Cloud provider specific profiles shipped.  However, it is
already possible to create custom profiles that will be applied to all
cluster nodes if profile with name `provider-<cloud-provider>` is
created by cluster administrator.

Add Cloud provider specific profiles support

---

README.md
manifests/20-profile.crd.yaml
manifests/20-tuned.crd.yaml
pkg/apis/tuned/v1/tuned_types.go

Other changes: 
- Fixes a statement in the API about `reapply_sysctl=false` by default.   It is actually true by default, but it is subject to the `TuneD` daemon defaults in tuned-main.conf file.
- `s/Tuned/TuneD/` where appropriate.

Add docs for reapply_sysctl TuneD functionality

---

vendor/modules.txt

4.8 ART builds for NTO are failing due to the slight diff in the `vendor/modules.txt` file from running `go mod vendor`.

[release-4.8] Run 'go mod vendor' to update vendor/modules.txt

---

pkg/operator/controller.go
pkg/operator/status.go
pkg/tuned/controller.go
pkg/tuned/status.go

This PR implements the changes to Profile and ClusterOperator status discussed in [this document]:(https://docs.google.com/document/d/1mhRsDTK91TUiE5O_G610g8QpTjTFc7GAkEiwZLdjXBE/edit?usp=sharing)
- When TuneD reports errors or warnings, add last log line containing " ERROR " or " WARNING " to the Profile degraded status condition Message.
- When the containerized TuneD daemon times out waiting for a profile to be applied, set the Profile status to Degraded.
- (second commit) When the operator is waiting for a profile to be applied, set the ClusterOperator status to Progressing False True. If the Profile is in a Degraded state, set Progressing = False as this means that the Profile either reported errors while applying, or there was a timeout waiting for the profile to be applied.

Improve TuneD error reporting and set CO status Progressing when applying new profiles

---

test/e2e/basic/custom_node_labels.go
test/e2e/basic/custom_pod_labels.go
test/e2e/basic/default_irq_smp_affinity.go
test/e2e/basic/default_node_sysctl.go
test/e2e/basic/metrics_cert_rotation.go
test/e2e/basic/rollback.go
test/e2e/basic/sysctl_d_override.go
test/e2e/basic/tuned_builtin_expand.go
test/e2e/basic/tuned_errors_and_recovery.go
test/e2e/util/util.go

The NTO e2e test suite runs as a series of short e2e tests starting
immediately once the previous test completes.  Some e2e tests rely on
tuning set by the default worker `TuneD` profile -- `openshift-node`.  Most
e2e test will complete without doing a full profile rollback (and/or)
application of the default worker `TuneD` profile.  If an e2e test relies
on this profile to be applied, block the execution of the test until it
applied.
Other changes:
- Make sure `tuned_errors_and_recovery.go` e2e test can be run several
times in a sequence on the same cluster.
- Some formatting nits.

Address e2e test races

---

examples/hugepages.yaml
test/e2e/basic/custom_node_labels.go
test/e2e/basic/custom_pod_labels.go
test/e2e/basic/default_irq_smp_affinity.go
test/e2e/basic/default_node_sysctl.go
test/e2e/basic/modules.go
test/e2e/basic/rollback.go
test/e2e/basic/sysctl_d_override.go
test/e2e/basic/tuned_builtin_expand.go
test/e2e/testing_manifests/tuned_modules_load.yaml
test/e2e/util/util.go

This PR fixes operator e2e tests for for aarch64 and clusters with
worker nodes that also have a master role, such as SNO.
Other changes:
- Fix for `sysctl_d_override.go` rollback (node/pod was always nil
and rollback in case of a test failure was not performed).
- Consistency changes across the tests.

Fix e2e tests for aarch64 and SNO

---

manifests/40-rbac.yaml

This PR is intended to fix [RHBZ#2066700](https://bugzilla.redhat.com/show_bug.cgi?id=2066700).
For an initial draft, I am replacing the wildcards with the full set of resources and verbs in the tuned.openshift.io apiGroup. I plan to experiment with removing some of the verbs, especially from the `cluster-node-tuning:tuned` clusterRole.

Bug 2066700: RBAC replace wildcards for tuned.openshift.io apiGroup

---

pkg/operator/controller.go

When updating NTO-generated MachineConfigs, update `tuned.openshift.io/generated-by-controller-version` annotation with the NTO version performing the update.

Update NTO-generated annotations in MCs

---

Dockerfile
Dockerfile.rhel8
Makefile
cmd/performance-profile-creator/README.md
hack/run-perf-profile-creator.sh
test/e2e/performanceprofile/functests-performance-profile-creator/1_performance-profile_creator/ppc.go

Align PPC with new folder structure in NTO
- Create new targets in Makefile to build PPC and execute functional tests
- Modify paths in functional tests to adapt them to the new folder
structure.
This PR depends on #322 and its related with #324

PerformanceProfileCreator build and functional test execution adaptation.

---

pkg/performanceprofile/controller/performanceprofile_controller.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go

Perfromance addons operator removal will be done by searching for PAO deployment name that will  always euqal `performance-operator` . It will remove the csv and its matching subscription.
This fix will also ensure that all versions lower than 4.11
will remove the PAO.
unit test added.

Fix PAO OLM operator removal

---

Makefile
cmd/cluster-node-tuning-operator/main.go
docs/performanceprofile/performance_addon.md
test/e2e/performanceprofile/functests-render-command/1_render_command/render_suite_test.go
test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

The original PAO code supports an offline render mode where it reads the PerformanceProfile manifest from a file and generates all the outputs as files. This is useful for Day 0 and GitOps based installations.
This PR is work in progress and depends on https://github.com/openshift/cluster-node-tuning-operator/pull/322

Performance profile render command integration

---

pkg/performanceprofile/controller/performanceprofile/components/manifestset/manifestset.go
pkg/performanceprofile/controller/performanceprofile/components/runtimeclass/runtimeclass.go
pkg/performanceprofile/controller/performanceprofile_controller.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go
pkg/performanceprofile/controller/resources.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/3_performance_status/status.go

RuntimeClass in the node.k8s.io/v1beta1 API version
will [no longer be served in v1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#runtimeclass-v125), therefore all occurrences in code containing v1beta1 are replaced with v1.
Kubernetes already supports the seamless transition for existing runtimeclasses.node.k8s.io v1beta1 to v1.

Bug 2073938: Replace RuntimeClass version from v1beta1 to v1 

---

cmd/performance-profile-creator/cmd/root.go
pkg/performanceprofile/profilecreator/profilecreator.go
pkg/performanceprofile/profilecreator/profilecreator_test.go
test/e2e/performanceprofile/functests-performance-profile-creator/1_performance-profile_creator/ppc.go
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5.yaml

Now power consumption modes will work together with workload hints:
1. low-latency -> enable real-time workload hint
2. ultra-low-latency -> enable realtime and highPowerConsumtion hints
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

Adapt PPC to use workload hints instead of setting additional kernel arguments

---

Makefile

Add build and ppc test targets under `test-e2e-local`
that already contains the render test so there will be one main
target for local e2e tests.

  Add build and ppc test invocation under one target

---

Makefile

Change test-e2e-local to use only local directives
instead of the whole build target.

Fix local e2e test target

---

.ci-operator.yaml
Dockerfile.rhel8
go.mod
go.sum

OCP 4.11 will be built with golang 1.18.  Switch the builder image to `rhel-8-golang-1.18-openshift-4.11`.

Switch builder to golang 1.18

---

assets/performanceprofile/scripts/set-cpus-offline.sh
docs/performanceprofile/performance_profile.md
examples/performanceprofile/samples/performance_v2_performanceprofile.yaml
manifests/20-performance-profile.crd.yaml
pkg/apis/performanceprofile/v2/performanceprofile_types.go
pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
pkg/apis/performanceprofile/v2/zz_generated.deepcopy.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
pkg/performanceprofile/controller/performanceprofile/components/utils.go
pkg/performanceprofile/controller/performanceprofile/components/utils_test.go
pkg/performanceprofile/utils/testing/testing.go
test/e2e/performanceprofile/cluster-setup/manual-cluster/performance/performance_profile.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

Provide the ability through the performance addon operator to offline a set of unused cpus to reduce the overall power consumption of the cluster.
Launch test with PerformanceProfile:
cpu:
isolated: "1-2"
reserved: "0"
offlined: "4"
check if offlined cpu are offline:
sh-4.4# cat /sys/devices/system/cpu/offline 
4

Add performanceProfile API offline cores

---

test/e2e/performanceprofile/functests/1_performance/performance.go

No need for a conversion test since the workloadHints
field was introduced only for V2.

Remove conversion test for workload hints

---

cmd/performance-profile-creator/cmd/root.go
pkg/performanceprofile/profilecreator/profilecreator.go
pkg/performanceprofile/profilecreator/profilecreator_test.go
test/e2e/performanceprofile/functests-performance-profile-creator/1_performance-profile_creator/ppc.go
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1a.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1b.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1c.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1c.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2a.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2b.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3a.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3b.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3c.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3c.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4a.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4b.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4c.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4c.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5a.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5b.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5b.yaml

A new parameter is going to be added to Performance Profile  by #345. 
This PR aims to modify the Performance Profile Creator to be able to generate it.
To calculate offlined cpus we take into account the following input parameters:
- `offlined-cpu-count` : the number of cpus the user wants to set offline.
- `disable-ht`: Marks if the user want to disable logical processor siblings to disable hyperthreading
- `power-consumption-mode`: values: “default”, “low-latency”, “ultra-low-latency”
if `disable-ht` is true sibling logical processors will not be considered in the calculation of any of the CPUSets.
Unless `power-consumption-mode` is equal to `ultra-low-latency` ( which is considered a high-consumption scenario), we will first try to look for a complete socket to set offline, that is a …

Bug 2087159: Modify PPC to generate new "offlined" parameter in Performance Profile

---

pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go

Isolated and offlined can not share any CPUs.
If there is an overlap, it fails.

Bug 2089414: PAO Add validation check between isolated and offlined CPUs

---

test/e2e/performanceprofile/functests/4_latency/latency.go
test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

- fix expected runtime flag of cyclictest.
- latency: skip the test when requested cpus number is odd
please find the commits for more details.

Bug 2090184: e2e:  performanceprofile: latency tests fixes

---

assets/performanceprofile/configs/99-netdev-rps.rules
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml

Updated udev rule in 99-netdev-rps.rules to also exclude physical
interfaces.
Co-Authored-By: Brent Rowsell <browsell@redhat.com>
Signed-off-by: Don Penney <dpenney@redhat.com>
/cc @yanirq @MarSik

Bug 2093267: Exclude physical interfaces from netdev-rps rule

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/4_latency/latency.go
test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
test/e2e/performanceprofile/functests/utils/images/prepull.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

- e2e: latency: fail the test if CPUs number is less than 1
- images: change ImagePullPolicy to default
- e2e: pp-latency: verify tool args
- e2e: pp-latency: add the runtime to stabilize the pod-phase condition
Please find each commit for more details

e2e: performance profile: Latency tests stabilization

---

pkg/operator/controller.go
pkg/tuned/controller.go

For every Node object, there is a corresponding Profile object.  While
we have code that removes Profile objects on Node removal, these events
can be missed and/or deletion attempts stopped after several
unsuccessful deletion trials at a given time.
While the existence of these stale Profile objects is not a major
problem, they cause misleading messages in the co/node-tuning object.
Changes:
- Enable periodic resync of all Profile objects and their deletion
unless a corresponding Node object exists.
- Do not overwrite Profile status ERROR messages with lower priority
WARNING message -- credits David Gray.
Resolves rhbz#2102109

Bug 2102109: Remove stale Profiles.

---

Dockerfile

CentOS 8 is dead, switch to CentOS Stream 8.

Switch to CentOS Stream for upstream Containerfile

---

test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1c.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3c.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4c.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5b.yaml

Typo in realtime workloadHints in PerformanceProfile.yaml
```
workloadHints:
highPowerConsumption: false
realtime: true
```
to:  
```
workloadHints:
highPowerConsumption: false
realTime: true
```

Fix typo realTime Hint in PerformanceProfile.yaml

---

pkg/generated/clientset/versioned/clientset.go

After: Bump vendor dependencies to k8s 1.24.2 #386 
make pkt/generated a new file

Add clientset.go missing pkg/generated file

---

Makefile
hack/build-latency-test-bin.sh
hack/run-latency-testing.sh

Add target in the MakeFile to enable running the 5_latency_testing suite: dist-latency-tests to create the load binary and pao-functests-latency-testing to consume it in the tests. Also adjust the path of the suites to match to their new place in NTO directories.

makefile: enable running pao latency testing suite

---

Dockerfile

I believe explicit is better than implicit in this case.

Dockerfile: provide full URL to CentOS stream image

---

test/e2e/performanceprofile/functests/utils/profiles/profiles.go

UpdateWithRetry wants to get a fresh copy of the profile
to update to avoid conflicts; because of a copy/paste
mistake, it was trying to reapply the original profile,
not the updated copy, thus defeating the purpose of the function.
Signed-off-by: Francesco Romani <fromani@redhat.com>

test: utils: use updated profile, not original

---

test/e2e/reboots/machine_config_labels.go

Recent TuneD realtime profile is using `tsc=reliable`
instead of `tsc=nowatchdog`.  Adjust
`[reboots][machine_config_labels]` to reflect this.  See:
https://github.com/redhat-performance/tuned/pull/423
Signed-off-by: Jiri Mencak <jmencak@users.noreply.github.com>

e2e: check for tsc=reliable instead of tsc=nowatchdog

---

docs/performanceprofile/performance_controller.md

Environment variable `PERFORMANCE_PROFILE_INPUT_FILES` used in render mode
should be a comma separated list of PerformanceProfile manifests not a
folder.

doc: fix description of the `PERFORMANCE_PROFILE_INPUT_FILES` env var

---

test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go

OCP >= 4.12 wants to have stricter podsecurity rules.
In our e2e tests we do a bunch of stuff, including running privileged pods. We just annotate the test namespace(s) to signal we need top  privileges. Since e2e tests run in very controlled envs (CI mostly), and since test namespace should be gone anyway once the e2e tests are finished, this is still fair game.
Signed-off-by: Francesco Romani <fromani@redhat.com>

e2e: add podsecurity labels 

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

When a performance profile is applied, the priority of the
ksoftirqd and rcuc realtime attributes are set to to FIFO:11.
The rcutree.kthread_prio must be set accordingly to avoid
RCU stall situations with rt kernel
Signed-off-by: Vitaly Grinberg <vgrinber@redhat.com>

Bug 2102450: set rcutree.kthread_prio to ksoftirqd prio

---

pkg/apis/performanceprofile/v2/performanceprofile_validation.go

Output when forbidden CPU's overlapping is not formatted and it shows the object value
Launch PerformanceProfile as this one:
spec:
cpu:
isolated: "0-2"
reserved: "0-2"
apply -f *.yaml
```
The PerformanceProfile "performance" is invalid: spec.cpu: Invalid value: v2.CPU{Reserved:(*v2.CPUSet)(0xc001017d30), Isolated:(*
v2.CPUSet)(0xc001017d20), BalanceIsolated:(*bool)(nil), Offlined:(*v2.CPUSet)(nil)}: **reserved and isolated cpus overlap**: [0 1 2] 
```
Also the code shows error as invalid, and it should be forbidden.
Fixed output:
```
The PerformanceProfile "performance" is invalid: spec.cpu: Forbidden: reserved and isolated cpus overlap: [0 1 2]
```
Also fixed for "reserved and offlined" and "isolated and offlined".

Fix CPU's overlapping error output

---

pkg/apis/performanceprofile/v1/performanceprofile_types.go
pkg/apis/performanceprofile/v2/performanceprofile_types.go

Fix optional parameter in workloadHints.
To improve readability and avoid mistakes add +default=true to realTime Hint API. If no realTime parameter is added in performanceProfile, realTime is set to true and the user can get Spec.WorkloadHints.RealTime
Add +optional to workloadHints API
Add +default=true to realTimeHint to maintain compatibility with previous versions

Add +optional and +default=true to workloadHints API

---

manifests/20-performance-profile.crd.yaml
pkg/apis/performanceprofile/v1/performanceprofile_types.go
pkg/apis/performanceprofile/v1/zz_generated.deepcopy.go
test/e2e/performanceprofile/functests/1_performance/performance.go

Field spec.cpu.offlined must be also in v1 API as v1 and v2 API must be compatible
- [] Add test

Bug 2108222 - Add offlined cpus to v1 api

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
pkg/performanceprofile/controller/performanceprofile/components/utils.go
pkg/performanceprofile/controller/performanceprofile/components/utils_test.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

The tuned irqbalance plugin clears the irqbalance banned CPUs list when tuned starts. The list is then managed dynamically by the runtime handlers.
On node restart, the tuned pod can be started AFTER the workload pods (kubelet nor kubernetes offers ordering guarantees when recovering the node state); clearing the banned CPUs list while pods are running and compromising the IRQ isolation guarantees. Same holds true if the NTO pod restarts for whatever reason.
The fix is twofold:
1. disable the irqbalance plugin, so tuned doesn't clear the irqbalance banned list anymore.
2. depend on crio to reset the banned CPU list earlier in the boot
in #413 we add e2e tests to verify the aforementioned steps.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2105123
Signed-off-by: Francesco Romani …

Bug 2105123: tuned: disable irqbalance

---

test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go

this PR combine both #436 and #437. We need _both_ to unbreak the lane, but either alone is not sufficient, and they are unrelated to each other

e2e: perfprof: unbreak the e2e-gcp PAO lane

---

test/e2e/reboots/kernel_parameter_add_rm.go
test/e2e/reboots/machine_config_labels.go
test/e2e/reboots/operator_test.go
test/e2e/reboots/stalld.go

Wait for a flip to MachineConfigPool UpdatedMachineCount == 0 prior to
waiting for it to be updated (== 1) again.

e2e: fix a race in [reboots] tests.

---

test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go

Some tests in the suites require setting the number of CPUs to be used by the latency pod. If the available cpus is not sufficient, the tests will be skipped.
The goal of the suite is to verify that the main tests of the latency tools are executed as expected.
So to overcome this, update the isolated CPUs for this suite to CPU set that guarantees to execute the tests properly, and restore the initial set when finished.

e2e: performance: configure isolated cpus in the profile

---

test/e2e/performanceprofile/functests/4_latency/latency.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

A couple of log improvements for latency-tests to make it easier to debug in case of test failures.

latency-tests: improve logs clarity

---

cmd/cluster-node-tuning-operator/main.go
pkg/client/client.go
pkg/client/clients.go
pkg/client/listers.go
pkg/config/config.go
pkg/manifests/manifests.go
pkg/operator/controller.go
pkg/operator/hypershift.go
pkg/operator/profilecalculator.go
test/e2e/basic/available.go
test/e2e/basic/custom_node_labels.go
test/e2e/basic/custom_pod_labels.go
test/e2e/basic/default_irq_smp_affinity.go
test/e2e/basic/metrics_cert_rotation.go
test/e2e/basic/modules.go
test/e2e/basic/netdev_set_channels.go
test/e2e/basic/profile_status.go
test/e2e/basic/rollback.go
test/e2e/basic/sysctl_d_override.go
test/e2e/basic/tuned_builtin_expand.go
test/e2e/basic/tuned_errors_and_recovery.go
test/e2e/reboots/kernel_parameter_add_rm.go
test/e2e/reboots/machine_config_labels.go
test/e2e/reboots/stalld.go
test/e2e/util/util.go

/cc @jmencak 
This PR enables the Node Tuning operator to run in HyperShift environments, to manage the tuning of hosted cluster nodes.
**A brief explanation of the design:**
The operator will run in the management cluster, in the hosted cluster control plane namespace, alongside some other cluster operators like OLM, network operator, etc. It will manage Tuned / Profile objects and a Tuned daemonset that exist in the hosted cluster API, but are subordinate to Tuned YAMLs in ConfigMaps in the management cluster hosted control plane namespace. To create Tuned in this environment, a user will create a ConfigMap which contains a Tuned manifest in the data.tuned field, and then reference this ConfigMap in the NodePool API spec.tunedConfig field. The NTO operator watches for the ConfigMap in …

Enable basic sysctl tuning of HyperShift hosted cluster nodes

---

assets/performanceprofile/scripts/clear-irqbalance-banned-cpus.sh
pkg/performanceprofile/controller/performanceprofile/components/assets_scripts_test.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml

irqbalance: add unit to clear the cpu ban list
Add a oneshot unit to clear the CPU ban list once and explicitely per node reboot.
CRI-O has a facility to restore the irqbalance ban list, which only partially fit this scenario.
For this reason, to really ensure the desired behavior we tamper the CRI-O private irqbalance ban list, until CRI-O gains better
support for this flow.
Depends on https://github.com/openshift/cluster-node-tuning-operator/pull/396
Copy of https://github.com/openshift/cluster-node-tuning-operator/pull/413

irqbalance: add unit to clear the cpu ban list #413 

---

pkg/client/clients.go
pkg/operator/controller.go
pkg/operator/hypershift.go
pkg/operator/profilecalculator.go

In #390 we added the dynamic go-client to look at MachineSets to map Nodes to HyperShift NodePools in the function `getNodePoolNameForNode(node *corev1.Node)`, without needing a dependency on the cluster-api. Since then,  https://github.com/openshift/hypershift/pull/1702 has merged which adds the NodePool labels directly to the Nodes in HyperShift, removing the need for the dynamic client.
This PR greatly simplifies the function `getNodePoolNameForNode(node *corev1.Node)` in `pkg/operator/hypershift.go` and removes the dynamic client.
This has been manually tested with the latest version of the HyperShift work in https://github.com/openshift/hypershift/pull/1651.

Remove dynamic client and simplify getNodePoolNameFromNode

---

hack/run-functests.sh
test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

The tests in 5_latency_testing should run only on-demand and by using different make target with relevant dependencies. Skip this package using ginkgo skipPackage flag.
And fail the suite if the binary is not found.

hack: performance: skip tests under 5_latency_testing

---

Dockerfile

Manual cherry-pick from https://github.com/openshift/cluster-node-tuning-operator/pull/406

OCPBUGS-851: [release-4.11] Dockerfile: provide full URL to CentOS stream image #406 

---

pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
pkg/performanceprofile/utils/testing/testing.go

Improve legibility and facility to add test in tuned test suite. 
Remove Regex and parse data from template
Difficulty to add new test and understand the current ones
Test are launched in ci under ci/prow/e2e-no-cluster  lane

Improve tuned test suite

---

pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml

When workload realtime hint is explicitly set to false there is no reason to set RPS realtime related configuration. In that case, the entire RPS configuration will not be set including systemd RPS device services and low latency crio hook.

Remove RPS configuration wihen realtime workload hint is explicitly set to false

---

test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go

Some tests in the suites require setting the number of CPUs to be used by the latency pod. If the available cpus is not sufficient, the tests will be skipped.
The goal of the suite is to verify that the main tests of the latency tools are executed as expected.
So to overcome this, update the isolated CPUs for this suite to CPU set that guarantees to execute the tests properly, and restore the initial set when finished.
This is a backport of #429 to release 4.11

OCPBUGS-63: e2e: performance: Update PP isolated cpus

---

pkg/operator/controller.go
pkg/operator/hypershift.go
pkg/operator/mc.go
pkg/operator/profilecalculator.go
pkg/util/strings_map.go

This PR enables NTO to generate MachineConfigs for setting kernel boot parameters in HyperShift environments. NTO will embed the MachineConfig manifests in ConfigMaps with labels specifying that it is NTO-generated and what NodePool it should be applied to. The ConfigMaps will be created in the hosted control plane namespace, and will need to be picked up by the NodePool controller in order to be applied (will add link to HyperShift PR once it is open).
This is "phase-2" of the design outlined in the following enhancement: https://github.com/openshift/enhancements/pull/1229
/cc @jmencak

HyperShift: Create ConfigMaps for NTO-generated MachineConfigs

---

docs/performanceprofile/configuration_hotfixes.md
pkg/apis/performanceprofile/v2/performanceprofile_types.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/performanceprofile/controller/performanceprofile/components/profile/profile.go
test/e2e/performanceprofile/functests/1_performance/performance.go

A new annotation: "performance.openshift.io/enable-rps" when added to a performance profile, will enable all RPS settings while ignoring the realtime workload hint settings.
This can be used as an emergency override for special cases where realtime workload hint is false but RPS settings still need to be applied.

Performance profile Annotation to enable RPS

---

test/e2e/basic/metrics_cert_rotation.go
test/e2e/util/util.go

Fix `metrics_cert_rotation.go` on systems where the host OS libraries do not match container libraries.  An alternative is to rely on container-shipped `openssl`, but we probably do not wish to add this dependency to the container image.
Other fixes:
- insufficient number of arguments in `test/e2e/util/util.go`
/cc @dagrayvid

e2e: Fix metrics_cert_rotation.go

---

test/e2e/performanceprofile/functests/1_performance/performance.go

Automates https://bugzilla.redhat.com/show_bug.cgi?id=2114681

Add verification on kernel param rcutree.kthread

---

assets/performanceprofile/tuned/openshift-node-performance
docs/performanceprofile/performance_profile.md
manifests/20-performance-profile.crd.yaml
pkg/apis/performanceprofile/v1/performanceprofile_types.go
pkg/apis/performanceprofile/v1/zz_generated.deepcopy.go
pkg/apis/performanceprofile/v2/performanceprofile_types.go
pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
pkg/apis/performanceprofile/v2/zz_generated.deepcopy.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
pkg/performanceprofile/utils/testing/testing.go
test/e2e/performanceprofile/cluster-setup/manual-cluster/performance/performance_profile.yaml
test/e2e/performanceprofile/functests/0_config/config.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

Add new workloadHint PerPodPowerManagement
PerPodPowerManagement workloadHint allows power management to be configured on a per pod (v.s. per node) basis. Using this workloadHint will configure the node to run with c-states and p-states enabled, instead of being disabled (which is the default).
WorkloadHints HighPowerConsumption and PerPodPowerManagement cannot be enabled at the same time.

Implement new workloadHint perPodPowerManagement

---

test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go

Manual cherry-pick of https://github.com/openshift/cluster-node-tuning-operator/pull/438
e2e: add podsecurity labels, disable OCP label sync
Backport and squash two commits related to handling
of security labels:
b0024584fb244691097916665d5cec1e7c1dc5f4 (partial):    
OCP >= 4.12 wants to have stricter podsecurity rules.
In our e2e tests we do a bunch of stuff, including running privileged
pods. We just annotate the test namespace(s) to signal we need top
privileges. Since e2e tests run in very controlled envs (CI mostly),
and since test namespace should be gone anyway once the e2e tests
are finished, this is still fair game.
Signed-off-by: Francesco Romani <fromani@redhat.com>
b0024584fb244691097916665d5cec1e7c1dc5f4
podsecurity: disable OCP label sync
Per last OCP recommendation …

OCPBUGS-1131: [release-4.11] e2e: perfprof: unbreak the e2e-gcp PAO lane

---

cmd/performance-profile-creator/cmd/root.go
test/e2e/performanceprofile/functests-performance-profile-creator/1_performance-profile_creator/ppc.go
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1c.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3c.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4c.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5a.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5b.yaml
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile6.json
test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile6.yaml

Add PPC argument for perPodPowerManagement WorkloadHint 
After add the new workloadHint https://github.com/openshift/cluster-node-tuning-operator/pull/415 it is necessary to add a new argument in Performance Profile Creator to configure it.
-

Add PPC argument for perPodPowerManagement WorkloadHint

---

pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go

workloadHints are not included in validateFields()
Thus, are not applying correctly. 
Also validateFields is not being testing.
Related: https://github.com/openshift/cluster-node-tuning-operator/issues/339

workloadHints not included in validateFields()

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

If hugepages or additional arguments cmdline is no present in the perfromanceProfile, the ouptut of /proc/cmdline is dirty with "+" as:
Before fix:
[...]
rcutree.kthread_prio= 11 + + intel_pstate=passive
After fix:
[...]
rcutree.kthread_prio= 11 intel_pstate=passive

Clean output of kernel args if no hugepages or additional args are present

---

pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go

Default value of RealTime hit is enabled.

Set default RealTime hint to true and add to conversion

---

manifests/30-monitoring.yaml

This is needed in HyperShift management clusters when HyperShift is configured to have hosted control plane metrics scraped by the platform monitoring prometheus. In this case, metrics from all NTOs in all hosted control plane namespaces will be summed into one count. We want one count per cluster. This has no impact on standalone OCP.

Adjust nto_custom_profiles:count metric to count by _id

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

Maintain backwards compatibility after workloadHints change https://github.com/openshift/cluster-node-tuning-operator/pull/339
The workloads hints feature introduced in 4.11 does not preserve the default tuning settings from 4.10: intel_pstate=disabled.
So if the customer wants to preserve the behavior they have in 4.10, they have to update their performance profile and incur another reboot.
The correct behavior the default setting should be preserved.
Add intel_pstate=disable to default configuration with no hints

OCPBUGS-2167: Workload hints backwards compatibility intel_pstate=disable

---

test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go

Lately, the latency testing suite starting to fail and that was because the tests didn't reconfigure the performance profile to be compatible with the tests prerequisites, hence they were using the existing profile mainly missing the correct isolated CPUs value.
The reason for not changing the profile is that there were no nodes with sufficient CPUs on the compute nodes. This check was actually fetching the allocatable CPUs (total of isolated) and that is excluding the resreved CPUs, and this is expected because this is the configuration of the PP that was applied earlier on the cluster.
To fix that, fetch that CPUs value from node capacity instead in order to include all CPUs on the node.

e2e: perfprof: get cpus from node capacity

---

pkg/operator/hypershift.go

This PR enables NTO to support the Tuned ConfigMap key `tuned` and `tuning` in HyperShift.
This is required so that we can rename this key from `tuned` and `tuning` on the HyperShift side without disrupting HyperShift CI. We are renaming this and the spec.TunedConfig section in order to keep the names more general so that we can reference PerformanceProfiles in these ConfigMaps later on when we enable the PerformanceProfile controller.
I split this PR into two commits, so that once the rename happens on the HyperShift side, we can simply revert the second commit
See: https://github.com/openshift/hypershift/pull/1802
/cc @jmencak @jlojosnegros

HyperShift: rename Tuned ConfigMap key from tuned to tuning

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/cluster-setup/manual-cluster/performance/performance_profile.yaml
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

Maintain backwards compatibility after workloadHints feature
The workloads hints feature introduced in 4.11 does not preserve the default tuning settings from 4.10: intel_pstate=disabled.
So if the customer wants to preserve the behavior they have in 4.10, they have to update their performance profile and incur another reboot.
The correct behavior the default setting should be preserved.
manual cherry-pick https://github.com/openshift/cluster-node-tuning-operator/pull/480:

OCPBUGS-764: [release-4.11] Add intel_pstate=disable to default configuration with no hints (#480)

---

test/e2e/performanceprofile/functests/1_performance/irqbalance.go

We added a e2e test to ensure that the implicit and uncontrollable recover of the irqbalance settings performed by crio was doing what we expect (and actually assume) it would.
The test was becoming flakier and flakier over time ever since.
The test was well intentioned, but it tried to restart crio from within a container.
And this is a terrible idea in the first place, and a idea which could not possibly work in any sane environment in the second place.
A sane container environment just can't allow a container, no matter how privileged, to mess up with the runtime, for very obvious and very basic security reasons.
So the test, which still has its merits, need to be redesigned from scratch. This can take time, and most notably, would need a different approach. Possibly, the only sane way …

e2e: perfprof: remove broken test

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

New per-CPU kthread introduced to handle timer expiry named `ktimers/n` where `n` is the CPU id where it is executing.
Recommended priority is the same as ksoftirqsd.

OCPBUGS-1334: Configure ktimers scheduler priority to match ksoftirqsd's

---

test/e2e/performanceprofile/functests/4_latency/latency.go
test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

Instead of having the neccessaty to copy all the tests\` output into a log file and then read everything from the log, we can skip this extra step and read the log directly from the pod. The latency test tools, i.e. oslat/cyclictest/hwlatdetect, redirect their output to stdout/stderr anyway, so by reading pod\'s log we get tools\` output.
In addition, this patch is a prerequisite for
https://github.com/openshift-kni/cnf-features-deploy/pull/1301

pao: latency-tests: read test log directly from pod

---

docs/performanceprofile/configuration_hotfixes.md

PerformanceProfile controller generates Tuned CRs with priority 20.  We need to make the priority of the "hotfix" CRs higher, for example 15.
/cc @yanirq 
/cc @MarSik

Configuration hotfixes documentation fixes

---

test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go

Latency testing suite is failing but there is hardly useful info that is logged out to the console.
Add more logs to clarify the steps that are being executed to enable better debugging, along with some minor fixes.

e2e: performance profile: add logs and minor fixes

---

test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go

On a system with offline cpus (like when nosmt is being used), the default_smp_affinity still shows all bits as one even though the respective cpus are offline.
[core@cnfdd7 ~]$ cat /proc/irq/default_smp_affinity ff,ffffffff,ffffffff,ffffffff
[core@cnfdd7 ~]$ cat /sys/devices/system/cpu/online 0-51
Our tests did not expect that.
The test is trying to check if all online cpus can handle interrupts before the tuning is applied and so this fix simply removes the offline cpus from the default affinity mask.

Fix two irqbalance tests - smp affinity vs online

---

Dockerfile.rhel9

This is a preliminary PR to add support for [RHEL-9](https://issues.redhat.com//browse/RHEL-9) image-based NTO.
Other changes:
- switch from three to two-stage build for [RHEL-8](https://issues.redhat.com//browse/RHEL-8)

Add Containerfile for RHEL-9

---

.ci-operator.yaml
go.mod
pkg/client/client.go
pkg/generated/clientset/versioned/fake/register.go
pkg/generated/clientset/versioned/scheme/register.go
pkg/operator/profilecalculator.go
pkg/performanceprofile/cmd/render/render.go
pkg/tuned/controller.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go
test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go

This change switches to golang 1.19 and addresses formatting issues in the code fixed by the switch to golang 1.19.

Switch to golang 1.19

---

Makefile
hack/render-sync.sh

For every change in PAO's assets, we should render the manifests and copy the data into `/test/e2e/performanceprofile/testdata/render-expected-output/`
This patch adds a make target to automate the process. For now, the make target itself should be called manually. If it proves itself useful, we can add it as a dependency of other targets.

performance-profile: render: make target for render sync

---

docs/performanceprofile/performance_controller.md
pkg/performanceprofile/cmd/render/cmd.go
pkg/performanceprofile/cmd/render/manifests.go
pkg/performanceprofile/cmd/render/render.go
pkg/performanceprofile/controller/performanceprofile/components/runtimeclass/runtimeclass.go
test/e2e/performanceprofile/functests-render-command/1_render_command/render_suite_test.go
test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_runtimeclass.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

This PR updates our render command to be more inline with a more flexible approach during the bootstrapping process.
Typically operators that need to generate files during bootstrapping might need some initial cluster state information in order to correctly render the resource files, some have static information that is retrieved and others more dynamic. In this approach we take the pattern used by MCO where the manifest directory is inspected and the relevant files are read in and parsed to render out the resulting configurations. ([see](https://github.com/openshift/machine-config-operator/blob/bff62e7ea81a3180860b28068fd33a7209475f14/pkg/controller/bootstrap/bootstrap.go#L52-L232))
This affords us some niceties like not being over prescriptive with file names for performance profile …

CNF-6946: feat: expand support to render based on files in dir

---

test/e2e/performanceprofile/functests/4_latency/latency.go

While waiting for latency test pod to transition to `Succeeded` phase, we are not taking into account
the `LATENCY_TEST_DELAY` value when calculating
the timeout.
if `LATENCY_TEST_DELAY` > 120 then we might failed the test although it's still running.

e2e:latency: count LATENCY_TEST_DELAY in timeout

---

test/e2e/performanceprofile/functests/1_performance/hugepages.go

It confuses test parsers and just not nice.

Remove trailing space from test name

---

test/e2e/performanceprofile/functests/4_latency/latency.go
test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

Instead of having the neccessaty to copy all the tests\` output into a log file and then read everything from the log, we can skip this extra step and read the log directly from the pod. The latency test tools, i.e. oslat/cyclictest/hwlatdetect, redirect their output to stdout/stderr anyway, so by reading pod\'s log we get tools\` output.

[release-4.11] [manual] OCPBUGS-5020: pao: latency-tests: read test log directly from pod

---

Makefile
hack/run-update-testing.sh
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/nodes_test.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/test_suite_performance_kubelet_node_test.go

Changes in Makefile to split performance test in two lanes
Before this PR ci/prow/e2e-gcp-pao takes a lot of time, getting many timeouts and with a unstable behavior.
Depends on: https://github.com/openshift/release/pull/35029

Updating profile new lane

---

pkg/client/listers.go
pkg/metrics/server.go
pkg/operator/controller.go
pkg/tuned/controller.go
pkg/util/os.go

This change adds authentication to the /metrics endpoint by requiring client key and certificate.
Resolves: OCPBUGS-4647

OCPBUGS-4647: Add authentication to the /metrics endpoint

---

pkg/metrics/server.go
pkg/operator/controller.go

In HyperShift environments, don't watch the CA ConfigMap. 
In HyperShift the CA cert is in the hosted control plane namespace along with NTO, so we can mount it into the operator Pod.
/cc @jmencak

OCPBUGS-6057: Skip watch on CA ConfigMap in HyperShift

---

hack/render-sync.sh
pkg/performanceprofile/cmd/render/cmd.go
pkg/performanceprofile/cmd/render/render.go

klog flags are not initiated for the render command, so
passing klog arguments like `--v` would be ignored
In addition, added a few logs for debugging purposes.

render: initialize klog flag

---

pkg/tuned/controller.go
pkg/tuned/status.go

Kernel parameters can be changed at runtime via various configuration files in `/run/sysctl.d/*.conf`, `/etc/sysctl.d/*.conf` and `/etc/sysctl.conf`
By default, NTO's node agents do not override these settings.  This matches the default TuneD behaviour `reapply_sysctl=1` in `tuned-main.conf`.
While NTO can be configured to set `reapply_sysctl=0` in `tuned-main.conf` to let TuneD manage all sysctls and override the host-level configuration files, many users do not know about this functionality.
This PR makes this potential issue more visible to users by reporting it issue via making the Profile Degraged with a status message set.
Also see:
* https://github.com/redhat-performance/tuned/pull/492
* https://github.com/redhat-performance/tuned/pull/501

Report host-level sysctls in conflict with TuneD ones

---

pkg/tuned/controller.go

There are edge cases (e.g. OCPBUGS-7384), where full resync seems to be necessary.  Remove an optimization to skip Tuned and Profile resync for NTO operands when the old and new Accessor are the same.  This will add on average 4% more CPU cycles, but should ensure more reliable operation.

OCPBUGS-7384: Remove optimization to allow full resync

---

pkg/performanceprofile/controller/performanceprofile/components/utils_test.go
pkg/performanceprofile/profilecreator/profilecreator_test.go
test/e2e/performanceprofile/functests/1_performance/netqueues.go

Remove trailing spaces from all tests which have them.

OCPBUGS-7745: Remove trailing spaces from test names

---

pkg/apis/tuned/v1/tuned_types.go
pkg/operator/controller.go
pkg/operator/status.go
pkg/tuned/controller.go

Generally, nodes with different topologies are discouraged to be used in
the same MachineConfigPool (MCP).  Consider two nodes with different CPU
count.  If they belong to the same MCP, they will share the same
NTO-generated MachineConfig (MC).  It is then entirely possible for the
operator's node agent together with TuneD to return different CPU
parameters (e.g. systemd.cpu_affinity) in the kernel command line for
each of these nodes.  This will result in a race to update NTO-generated
MC and ensuing boot loops.
This change adds annotations to NTO-generated MCs to keep track of the
configuration based on which they were generated.  Updates to these MCs 
are only accepted if they come from a different input (Tuned CR)
configuration.
See: https://issues.redhat.com/browse/PSAP-993
Suggested …

Handle different # of CPUs are in the same MCP

---

hack/test-upstream-tuned.sh

Adding `hack/test-upstream-tuned.sh` script to run NTO and PerformanceProfile controller tests on a cluster with a specific TuneD version from upstream.
Example invocations
```
ORG=quay-user hack/test-upstream-tuned.sh
ORG=quay-user TUNED_COMMIT=ce3d0926 hack/test-upstream-tuned.sh
```
This script assumes a deployed OpenShift cluster and an environment configured to write the locally built IMAGE to an image repository.
Also note `cvo_scale()` scales down CVO replica to 0 to prevent it from overriding the custom NTO image.  If you wish to upgrade your cluster, do not use this script.

Add a script to validate upstream TuneD

---

cmd/cluster-node-tuning-operator/main.go

Recent PR431 broke HyperShift presubmits.  The code is not HyperShift aware.

Fix failing HyperShift presubmits

---

HACKING.md
manifests/20-performance-profile.crd.yaml
pkg/apis/performanceprofile/v2/performanceprofile_types.go

kubectl explain to explicitly state worloadHint default values
Even though default values are set for the API, when kubebuilder builds
the CRDs it does not give end users a hint about the default values of
the fields. Improve the field comments to mention the default field
values. This way, admins who run oc explain can clearly see that the
realTime field has a different default value than the other 2 fields.
-----------------------
Hacking instructions: Deploy custom tuning operator image on OpenShift
Add instructions to deploy the custom tuning operator image on
OpenShift.
-----------------------
With the change:
~~~
[akaris@linux perf-profile-creator]$ oc explain performanceprofile.spec.workloadHints 
KIND:     PerformanceProfile
VERSION:  performance.openshift.io/v2
RESOURCE: …

kubectl explain to explicitly state workloadHint default values

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/utils/bugzilla/client.go
test/e2e/performanceprofile/functests/utils/jira/status.go
test/e2e/performanceprofile/functests/utils/utils.go

This adds an automatic skip of known issues based on the issue status. The moment an issue is fixed, the skip will no longer be effective.
See the two added methods:
testutils.KnownIssueBugzilla(2181546)
testutils.KnownIssueJira("OCPNODE-1538")

Skip tests depending on Jira or Bz issue status

---

test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go

The node selector tests are using a utility function that removes labels from nodes.
When the function tries to patch nodes with updated labels it will wait for the matching mcp to be updated. In case no update to node labels where done the update will time out.
The fix is to only wait for mcp updates if there was actually one.

OCPBUGS-10998: Fix updating nodeSelector test

---

pkg/operator/controller.go
pkg/operator/mc.go

PR558 added support for informing users about nodes with incompatible topologies within the same MCP.  However, a recovery from this state is not handled in a user-friendly way.  Currently, the entire MCP or NTO-generated MC needs to be deleted or manually adjusted to recover.
This PR fixes the situation so that when the MachineCount of the MCP which had nodes with conflicting topologies is equal or less than 1, updates to the NTO-generated MC are allowed even though the input configuration did not change and the new kernel parameters do not match the MC's kernel parameters.
Fixes OCPBUGS-10247

OCPBUGS-10247: Update NTO-generated MC on MachineCount <= 1

---

cmd/cluster-node-tuning-operator/main.go

The `--enable-leader-election=false` currently does not work.  Leader election is always on.  This change fixes the issue.

Make the enable-leader-election option work

---

test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/utils/tuned/tuned.go

There might be a race condition when the mcp is ready after it got updated but tuned profile is not.
Let's wait for tuned and stalld to get started.
In addition, added few general fixes/optimization in order to cut the test's runtime.

OCPBUGS-11083: e2e: profile updates tests revised

---

hack/render-sync.sh
test/e2e/performanceprofile/testdata/render-expected-output/manual_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_runtimeclass.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

The render command is generating manifests with uid now. we don't need it to be part of the data for our render-expected-output so let's remove it

render: remove uid from render-sync target

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go

When RealTime workload hint configured as false, we should
explicitly disable stalld service

OCPBUGS-10635: workload-hints: disable stalld when rt disabled

---

test/e2e/performanceprofile/functests/utils/utils.go

This option can be used for full release verification where known issues are treated as failures. This is needed to avoid releasing content with known bugs without noticing.

A new env var NO_BZ_CHECKS disables Bz and Jira status checks

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
pkg/tuned/controller.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

PerformanceProfile Controller (PPC) generates TuneD configuration out of template file `assets/performanceprofile/tuned/openshift-node-performance`.
This PR fixes several issues with this file:
- Remove `TuneD [scheduler]` plug-in options that do not exist.
- Add a note about sysctl existing only in non-rt kernels.
Also, as a temporary fix we revert the removal of optimizations done in #567 as a way of addressing OCPBUGS-7384.  However, we later found OCPBUGS-7384 was a user configuration issue so the change is not really needed at this point as we ran with it since OCP 4.5 with no issues.

OCPBUGS-11150: Revert #567 and cleanup PPC-generated TuneD config

---

test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/utils/tuned/tuned.go

This is manual cherry-pick of https://github.com/openshift/cluster-node-tuning-operator/pull/600
replaces https://github.com/openshift/cluster-node-tuning-operator/pull/603

 [release-4.13] [manual] OCPBUGS-11336: e2e: profile updates tests revised

---

assets/tuned/manifests/ds-tuned.yaml

`subPath`s are broken in current versions of k8s and also suffer from other issues on RHOCP.  Do not use them.  See:
- https://github.com/kubernetes/kubernetes/issues/89181
- https://issues.redhat.com/browse/OCPBUGS-5255

OCPBUGS-11914: Remove subPaths, they are broken

---

assets/performanceprofile/scripts/cpuset-configure.sh
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go

on RHEL 9 and newer kernels, the sysfs previously relied on to disable CPU load balancing is no longer available. Instead, cpu load balancing must be configured through cgroups.
To configure a cpuset to have load balance disabled (on cgroup v1), a cpuset cgroup must have `cpuset.sched_load_balance` set to 0 (disable), and any cpuset that contains the same set as `cpuset.cpus` must also have `cpuset.sched_load_balance` set to disabled.
To do this, we must move systemd and all host processes to a separate cpuset off of the root cgroup, and manually configure it to use the reserved cpus set by set_cpuaffinity. This won't have any effect on the actual processes themselves, but will open the opportunity for the root cgroup to have load balance disabled.
Also, preconfigure the machine.slice …

[release-4.13] OCPNODE-1539: perf profile: add script for preparing cgroups for CPU load balance disabling

---

assets/performanceprofile/scripts/cpuset-configure.sh
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go

on RHEL 9 and newer kernels, the sysfs previously relied on to disable CPU load balancing is no longer available. Instead, cpu load balancing must be configured through cgroups.
To configure a cpuset to have load balance disabled (on cgroup v1), a cpuset cgroup must have `cpuset.sched_load_balance` set to 0 (disable), and any cpuset that contains the same set as `cpuset.cpus` must also have `cpuset.sched_load_balance` set to disabled.
To do this, we must move systemd and all host processes to a separate cpuset off of the root cgroup, and manually configure it to use the reserved cpus set by set_cpuaffinity. This won't have any effect on the actual processes themselves, but will open the opportunity for the root cgroup to have load balance disabled.
Also, preconfigure the machine.slice …

OCPNODE-1539: perf profile: add script for preparing cgroups for CPU load balance disabling

---

test/e2e/performanceprofile/functests/1_performance/performance.go

Add missing PAO test id to enble proper reporting of the test's result.

OCPBUGS-12229: e2e: add missing test id

---

pkg/operator/controller.go

This is a partial revert of
https://github.com/openshift/cluster-node-tuning-operator/pull/558 and https://github.com/openshift/cluster-node-tuning-operator/pull/585
that handle different topology of machines in the same MCP.  The code was not properly tested on HyperShift and causes a SEGV there.

OCPBUGS-12883: Revert PR558 and PR585 partially

---

test/e2e/performanceprofile/functests/1_performance/performance.go

Fix `[test_id: 59572] Check RPS Mask is applied to atleast one single rx queue on all veth interface` test bug that occurs when running against a cluster with multiple worker nodes.
@mrniranjan @jlojosnegros Please, take a look.

OCPBUGS-10424: e2e: Fix RPS test for multi-worker cluster

---

test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/utils/tuned/tuned.go

This PR comes to fix :
- stalld flaky tests the occur due to race conditions
- afterAll function should be skipped if tests are skipped to save testing time and irrelevant errors.
- skip flaky update test due to OCPBUGS-12836

OCPBUGS-11083: pao e2e: fix update test suit timeouts

---

pkg/operator/controller.go

In HyperShift, WatchNamespace() is the namespace in hosted cluster where Profile and Tuned objects exist, which is distinct from the OperatorNamespace() which is named based on the name of the HostedCluster. 
In standalone OCP, these will be the same namespace (`openshift-cluster-node-tuning-operator`) (by default, at least...)

OCPBUGS-12978: use WatchNamespace() when deleting Profiles

---

pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml

The current code configures the cpu balancing management cpuset cgroup structure only when Workload partitioning is enabled.
That is wrong as even standard clusters use that feature.

OCPBUGS-13148: Configure cpu balancing cpu sets for all clusters

---

pkg/operator/status.go

Add PerformanceProfiles as a RelatedObject for the must-gather tool.

OCPBUGS-13262: Add PerformanceProfiles to 'oc adm must-gather'

---

pkg/operator/status.go

Reverts openshift/cluster-node-tuning-operator#582
HyperShift conformance tests are failing.

OCPBUGS-13262: Add PerformanceProfiles to 'oc adm must-gather: REVERT

---

test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/utils/tuned/tuned.go

This is partial manual cherry-pick of https://github.com/openshift/cluster-node-tuning-operator/pull/626
covering stalld and workload hints flaky tests that occur due to race conditions

[release-4.13] [manual] OCPBUGS-11336: pao e2e: fix update test suit timeouts

---

test/e2e/performanceprofile/functests/8_reboot/devices.go
test/e2e/performanceprofile/functests/8_reboot/test_suite_reboot_test.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

Add test to verify the device recovery on SNO nodes.
This test has unusual and potentially challenging requirements
- SRIOV stack fully configured
- SNO cluster
- needs to reboot the SNO cluster
For this reason, the test requires to be given explicit which node to use, and skips if a target node is not explicitely given using the `DEVICE_RECOVERY_TARGET_NODE` environment variable.
SRIOV setup is assumed, but the test makes no attempt to enforce, intentionally. The SRIOV device to consume can be overridden using the `DEVICE_RECOVERY_RESOURCE_NAME` environment variable, depending on the setup.    
The test needs to create test workload (deployment, pod) but more importantly needs to reboot the node. It tries hard to tolerate connection loss to the control plane (SNO rebooted -> control …

OCPBUGS-14137: e2e: perfprof: add SNO device recovery test

---

hack/render-sync.sh
test/e2e/performanceprofile/testdata/render-expected-output/manual_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_runtimeclass.yaml

The render command is generating manifests with uid now. we don't need it to be part of the data for our render-expected-output so let's remove it

[release-4.13][manual] OCPBUGS-11851: render: remove uid from render-sync target (#594)

---

hack/run-functests.sh
hack/run-update-testing.sh

Some ci-lanes are running test-suites by mistake.

OCPBUGS-14756: [test] [e2e] Check ci lanes are executing the right test suites

---

manifests/20-tuned.crd.yaml
pkg/apis/tuned/v1/tuned_types.go

Add `minLength == 1` to Tuned `spec.profile[].name` and `spec.recommend[].profile`.  The profile name always has at least 1 character and this will also prevent `TuneD` daemon traceback when recommending an empty-string profile.
Also see: https://github.com/redhat-performance/tuned/issues/537

OCPBUGS-12756: Add minLength restriction to Tuned CR

---

test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

Following the bug OCPBUGS-5219, automate the verification process by adding a new test for all latency tools to verify that the tests run with LATENCY_TEST_DELAY value greater than 120.
Signed-off-by: Ilya Tyomkin <ityomkin@redhat.com>

e2e: verify latency tests run with LATENCY_TEST_DELAY>120

---

test/e2e/performanceprofile/functests/8_reboot/devices.go

The new test image gained compatibility with SRIOV device plugin >= 4.13

test: perfprof: devices: fix default test image

---

go.mod
pkg/apis/performanceprofile/performance_test.go
pkg/performanceprofile/cmd/render/render.go
pkg/performanceprofile/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/functests-performance-profile-creator/1_performance-profile_creator/ppc.go
test/e2e/performanceprofile/functests-render-command/1_render_command/render_suite_test.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go

Currently we are using two YAML packages:
1. `github.com/ghodss/yaml v1.0.0`
2. `sigs.k8s.io/yaml v1.3.0`
The `github.com/ghodss/yaml` package is no longer actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`. It is actively maintained by Kubernetes SIG, and also widely used in K8s projects.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.
```
$ go mod why -m github.com/ghodss/yaml
github.com/openshift/cluster-node-tuning-operator/pkg/operator
github.com/openshift/library-go/pkg/operator/v1helpers
github.com/ghodss/yaml
```
Please review and merge …

chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

---

assets/bin/run
assets/tuned/manifests/ds-tuned.yaml

This change exposes `TuneD` socket interface to the host OS.  This will, for example, allow to query and/or change a `TuneD` profile by using `TuneD` socket API.  For example, issuing the following (by the root user) from the host will return the active `TuneD` profile.
```
printf '{"jsonrpc": "2.0", "method": "active_profile", "id": 1}' | nc -U /run/tuned/tuned.sock
{"jsonrpc": "2.0", "id": 1, "result": "openshift-node"}
```

Expose TuneD socket to host.

---

test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go

Just enable the tests to check if, after the ci-lane split they work, as the lastest errors were due to timeout issues.

OCPBUGS-12836: [pao] [e2e] flaky test test_id:28440 Updating of nodeSelector

---

assets/bin/run
examples/ingress.yaml
test/e2e/basic/rollback.go

Settings rollbacks on `TuneD` exit in the OCP environment are generally a bad idea.  They can cause issues ranging from latency spikes to a complete loss of service (see OCPBUGS-13065).  Do not perform rollbacks apart from when switching Profiles.
Other changes:
- Changed `rollback.go` e2e tests to reflect the new `rollback=not_on_exit` behaviour.
- A minor change in examples/ingress.yaml to simplify necessary adjustments in  `rollback.go`.
Resolves: OCPBUGS-13065

OCPBUGS-13065: Do not rollback settings on TuneD exit

---

assets/tuned/manifests/ds-tuned.yaml

Mount propagation of a volume is controlled by the `mountPropagation` field in `Container.volumeMounts`.  By default, `None/rprivate` mount propagation -- see `mount(8)`, is used when sharing volumes mounted by a container.  `None/rprivate` mount propagation seems to be causing issues in certain cases -- see [OCPBUGS-14946](https://issues.redhat.com/browse/OCPBUGS-14946)  Switch to `HostToContainer/rslave` volume mount propagation, which also aligns better with what we would like to see in the TuneD pods.
Resolves: OCPBUGS-14946

OCPBUGS-14946: Switch to rslave/HostToContainer volume mount propagation

---

test/e2e/performanceprofile/functests/1_performance/performance.go

Because of a logic oversight, the expected cpu set was overwritten with the value expected for physical devices after the first loop iteration. This broke the test when running on clusters with more than a single worker node.

e2e: RPS: fix expected cpu set

---

pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go

The original implementation of workload partitioning tried to leverage default behavior for CRIO to allow full use of CPU Sets when no Performance Profile is supplied by the user while still being a CPU partitioned cluster. This works fine for CPU affinity however because we don't supply a config and allow the default behavior to kick in, CRIO does not alter the CPU share and gives all pods 2 CPU Share value. 
We need to supply a config for CRIO with an empty string for CPU Set to support both CPU share and CPU affinity behavior when NO performance profile is supplied, so that the `resource.requests` which get altered to CPU Share, are correctly being applied in a default state.
/assign @haircommander

OCPVE-382: fix: add default state for crio config

---

test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

When the tests fail, we want to have a clear full log of the output of the executed latency tool. The default format.MaxLength is 4000 but it isn't always sufficient to display the full string presentation especially when there is a failure.
Disable this limitation by setting the format.MaxLength to 0, to help with better troubleshooting of the failure.
For more info: https://onsi.github.io/gomega/#adjusting-output

e2e: perf-prof: disable truncating gomega output

---

test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

lately some of the latency tests were failing and it turned out that the failure is due to that the maximum latency found was greater than anticipated. The tests in this suite do not care about the measured latency because we do not care to tune the systems in the first place. Its only goal is to run the tests of the latency tools with different values of environment variables and validate that the tool actually runs with these parameters.
Increase the maximum latency threshold so that the test doesn't fail in case of a high latency result.

e2e: latency testing: increase the expected threshold

---

test/e2e/performanceprofile/functests/0_config/config.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/3_performance_status/status.go
test/e2e/performanceprofile/functests/4_latency/latency.go
test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go
test/e2e/performanceprofile/functests/utils/tuned/tuned.go

Bunch of small fixes, dead-code removal and error handling to the existing tests.
Should not affect the functionally and be completely harmless.

e2e: overhaul Performance-Addon-Operator tests

---

assets/tuned/manifests/ds-tuned.yaml

Mount propagation of a volume is controlled by the mountPropagation field in Container.volumeMounts.  By default, None/rprivate mount propagation -- see mount(8), is used when sharing volumes mounted by a container.  None/rprivate mount propagation seems to be causing issues in certain cases -- see OCPBUGS-14946.  Switch to HostToContainer/rslave volume mount propagation, which also aligns better with what we would like to see in the TuneD pods.
Resolves: OCPBUGS-15738

OCPBUGS-15738: Switch to rslave/HostToContainer volume mount propagation

---

assets/bin/run
examples/ingress.yaml
test/e2e/basic/rollback.go

Settings rollbacks on TuneD exit in the OCP environment are generally a bad idea.  They can cause issues ranging from latency spikes to a complete loss of service (see OCPBUGS-13065).  Do not perform rollbacks apart from when switching Profiles.
Other changes:
- Changed "rollback.go" e2e tests to reflect the new "rollback=not_on_exit" behaviour.
Resolves: OCPBUGS-15736

OCPBUGS-15736: Do not rollback settings on TuneD exit

---

test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

lately some of the latency tests were failing and it turned out that the failure is due to that the maximum latency found was greater than anticipated. The tests in this suite do not care about the measured latency because we do not care to tune the systems in the first place. Its only goal is to run the tests of the latency tools with different values of environment variables and validate that the tool actually runs with these parameters.
Increase the maximum latency threshold so that the test doesn't fail in case of a high latency result.

OCPBUGS-15800:e2e: latency testing: increase the expected threshold and fix gomega truncating output

---

Dockerfile
Dockerfile.rhel8
Dockerfile.rhel9
Makefile
cmd/gather-sysinfo/.gitignore
cmd/gather-sysinfo/gather-sysinfo.go
cmd/gather-sysinfo/gather-sysinfo_test.go
go.mod
go.sum
vendor/github.com/openshift-kni/debug-tools/LICENSE
vendor/github.com/openshift-kni/debug-tools/pkg/fswrap/fswrap.go
vendor/github.com/openshift-kni/debug-tools/pkg/irqs/info.go
vendor/github.com/openshift-kni/debug-tools/pkg/irqs/reporter.go
vendor/github.com/openshift-kni/debug-tools/pkg/irqs/soft/info.go
vendor/github.com/openshift-kni/debug-tools/pkg/k8s_imported/cpuset.go
vendor/github.com/openshift-kni/debug-tools/pkg/k8s_imported/podresources_client.go
vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/cpuaff.go
vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/irqaff.go
vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/irqwatch.go
vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/podinfo.go
vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/podres.go
vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/types.go
vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/root.go
vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/wait.go
vendor/github.com/openshift-kni/debug-tools/pkg/machineinformer/fakefsinfo.go
vendor/github.com/openshift-kni/debug-tools/pkg/machineinformer/informer.go
vendor/github.com/openshift-kni/debug-tools/pkg/machineinformer/relocatablesysfs.go
vendor/github.com/openshift-kni/debug-tools/pkg/procs/info.go
vendor/modules.txt

The gather-sysinfo binary is used by must-gather to collect
structured hardware information data about an OCP node.
This data is then also used by the Performance Profile Creator
also present in this repository.
Must-gather also needs the lspci binary from the pciutils package.

 Build gather-sysinfo

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

sched_min_granularity_ns was dropped from Red Hat-maintained profiles. we should align with the other profiles and drop the value from NTO as well.
In addition, we drop the test that checks for the value and update the rendered profiles.

OCPBUGS-16401:tuned: remove sched_min_granularity_ns settings

---

pkg/performanceprofile/controller/status.go

Taking the address of the range loop variable is bad, because go reuses the loop variable address.
more on that here: https://www.evanjones.ca/go-gotcha-loop-variables.html

pao: status: do not take address of loop var

---

test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/functests/utils/tuned/tuned.go

We need to wait for tuned to apply the recent changes, before we check the irqbalance settings.
We poll the tuned profile and check the applied status. we failed the test if the status not consolidate to applied within the timeout value.

OCPBUGS-15044: e2e:irqbalance: wait for tuned profile to be ready

---

pkg/performanceprofile/cmd/render/render.go

When looking for a MachineConfigPool match for each PerformanceProfile we can found no match at all.
We should check for this case before using the MCP.
This do not detect the root cause of the problem, an invalid PerformanceProfile. To tackle that problem we would need something more deep like a validator.

Improve render error handling

---

Makefile
hack/run-update-testing.sh

`e2e-gcp-pao` consistently  falling on timeouts because the lane split to 4.12 (updating-profile lane) wasn't backport.
Split the lane to improve situation.

OCPBUGS-13429: Split pao lanes

---

test/e2e/basic/rollback.go

This changes fixes a race between a sysctl write and TuneD applying a profile.

Fix a race in e2e test rollback.go code

---

test/e2e/performanceprofile/functests/6_mustgather_testing/test_suite_mustgather_test.go

The PAO must gather is being merged with the NTO and hence in the updated versions the image parameter is not required to be given with the oc adm command.

e2e: remove image parameter from must gather

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/1_performance/hugepages.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
test/e2e/performanceprofile/functests/4_latency/latency.go
test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
test/e2e/performanceprofile/functests/9_reboot/devices.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

In some of the tests we're implicitly relaying on the fact that the pod data returned from the `pods.WaitFor*` functions is the most updated one.
This is not the case in some of the functions on which we are storing the data on different pointer to pod object and never return it.
Instead of using different pod object, we should use the same one passed into the function.

e2e:wait: return updated pod object explicitly

---

test/e2e/performanceprofile/functests/utils/mcps/mcps.go
test/e2e/performanceprofile/functests/utils/profiles/profiles.go

There are times when the deletion is not completed and the next test begins, trying to create the object which not completly deleted.
That cause the test to failed with `Object already exist error`.
In order to fix that, we should wait for the objects to be removed completely from the cluster.

e2e: wait for objects deletion

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

We  retrieve the worker node where the pod
located, before executing command against it.

OCPBUGS-7980:e2e:ht-aware: exec on the correct worker node

---

cmd/cluster-node-tuning-operator/main.go

Step down voluntarily on manager exit and speed up voluntary leader transitions as the new leader doesn't have to wait LeaseDuration time first.
Resolves: OCPBUGS-16908

OCPBUGS-16908: Release leader election on manager exit

---

pkg/performanceprofile/cmd/render/render.go

There was a possibility of a segfault when the input directory for the render mode had some MCPs, but none of them matched the expected node selector.

OCPBUGS-17219: Render mode should not segfault w/ no matching MCP

---

Makefile
hack/build-test-bin.sh
hack/list-test-bin.sh

In order to enable developers to spot issues when
developing e2e tests and/or updating deps before to hit CI and save time and CI runs, add helpers and targets to compile testsuites without running them. This alone helps us spotting a fair share of code issues.

Makefile: hack: add helpers to compile testsuites

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

Signed-off-by: Brent Rowsell <browsell@redhat.com>
A RHEL 9.x change added a timer to make sure TSC_adjust is always which introduces latency spikes. Update tsc karg to tsc=reliable. This aligns with the realtime tuned profile.

OCPBUGS-16348: OSLAT latency spikes due to tsc karg setting

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

Signed-off-by: Brent Rowsell <browsell@redhat.com>
Add the rtentsk plugin to the openshift-node-performance tuned profile.

OCPBUGS-17943: Add rtentsk plugin to pp tuned profile

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

This is a manual cherry-pick of https://github.com/openshift/cluster-node-tuning-operator/pull/756
A RHEL 9.x change added a timer to make sure TSC_adjust is always which introduces latency spikes. Update tsc karg to tsc=reliable. This aligns with the realtime tuned profile.

[release-4.13] OCPBUGS-17688: update tsc karg to tsc=reliable

---

pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml

OVN Interconnect feature was merged to CNO [1] and the manifests mounting /etc/openvswitch to the ovnkube-node containers changed.
This caused the trigger file to become invisible and so the dynamic OVS pinning was disabled.
This change moves the trigger file to the new directory used by OVN+CNO to re-enable the feature.
[1] https://github.com/openshift/cluster-network-operator/pull/1874

OCPBUGS-18392: Change the OVN trigger file name to adapt to OVN IC

---

test/e2e/performanceprofile/functests/1_performance/performance.go

This PR not intended to fix the flakiness we have but should help
with finding the the culprit virtual device which causes it.

OCPBUGS-18662: e2e:rps: improve logging

---

Makefile
test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

The test started to fail frequently in CI. The reason for the failure is that there were measured latency samples that exceeds the maximal default threshold of hwlatdetec. Since we have enabled new CI machines, it seems that they are not well tuned hence causing in high latency.
To fix the test, just add a high threshold. Note that in these tests we do not care about latency measurments but about enabling the latency tools tests with differnt variables.

e2e: add expected max latancy to hwlatdetec test & rename constant

---

cmd/cluster-node-tuning-operator/main.go

Step down voluntarily on manager exit and speed up voluntary leader transitions as the new leader doesn't have to wait LeaseDuration time first.
Resolves: OCPBUGS-18000
This is a backport of: https://github.com/openshift/cluster-node-tuning-operator/pull/745

OCPBUGS-18000: Release leader election on manager exit

---

Dockerfile
go.mod

Some unit tests fail with go1.19 as some modules require 1.20. It seems that ci-lanes are using go1.20 already so just updating required version and Dockerfile base image to align all

Update required go version

---

cmd/cluster-node-tuning-operator/main.go

This reverts commit 8f21a273b3ff4ff21a15b9bdcc59ffa788be559b.

OCPBUGS-19351: Revert "Release leader election on manager exit

---

manifests/20-profile.crd.yaml
pkg/apis/tuned/v1/tuned_types.go

https://github.com/openshift/cluster-node-tuning-operator/pull/766 introduced a fix for OCPBUGS-17941 by tightening the rules for modifying Tuned Profiles.  Unfortunately, the fix introduced an upgrade issue (race), where the old operator still relies on removed Profile status.bootcmdline.
Reintroduce the field for the old operator, so that it does not cause additional reboots by seeing the bootcmdline as empty.  The status.bootcmdline field is not used in any way by the new operator, it is marked as obsolete and will be removed in the future.
Resolves: OCPBUGS-19351

OCPBUGS-19351: Keep Profile status.bootcmdline around

---

pkg/util/objectinfo.go

This change fixes a crash during error reporting when a returned object is nil.
Resolves: OCPBUGS-19459

OCPBUGS-19459: check for object being nil

---

go.mod
go.sum
test/e2e/performanceprofile/functests/1_performance/test_suite_performance_test.go
test/e2e/performanceprofile/functests/4_latency/test_suite_latency_test.go
test/e2e/performanceprofile/functests/utils/consts.go
test/e2e/performanceprofile/functests/utils/k8sreporter/reporter.go
vendor/github.com/golang/glog/LICENSE
vendor/github.com/golang/glog/README.md
vendor/github.com/golang/glog/glog.go
vendor/github.com/golang/glog/glog_file.go
vendor/github.com/openshift-kni/k8sreporter/LICENSE
vendor/github.com/openshift-kni/k8sreporter/README.md
vendor/github.com/openshift-kni/k8sreporter/client.go
vendor/github.com/openshift-kni/k8sreporter/reporter.go
vendor/modules.txt

This commit adds a k8s reporter to the e2e tests.
Here we are utilizing the openshift-kni k8sreporter, and passing to its constructor the CRDs and namespace of the test.
The reporter will function only if the `-report` flag is passed.
This is to be aligned with the current reporter we use in the cnf-tests.
Here is an example of the k8s reporter tree output when all the tests of the 1_performance suite failed:
```
.
└── nto_failure_report.log
├── [performance]_Checking_IRQBalance_settings_Verify_GloballyDisableIrqLoadBalancing_Spec_field_[test_id:36150]_Verify_that_IRQ_load_balancing_is_enabled-disabled_correctly
│   ├── crs.log
│   └── nodes.log
├── [performance]Hugepages_[rfe_id:27369]when_NUMA_node_specified_[test_id:27752][crit:high][vendor:cnf-qe@redhat.com][level:acceptance]_should_be …
```

Add k8s reporter to e2e tests

---

assets/tuned/manifests/ds-tuned.yaml
pkg/tuned/controller.go

IBM Managed OpenShift seems to use `/etc/kubernetes/kubelet-kubeconfig` instead of the traditional `/var/lib/kubelet/kubeconfig` kubelet config path.
Other changes:
- fix a crash when kubelet's kubeconfig is not found and in-cluster config is used instead
Resolves: OCPBUGS-19795

OCPBUGS-19795: Add kubeconfig path for IBM Managed OpenShift 

---

pkg/performanceprofile/utils/schedstat/schedstat.go
pkg/performanceprofile/utils/schedstat/schedstat_test.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

Add simple parser for `/proc/schedstat`, to have a good foundation for load balancing disabling tests.
Use it into the scheduling domains tests to make the test more precise and (hopefully) the failure conditions clearer.
Finally, builds on the aforementioned to tight up the tests.

OCPBUGS-18783: e2e: perfprof: enhance the scheduling domain tests

---

assets/tuned/manifests/ds-tuned.yaml
pkg/tuned/controller.go

IBM Managed OpenShift seems to use "/etc/kubernetes/kubelet-kubeconfig" instead of the traditional "/var/lib/kubelet/kubeconfig" kubelet config path.
Other changes:
- fix a crash when kubelet's kubeconfig is not found and in-cluster config is used instead
- fix an omitted mountPropagation for /etc/sysconfig
Resolves: [OCPBUGS-19840](https://issues.redhat.com/browse/OCPBUGS-19840)

OCPBUGS-19840: Add kubeconfig path for IBM Managed OpenShift

---

test/e2e/performanceprofile/functests/0_config/test_suite_performance_config_test.go

This commit adds the k8s reporter to the config suite that is also used by the cnf-tests.

Add the k8s reporter to the configuration suite

---

cmd/cluster-node-tuning-operator/main.go
pkg/operator/controller.go
pkg/tuned/controller.go
version/version.go

Add non-default UserAgent when communicating with the API server to ease debugging.  See OCPBUGS-19351 for more detail.

OCPBUGS-19785: Set non-default UserAgent for easier debugging

---

cmd/cluster-node-tuning-operator/main.go
pkg/performanceprofile/controller/utils.go
test/e2e/basic/csvs.go
test/e2e/testing_manifests/csv-dummy.yaml

Adding pagination to CSVs list operation while deleting PAO OLM operator elements.
From versions >= 4.11 PAO has been integrated into NTO
For that reason PAO OLM operator elements (ClusterServiceVersion, Subscriptions .. ) should be deleted
As part of this operation CSVs are listed. This operation can take too long in some clusters due to the number of elements to be listed, and so the operation will hit a timeout and the pod will crash. This could end on a `Crashbackloop`situation.
Adding pagination to the list operation should avoid this situation.

OCPBUGS-14241: nto: pao avoid timeout when there are too many CSV

---

cmd/cluster-node-tuning-operator/main.go
pkg/performanceprofile/controller/utils.go
test/e2e/basic/csvs.go
test/e2e/testing_manifests/csv-dummy.yaml

Adding pagination to CSVs list operation while deleting PAO OLM operator elements.
From versions >= 4.11 PAO has been integrated into NTO
For that reason PAO OLM operator elements (ClusterServiceVersion, Subscriptions .. ) should be deleted
As part of this operation CSVs are listed. This operation can take too long in some clusters due to the number of elements to be listed, and so the operation will hit a timeout and the pod will crash. This could end on a `Crashbackloop`situation.
Adding pagination to the list operation should avoid this situation.
Manual cherry-pick of: #731

[release-4.14] OCPBUGS-20032: nto: pao avoid timeout when there are too many CSV

---

cmd/cluster-node-tuning-operator/main.go
pkg/util/errors.go
pkg/util/errors_test.go

OLM will be made optional in 4.15, when OLM resources are removed, the error check fails to be caught with `IsNotFound`  resulting in a false positive error. Updating to also check for `NoResourceMatchError`

OCPVE-717: fix: add if check for no resource match error

---

Makefile

Makefile target `pkg/generated` output some data on `tmp` folder. 
Lets delete it also on clean.

Makefile: remote tmp folder on clean target

---

hack/render-sync.sh

When https://github.com/openshift/cluster-node-tuning-operator/pull/778 got merged, the directory layout has changed and broke the `render-sync`  make target. This patch should fix it.

render: change directory path

---

assets/performanceprofile/configs/99-netdev-physical-rps.rules
assets/performanceprofile/scripts/set-rps-mask.sh
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
test/e2e/performanceprofile/testdata/render-expected-output/manual_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_runtimeclass.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml

Instead of trigger udev event per physical device creation,
triggers it per queue creation so in case of queue resize
(i.e. more queues are added) it applies the correct rps mask on the
new created queues as well.

OCPBUGS-18662:rps: trigger udev even per queue

---

pkg/metrics/server.go

NTO metrics server was using the default tls.Config.  However, the default tls.Config supports obsolete/insecure protocols, such as TLS 1.0 and 1.1 and weak ciphers (3DES).  Drop support for TLS 1.0, 1.1 and 3DES. Also, drop CBC encryption method and RSA key exchanges.
Resolves: OCPBUGS-20567

OCPBUGS-20567: Remove obsolete protocols and weak ciphers

---

cmd/cluster-node-tuning-operator/main.go
pkg/metrics/server.go

Remove HTTP/2 support for webhook and metrics servers -- mitigation for CVE-2023-44487.
Resolves: OCPBUGS-21932

OCPBUGS-21932: Disable HTTP/2 for webhook and metrics servers

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhel9

`x86_energy_perf_policy` from RHEL8 causes a kernel taint on RHEL9 kernels.  This is a problem for CNF certifications.  Switch the NTO base to RHEL9 so that we use an up-to-date `x86_energy_perf_policy` aligned with RHEL9 kernels.
Resolves: OCPBUGS-13330

OCPBUGS-13330: Use RHEL9 as a base

---

cmd/cluster-node-tuning-operator/main.go

The latest operator SDK version allow specifying
multiple namespaces directly as part of the cache options.
Functionality would remain the same.

CNF-10294: main: remove deprecated multi ns function

---

pkg/operator/controller.go
pkg/operator/hypershift.go
pkg/operator/mc.go
pkg/performanceprofile/profilecreator/helper.go
pkg/tuned/controller.go
pkg/tuned/tuned_parser.go

This change improves upon #793 by removing most linter overrides and replacing them with a proper fix to keep the linter happy.  Only overrides for one false positive (static analysis check), and two nolint:errcheck overrides due to failing unit tests (future work) in performanceprofile_controller.go are kept.

NO-JIRA: Remove most //nolint:* overrides

---

cmd/cluster-node-tuning-operator/main.go
go.mod
go.sum
pkg/metrics/server.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go

Remove HTTP/2 support for webhook and metrics servers -- mitigation for CVE-2023-44487.  controller-runtime was upgraded to add support for TLSOpts.
Resolves: OCPBUGS-20669
This is a backport of https://github.com/openshift/cluster-node-tuning-operator/pull/841

OCPBUGS-20669: Disable HTTP/2 for webhook and metrics servers

---

pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
pkg/performanceprofile/controller/performanceprofile/components/utils.go
pkg/performanceprofile/controller/performanceprofile/components/utils_test.go
pkg/performanceprofile/profilecreator/profilecreator.go
pkg/performanceprofile/profilecreator/profilecreator_test.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/functests/1_performance/netqueues.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/4_latency/latency.go
test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go
vendor/k8s.io/utils/cpuset/OWNERS
vendor/k8s.io/utils/cpuset/cpuset.go
vendor/modules.txt

Change k8s.io/kubernetes/pkg/kubelet/cm/cpuset to k8s.io/utils/cpuset

CNF-10344: NTO: Avoid depending on kubernetes cpuset 

---

cmd/cluster-node-tuning-operator/main.go
go.mod
go.sum
pkg/metrics/server.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go

Remove HTTP/2 support for webhook and metrics servers -- mitigation for CVE-2023-44487.  controller-runtime was upgraded to add support for TLSOpts.
Resolves: OCPBUGS-20661
This is a backport of https://github.com/openshift/cluster-node-tuning-operator/pull/846

OCPBUGS-20661: Disable HTTP/2 for webhook and metrics servers

---

docs/performanceprofile/performance_controller.md
hack/run-test.sh
test/e2e/performanceprofile/functests/4_latency/latency.go
test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

After the cnf-tests image split, the image now has only latency tools tests so there is no need for a flag to enable those tests.

CNF-9264: e2e:latency: omit LatencyTestRun env variable

---

pkg/manifests/manifests.go

In the past, duplicate profiles were being report as WARNINGs only. Increase seriousness of this fact, so that it helps the users to fix their configuration issues.

NO-JIRA: Report duplicate profiles as ERRORs

---

cmd/cluster-node-tuning-operator/main.go
pkg/operator/controller.go
pkg/operator/mc.go
pkg/operator/profilecalculator.go
pkg/performanceprofile/cmd/render/render.go
pkg/tuned/cmd/render/cmd.go
pkg/tuned/cmd/render/render.go
pkg/tuned/controller.go
pkg/tuned/run.go
pkg/util/manifests.go

We need to speed up bootstrap.
To do so we need to apply kernel boot arguments without restarting node.
Add a new render command to prepare all tuned profiles, run `tuneD`, read `bootcmdline`  and render a MachineConfig to apply those kernel arguments.
Warning: running `tuneD` would modify some system files so this command should be executed in a properly isolated environment.
see: https://github.com/openshift/installer/pull/7692

CNF-10238: NTO render command for SNO boot arguments

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml

tuned complains that the sysctl value was already set via a sysctl.d file:
```
2023-12-05T22:23:07.343622915Z 2023-12-05 22:23:07,343 INFO     tuned.plugins.plugin_sysctl: Overriding sysctl parameter 'net.core.rps_default_mask' from '${not_isolated_cpumask}' to '30000003'
```
The comparison in tuned is broken as ${not_isolated_cpumask} should actually expand to the same value. But this INFO causes NTO to mark the profile as Degraded and we do not want that.
Commenting out the sysctl in the tuned profile is not going to break anything, because the sysctl.d version of it is applied anyway.

OCPBUGS-24638: Do not set default RPS sysctl twice

---

go.mod
go.sum

Changed go.mod and ran "go mod tidy".
Also see: https://github.com/openshift/cluster-node-tuning-operator/pull/873

OCPBUGS-24929: Use go 1.21

---

test/e2e/basic/operator_test.go

You must set a logger for controller-runtime, otherwise it complains.

NO-JIRA: e2e-test: Call SetLogger to avoid controller-runtime error.

---

Makefile

This make target should be called in the new TechPreviewNoUpgrade job and run some sanity tests: https://github.com/openshift/release/pull/46767 
After the job get settle, we should add all the other e2e tests that were planned.

CNF-10676: makefile: add target to trigger mixedcpus e2e test

---

pkg/operator/controller.go
pkg/operator/mc.go
pkg/operator/profilecalculator.go

OpenShift Nodes can be a part of only one custom MachineConfigPool. However, MCP configuration allows this not to be the case.  This is caught by the machine-config-controller and reported as an error (<node> belongs to <N> custom roles, cannot proceed with this Node).
In order to target an MCP with a configuration, NTO uses machineConfigLabels.  However, one or more MCPs can select a particular single MC.  This is due to the MCP's machineConfigSelector.  This is another challenge scenario.
In the above two scenarios, it was possible for NTO to generate a randomly-named MC based on the membership of one of the matching MCPs. Then, a pruning function would mistakenly remove the other MCs, seemingly unused.  This could result in a flip between the rendered MCs and cause a Node reboot.
This …

OCPBUGS-24792: Make MC names deterministic

---

pkg/tuned/cmd/render/cmd.go
pkg/tuned/cmd/render/render.go

Some fine tuning and leftovers from #844 
Mostly narrowing the Performance and Tuned Profiles applicable and adding more checks to ensure the cohesion all the objects computed.

CNF-10587: NTO: Fine tuning render bootcmd mc command

---

pkg/operator/controller.go
pkg/operator/mc.go
pkg/operator/profilecalculator.go

OpenShift Nodes can be a part of only one custom MachineConfigPool. However, MCP configuration allows this not to be the case.  This is caught by the machine-config-controller and reported as an error (<node> belongs to <N> custom roles, cannot proceed with this Node).
In order to target an MCP with a configuration, NTO uses machineConfigLabels.  However, one or more MCPs can select a particular single MC.  This is due to the MCP's machineConfigSelector.  This is another challenge scenario.
In the above two scenarios, it was possible for NTO to generate a randomly-named MC based on the membership of one of the matching MCPs. Then, a pruning function would mistakenly remove the other MCs, seemingly unused.  This could result in a flip between the rendered MCs and cause a Node reboot.
This …

OCPBUGS-25595: Make MC names deterministic

---

.snyk

Add a '.snyk' file to exclude these paths under the vendor directory:
ginkgo/v2/internal/suite.go
controller-runtime/pkg/log/log.go
jaypipes/ghw/pkg/block/block_linux.go
These paths trigger a warning related to the generation of error messages
containing sensitive information.
Currently, there is no available fix for these issues.

OCPBUGS-26162: Add .snyk file for static code analysis

---

pkg/operator/controller.go
pkg/operator/hypershift.go

https://github.com/openshift/cluster-node-tuning-operator/pull/456 introduced support for MachineConfig-like functionality for HyperShift via NTO.  This PR unnecessarily creates a runtime.Scheme on every invocation of getMachineConfigFromConfigMap() and serializeMachineConfig() function as pointed out in https://github.com/openshift/cluster-node-tuning-operator/pull/837#discussion_r1382825424.  Make the scheme an attribute of the controller and initialize it only once at controller instantiation.
/cc

NO-JIRA: HyperShift code linter PR837 followup

---

test/e2e/performanceprofile/functests/0_config/test_suite_performance_config_test.go
test/e2e/performanceprofile/functests/1_performance/test_suite_performance_test.go
test/e2e/performanceprofile/functests/2_performance_update/test_suite_performance_update_test.go
test/e2e/performanceprofile/functests/3_performance_status/test_suite_performance_status_test.go
test/e2e/performanceprofile/functests/4_latency/test_suite_latency_test.go
test/e2e/performanceprofile/functests/6_mustgather_testing/test_suite_mustgather_test.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/test_suite_performance_kubelet_node_test.go
test/e2e/performanceprofile/functests/8_performance_workloadhints/test_suite_performance_workloadhints_test.go
test/e2e/performanceprofile/functests/9_reboot/test_suite_reboot_test.go

avoid nasty stacktrace when trying to log, because we didn't manage to set the logger explicitly.
Thus, avoid things like
```
[rfe_id:27368][performance] Verify API Conversions  when the GloballyDisableIrqLoadBalancing field set to false should preserve the value during the v1 <-> v2 conversion
/go/src/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/performance.go:727
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 7762 [running]:
runtime/debug.Stack()
/usr/lib/golang/src/runtime/debug/stack.go:24 +0x5e
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
/go/src/github.com/openshift/cluster-node-tuning-operator/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:59 +0xcd …
```

NO-JIRA: e2e: log: set ctrl-runtime logger

---

pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go

In Hypershift we need to validate PerformanceProfile from NodePool controller.
As a one-to-one relationship between NodePool and Performance Profile is already enforced there is no need ( and no easy way ) to check for PerformanceProfiles with duplicated selectors, so we just need to check the fields.

CNF-6517: Export ValidateBasicFields for Hypershift

---

test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go

This tests is failing because of a known issue that is already being handled.
In the meantime skip it to avoid PRs to pile.

NO-JIRA: Skip PerformanceProfile update test

---

test/e2e/performanceprofile/functests/utils/profiles/profiles.go

The function contains a subtle bug on which the update is done only for fileds under the `Spec`
This means that changes to annotations, labels and any other field outside the `Spec` won't take affect.

NO-JIRA:e2e: `UpdateWithRetry` only update spec

---

pkg/tuned/cmd/render/render.go

This command should render a MC from the available sources. PerformanceProfile is a source, but it is not mandatory.
So, as there are scenarios where this command should work with no additional PP let's the command proceed even if there is no PP

CNF-10170: Render MC without additional PP

---

test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go

Reverts openshift/cluster-node-tuning-operator#917
a crun version that contains https://github.com/containers/crun/pull/1384  fix is in, let's see if the test is passing now

Revert "NO-JIRA: skip crun configuration test"

---

manifests/45-webhook-configuration.yaml

Change performance profile validating webhook failure policy to "Ignore". This is needed as a temporary workaround for bootstrap-in-place, where webhooks can not be served. This PR should be reverted after a permanent solution for BiP is implemented
/cc @MarSik @yanirq

CNF-11091: Change webhook failure policy to ignore

---

test/e2e/performanceprofile/functests/0_config/config.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/README.md

We've been observing lately that some tests that involve disabling load balancing are failing (like 32646) because the expected result does not have specific anticipated CPUs. After investigation, it turns out that one factor is the profile configuration of the CPU distribution.
PAO functional tests configure fixed CPU values under the PP. This is considered misconfiguration, especially when the system has more than 4 CPUs, and there is no guarantee that the functionality of the performance profile controller will work adequately with not all cpus reflected in the CPU section in the PP.
To resolve this complication, we are introducing new environment variables RESERVED_CPU_SET, ISOLATED_CPU_SET, OFFLINED_CPU_SET, should be set the profile would use them instead of the defaults.

NO-JIRA: e2e: set performance profile cpus using env vars

---

test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
test/e2e/performanceprofile/functests/1_performance/hugepages.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
test/e2e/performanceprofile/functests/utils/cgroup/cgroup.go
test/e2e/performanceprofile/functests/utils/cgroup/controller/controller.go
test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
test/e2e/performanceprofile/functests/utils/cgroup/v2/v2.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

This package provides a Getter which is cgroup version agnostic.
It provides a unified api for testing the mixedcpus feature for both v1 and v2.
The package can be expand in the future for testing additional features that requires cgroups inspection. (for example runc vs crun)
How to use:
```
getter := BuildGetter(context.TODO(), controllerRuntimeClient, k8sClient)
cpusetCfg := &controller.CpuSet{}
err := getter.Container(context.TODO(), pod, containerName, cpusetCfg)
// error handling
fmt.Println(cpusetCfg.Cpus)
```

CNF-9173: e2e: cgroups: introduce cgroup package

---

test/e2e/performanceprofile/functests/utils/label/label.go

The label package contains a list of labels that can be used in the functests to indicate and point certain behavior or characteristics of the various tests.
Those can be filtered/focused by ginkgo before the test runs.
Example:
`ginkgo --label-filter="!slow"` means avoid any specs labelled `slow`

NO-JIRA: e2e: classifying tests using labels

---

test/e2e/testing_manifests/sno/kernel_parameter_add_rm-child.yaml
test/e2e/testing_manifests/sno/kernel_parameter_add_rm-parent.yaml
test/e2e/testing_manifests/sno/stalld-disable.yaml
test/e2e/testing_manifests/sno/stalld.yaml

[PR459](https://github.com/openshift/cluster-node-tuning-operator/pull/459) made adjustments to fix NTO e2e tests on SNO.  Unfortunately, the PR did not include 4 SNO manifests to test with.  This change fixes this issue.

NO-JIRA: Fix e2e tests on SNO

---

test/e2e/performanceprofile/functests/11_mixedcpus/11_mixedcpus_suite_test.go
test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go

This is a first PR (more to come) that tests the mixed-cpus e2e.
It contains the following tests:
1. Basic test to verify that pod which asks for shared cpus, has the shared cpus under
its cgroup cpuset.
2. Check that `cpu-quota.crio.io: disable` annotation works along with mixedcpus. 
3. Check that `OPENSHIFT_ISOLATED_CPUS` and `OPENSHIFT_SHARED_CPUS` env variables are under the container and configured properly.
4. Verify that updates to shared CPUs under the profile are reflect under the containers correctly.

CNF-9173: e2e: mixedcpus test

---

pkg/performanceprofile/cmd/render/render.go

don't add weak ref to the perfprof and don't write back an updated version in output.
The rationale is that we don't want "duplicate" profiles, so avoiding to write back the mutated profile is the only option.

NO-JIRA: render: perfprofile: don't annotate perfprof

---

test/e2e/performanceprofile/functests/utils/label/label.go

backport of:
* https://github.com/openshift/cluster-node-tuning-operator/pull/947
* https://github.com/openshift/cluster-node-tuning-operator/pull/936

[release-4.15][manual] OCPBUGS-29396: Labels for e2e testing 

---

test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go

Add a test to check if shared CPUs survive Kubelet restart.

CNF-9173: e2e: mixedcpus: kubelet restart test

---

pkg/util/manifests.go

Newly added MCPs lack MachineConfigSelector field.

OCPBUGS-22095: Render: Add MCSelector to missing default MCPs

---

hack/render-sync.sh

We need this change because we also want to use also non default values for the owner-ref like the value none.
The work on [this PR depends](https://github.com/openshift/cluster-node-tuning-operator/pull/954) on these modifications to be merged.

NO-JIRA: Add support to inject owner-ref argument to render command

---

assets/performanceprofile/tuned/openshift-node-performance
assets/performanceprofile/tuned/openshift-node-performance-rt
hack/render-sync.sh
pkg/performanceprofile/controller/performanceprofile/components/consts.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

Kernel parameters that are not supported on RT kernel systems are being applied, causing errors to be logged to the tuned daemon, resulting in a degraded profile state.
Therefore, I added the openshift-node-performance-rt profile that would be included if an RT kernel is detected, thereby dropping the unsupported kernel parameters before they are applied.

OCPBUGS-23167: Add performance real time tuned template

---

assets/tuned/assets.go
pkg/tuned/cmd/render/render.go
pkg/tuned/controller.go

When there is no enough information to choose a recommended TuneD profile from the input folder manifests we load the `default-cr-tuned` manifests.
modifies: #844 
see: https://github.com/openshift/installer/pull/8007

CNF-10170: Avoid command to fail if there is no PP on input folders

---

pkg/performanceprofile/cmd/render/render.go
test/e2e/performanceprofile/cluster-setup/container-runtime-crun/enable-crun-master.yaml
test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/01_01-master-cpu-partitioning_workload_pinning_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/01_01-worker-cpu-partitioning_workload_pinning_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_node.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_runtimeclass.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_node.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_runtimeclass.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml

Fix bootstrap error  of "more than one ContainerRuntimeConfig found that matches MCP labels" when an additional ContainerRuntimeConfig is provided by user.
/cc @yanirq @MarSik @Tal-or @ffromani

OCPBUGS-29641: fix rendering extra ctrcfgs

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

Set tuned scheduler plugin not to change any IRQ affinities. This overrides the default(true) which is set via
the parent cpu partitioning profile.
Utilized https://github.com/redhat-performance/tuned/pull/595

OCPBUGS-26400: scheduler plugin: ignore IRQs

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go

One of the tests is failing in u/s and printing out the pod events is not enough for debugging.
Add another condition to skip the test if the requested cpus is greater than what the node can provide; and log a bit more info about the pod to be created.

NO-JIRA: e2e: perf-prof: increase logging for debugging

---

hack/test-upstream-tuned.sh

Starting with PR858, we can no longer use a random `RELEASE_VERSION` to trigger daemonset/operand updates.  In the context of testing upstream TuneD this is causes an issue.  Not changing `RELEASE_VERSION` at all is a simple fix, because we are also adjusting `CLUSTER_NODE_TUNED_IMAGE` and that will cause a daemonset/operand update.

NO-JIRA: Remove RELEASE_VERSION from test-upstream-tuned.sh

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

Disable irq affinity setting by scheduler plugin ONLY when GloballyDisableIrqLoadBalancing=false (default)

OCPBUGS-30812: Ignore scheduler plugin IRQs when globally enabled

---

Makefile
hack/show-cluster-version.sh

Add initial make target for running e2e tests on hypershift environment.
On later PR an actual call for the e2e tests will be added.
`HYPERSHIFT_MANAGEMENT_CLUSTER_KUBECONFIG` and
`HYPERSHIFT_HOSTED_CLUSTER_KUBECONFIG` are defined
by the u/s ci and provided the kubeconfig file path for the management and hostet cluster respectively.

CNF-11646: makefile:hypershift: initial make target

---

hack/render-sync.sh

Add missing sync for rendering extra ctrcfgs under the render-sync target
This was missing from https://github.com/openshift/cluster-node-tuning-operator/pull/972 
(no backport needed)

NO-JIRA: Add sync for rendering extra ctrcfgs

---

pkg/tuned/controller.go
pkg/tuned/run.go
pkg/tuned/status.go

In the past, there were reports of TuneD being stuck during profile application (e.g. rhbz#2013940).  As a workaround a timeout with exponential backoff was implemented to restart TuneD if it was ever stuck not finishing profile application.  However, with some TuneD profiles and hardware configurations, it can take very long for a TuneD profile to be applied.  In environments, such as latency-sensitive deployments a repeated profile application can make things matters worse. Therefore, remove the timeout functionality.
Also, remove the reload on TuneD ERRORs.  This is an openshift-tuned bug.

OCPBUGS-30647: Remove TuneD timeout code and reload on ERRORs

---

test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

Since ginkgo default timeout was updated from 24h to 1hr we add additional tests to ensure that the tests are executed taking ginkgo timeout into account and condering the values specified for LATENCY_TEST_RUNTIME and LATENCY_TEST_DELAY by the user.

NO-JIRA: Add positive tests with ginkgo timeout

---

test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
test/e2e/performanceprofile/functests/utils/deployments/deployments.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

Added a test for mixedCpus feature along with some util functions.
This test checks that pods using shared CPUs in a deployment won't
be able to schedule after the mixedCpus feature is disabled and the node reboots.

CNF-11213: added mixedCpus e2e test

---

.snyk

Previous format was wrong, and in turn had no effect on ignoring code issues.

OCPBUGS-26162: Fixed .snyk format

---

test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/utils/infrastructure/vm.go

Updated the tuned degradation test to fail only when the tuned profile was found degraded
on BM host.
In case of tuned profile found degraded on a VM, only a warning would be reported in the logs.
The reason for that is that the fact CI is using VMs - and some
configurations like certain kernel args can't be applied and therby lead to
the tuned profile being degraded.

NO-JIRA: Update tuned profile degraded test

---

pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

The script cpuset-configure.sh is responsible to move the
systemd processes to the cpuset/systemd.slice cgroup and  is executed
in a form of a service (cpuset-configure.service).
In the current implementation, the script is executed too early - some
system processes are yet to be created.
This in turn leads to them not being moved to the custom system slice.
Moreover, in the current implementation, the script is executed before
the network-online.target. The intention was to execute the script before
kubelet and crio services are initialized (by the fact network-online.target
is a common parent) in order to make sure that no workload pods are starting
before we are making this transition.
The fix I'm proposing consist of the following changes:
1. Adding an After statement - The script …

OCPBUGS-30569: Systemd processes not being moved to cpuset/systemd.slice fix

---

assets/performanceprofile/tuned/openshift-node-performance
assets/performanceprofile/tuned/openshift-node-performance-rt
hack/render-sync.sh
pkg/performanceprofile/controller/performanceprofile/components/consts.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

This is a manual backport of PR #954 and #1005 
This PR includes both of these PR's together, because #1005 introducing a fix for the tuned profile degradation test added in #954. 
* Add performance real time tuned template
Kernel parameters that are not supported on RT kernel systems are being applied, causing errors to be logged to the tuned daemon, resulting in a degraded profile state. Therefore, I added the openshift-node-performance-rt profile that would be included if an RT kernel is detected, thereby dropping the unsupported kernel parameters before they are applied.
* Added a test that make sure the tuned profile is not degraded
This could be great to have a generic test that make sure that after performance profile is applied the tuned profile is not degraded. This would prevent …

[release-4.15] [manual] OCPBUGS-30507: Add performance real time tuned template

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

Manual Cherry pick of https://github.com/openshift/cluster-node-tuning-operator/pull/976 + https://github.com/openshift/cluster-node-tuning-operator/pull/987
Set tuned scheduler plugin not to change any IRQ affinities. This overrides the default(true) which is set via
the parent cpu partitioning profile.
Utilized https://github.com/redhat-performance/tuned/pull/595

 [release-4.15] OCPBUGS-30306: scheduler plugin: ignore IRQs

---

pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

This is a manual backport for #992
* Systemd processes not being moved to cpuset/systemd.slice fix
The script cpuset-configure.sh is responsible to move the systemd processes to the cpuset/systemd.slice cgroup and  is executed in a form of a service (cpuset-configure.service).
In the current implementation, the script is executed too early - some system processes are yet to be created.
This in turn leads to them not being moved to the custom system slice.
Moreover, in the current implementation, the script is executed before the network-online.target. The intention was to execute the script before kubelet and crio services are initialized (by the fact network-online.target is a common parent) in order to make sure that no workload pods are starting before we are making this transition. …

OCPBUGS-31692:  [release-4.15] [manual]: Systemd processes not being moved to cpuset/systemd.slice fix

---

pkg/tuned/controller.go
pkg/tuned/run.go

Changes:
* fix logging in `updateTunedProfile()` and optimize the calls to update node annotations and update Profile.Status
* clean up `tunedStop()` to return only one value
* during `TuneD` process shutdown, handle the fact the `TuneD` process might have already exitted
* the openshift-tuned operand now no longer unnecessarily exits when `TuneD` process exits; when `TuneD` process exits, wait for k8s object changes and only then restart `TuneD`
* do not use buffered channels
* the indication that `TuneD` is reloading is now a status bit potentially reportable back to the operator
* introduce Change type for the `TuneD` event processor to avoid races, where it was previously possible to change `TuneD` configuration during `TuneD` profile reload
* register the fact `TuneD` finished …

OCPBUGS-30647: NTO operand (openshift-tuned) fixes

---

pkg/operator/profilecalculator.go

This is a manual backport for #965.
Originally, any profile matching rules with the same priority would be reported as warnings.  We do not necessarily need to issue a warning unless a Node has multiple matching profiles with the same priority.
Resolves: OCPBUGS-24636

OCPBUGS-31735: [release-4.14] [manual]: Report duplicate priority only for multiple matching profiles

---

assets/performanceprofile/tuned/openshift-node-performance
assets/performanceprofile/tuned/openshift-node-performance-rt
hack/render-sync.sh
pkg/performanceprofile/controller/performanceprofile/components/consts.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

This is a manual backport for: Add performance real time tuned template (#984)
* Add performance real time tuned template
Kernel parameters that are not supported on RT kernel systems are being applied, causing errors to be logged to the tuned daemon, resulting in a degraded profile state. Therefore, I added the openshift-node-performance-rt profile that would be included if an RT kernel is detected, thereby dropping the unsupported kernel parameters before they are applied.
* Added a test that make sure the tuned profile is not degraded
This could be great to have a generic test that make sure that after performance profile is applied the tuned profile is not degraded. This would prevent future issues like OCPBUGS-23167.
The test will fail only when the tuned profile was found degraded …

OCPBUGS-31905: [release-4.14] [manual] : Add performance real time tuned template

---

pkg/performanceprofile/controller/performanceprofile_controller.go

`deleteDeprecatedComponents` function was added in older releases to overcome this issue:
https://github.com/openshift-kni/performance-addon-operators/pull/538
This is no longer relevant and can be removed since it was intented to fix an upgrade issue from an old version.

NO-JIRA: pao:controller: remove depracated function

---

pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/functests/1_performance/netqueues.go

The internal regular expression has duplicated exclamation mark that breaks the pattern.

OCPBUGS-30111: Negative net interface name does not reduce queues

---

Dockerfile
HACKING.md
hack/deploy-custom-nto.sh

Updated a script to deploy a custom NTO image to a cluster
* Using this script developers could easily test their code.
Running it will replace the NTO image in the current running operator deployment with the custom image.
Updated HACKING.md to build & deploy custom NTO image
* It is important to make sure this file contains correct steps, and does not turn outdated.
Therefore, a new contributor reading HACKING.md file is able to deploy a custom version of NTO.

PSAP-1354: Updated a script for deploying a custom NTO image to a cluster

---

pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/performanceprofile/controller/performanceprofile/resources/resources.go
pkg/performanceprofile/controller/performanceprofile/status/status.go
pkg/performanceprofile/controller/performanceprofile_controller.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go
pkg/performanceprofile/controller/status.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/utils/mcps/mcps.go

Before we start with the implementation itself we should do some preliminary  work in order to generalize some of the functions and flows so they could fit for the controller when it runs on  hypershift platform.
The main work done here, is extracting bits which are specific for non-hypershift platform and replacing methods with functions.
For example we want to pass the `client` from the caller because on hypershift the client is different than on non-hypershift platform.
NOTE: whether we decide to go with unified controller for both hypershift and none-hypertshift or a separate controller for each, this PR is good improvement in general and will allow us to reuse more code.
This is the main reason for dedicating a separate PR for this code changes.

CNF-6517: [Part 1]  Hypershift PAO adoption 

---

manifests/20-profile.crd.yaml
pkg/apis/tuned/v1/tuned_types.go
pkg/apis/tuned/v1/zz_generated.deepcopy.go
pkg/generated/informers/externalversions/factory.go
pkg/manifests/manifests.go
pkg/operator/controller.go
pkg/operator/hypershift.go
pkg/operator/profilecalculator.go
pkg/operator/profilecalculator_test.go
pkg/tuned/cmd/render/render.go
pkg/tuned/controller.go
test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go

The NTO operand is controlled by the operator by updates to two resources.  Its corresponding k8s Tuned Profile resource and tuned/rendered object, which contains a list of all `TuneD` (daemon) profiles.
While this setup works for most cases, there is a problem with this approach when a cluster administator changes both a current `TuneD` profile content and (at the same) time switches to a new `TuneD` profile completely.  Then, depending on the k8s object update timing, we could see two `TuneD` daemon reloads instead of just one.
Remove the tuned/rendered object and carry `TuneD` (daemon) profiles directly in the Tuned Profile k8s objects.

OCPBUGS-32469: Remove tuned/rendered object

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
test/e2e/performanceprofile/functests/utils/tuned/tuned.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

Set CPUFreq driver mode based on hardware generation which will set intel_pstate=active for IceLake and newer processors while it will disable the pstate for older generation of processors.
- For FlexRAN (and FlexRAN-like applications), the hardware vendor(I//) recommends to use the intel_pstate CPUFreq driver in active mode with HWP enabled on Ice Lake and later generations. The majority of Telco RAN DU deployments will be on the Ice Lake or newer generation hardware.
- We have One RAN customer who wants the intel pstate to be active as default. [RFE link](https://issues.redhat.com/browse/RFE-4138)
We introduced a function in [tuned](https://github.com/redhat-performance/tuned/blob/master/tuned/profiles/functions/function_intel_recommended_pstate.py) which returns appropriate CPUFreq …

CNF-11099: set intel_pstate driver to automatic as default

---

cmd/cluster-node-tuning-operator/main.go
pkg/performanceprofile/controller/performanceprofile/components/components.go
pkg/performanceprofile/controller/performanceprofile/components/handler/handler.go
pkg/performanceprofile/controller/performanceprofile/resources/resources.go
pkg/performanceprofile/controller/performanceprofile/status/status.go
pkg/performanceprofile/controller/performanceprofile/status/writer.go
pkg/performanceprofile/controller/performanceprofile_controller.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go

Since the controller implementation diverged on Hypershift platform, we need to add an abstraction layer
in order to handle a different type of implementation.
In this PR we introduce 2 interfaces:
1. `components.Handler` - which provides an API for handling the different components the controller owns.
2. `status.Writer` which provides an API for reporting the different statuses by the controller.
This PR doesn't add any new functionality but implementing the old reconciliation loop using the new interfaces introduced above.

CNF-6517: [Part 2] Hypershift PAO adoption

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go

Currently the test would fail when tested on machines with exactly isolated cpus equal to the requested cpus by the pod. This is because the worker nodes has already other pods running on them and thus they are using already a portion of the isolated cpus of the node. Scheduling a pod requesting all allocatable cpus would fail due to insufficient cpus on node.
Skip the test if the testing environment is not suitable for the test's requirements.

NO-JIRA: perfprof: e2e: account for node base load

---

Dockerfile
Dockerfile.rhel8
Dockerfile.rhel9
assets/performanceprofile/configs/ocp-tuned-one-shot.service
pkg/metrics/server.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/tuned/cmd/operand/cmd.go
pkg/tuned/cmd/render/render.go
pkg/tuned/controller.go
pkg/tuned/run.go
pkg/util/os.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

TuneD prior to kubelet in one-shot mode
Motivation.  In case of node reboots, all pods restart again in random order.
Since there's no control on pod restart order, it is possible that tuned
pods will start after the workload pods.  This means the workload pods can
start with partial tuning which can result in degraded performance or even
cause the workload pods crash.
This change is intended mostly for Telco use cases where PerformanceProfiles
are used.  To minimize the risk of affecting other deployments by backporting
this code, TuneD will start prior to kubelet only when PerformanceProfiles
are used.
Changes:
* Switch to /var/lib/ocp-tuned as the home directory for the operand
(TuneD) pod on the host.  This directory now holds configuration for the
TuneD daemon both running prior to …

OCPBUGS-26401: TuneD prior to kubelet in one-shot mode

---

pkg/performanceprofile/controller/performanceprofile_controller.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go
pkg/performanceprofile/controller/resources.go
pkg/performanceprofile/utils/testing/testing.go

This PR fixes an extra-reboot when upgrading OpenShift with paused
MCP "worker", for example during EUS-to-EUS upgrade. The extra-reboot
occurred because PerformanceProfile controller was reconciling against
rendered MC appearing in the MCP status. While this MC reflects current
MCP conditions, it does not reflect the latest planned state when the
MCP is paused.
Unpausing the MCP lead to one reboot when applying the target MC, and
one additional reboot after the performance profile was reconciled
against it.
This change eliminates this additional reboot because PerformanceProfile
is now reconciling against the latest planned MC before theMCP is
unpaused
/cc @MarSik @yanirq

OCPBUGS-32978: fix extra-reboot on upgrade with paused mcp worker

---

pkg/performanceprofile/controller/performanceprofile_controller.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go
pkg/performanceprofile/controller/resources.go
pkg/performanceprofile/utils/testing/testing.go

This PR fixes an extra-reboot when upgrading OpenShift with paused MCP "worker", for example during EUS-to-EUS upgrade. The extra-reboot occurred because PerformanceProfile controller was reconciling against rendered MC appearing in the MCP status. While this MC reflects current MCP conditions, it does not reflect the latest planned state when the MCP is paused.
Unpausing the MCP lead to one reboot when applying the target MC, and one additional reboot after the performance profile was reconciled against it.
This change eliminates this additional reboot because PerformanceProfile is now reconciling against the latest planned MC before the MCP is unpaused.
This is a manual cherry-pick from #1049 
/cc @MarSik @yanirq

OCPBUGS-32980: [release-4.14]:fix extra-reboot on upgrade with paused mcp worker

---

hack/render-sync.sh
pkg/performanceprofile/cmd/render/render.go
test/e2e/performanceprofile/cluster-setup/container-runtime-crun/enable-crun-worker-cnf.yaml
test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_node.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_runtimeclass.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_tuned.yaml

This is a manual cherry-pick of #975 
Fix bootstrap error  of "more than one ContainerRuntimeConfig found that matches MCP labels" when an additional ContainerRuntimeConfig is provided by user.
/cc @yanirq @MarSik

[release-4.14] OCPBUGS-30153: fix rendering extra ctrcfgs

---

pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
test/e2e/performanceprofile/functests/utils/client/clients.go
test/e2e/performanceprofile/functests/utils/client/dataplane.go
test/e2e/performanceprofile/functests/utils/hypershift/hypershift.go

On Hypershift we should be able to access both the management and hosted clusters.
For that, we should now have two clients, each communicates with a different cluster.
ControlPlaneClient - defines the API client to run CRUD operations on the control plane that will be used for testing.
DataPlaneClient - defines the API client to run CRUD operations on the data plane that will be used for testing.
On non-hypershift both client would point the same the cluster under the hood.
We also added Ginkgo assertions that prevent the user from using the wrong clients for the wrong objects.
For example using the `DataPlaneClient` for querying the `PerformanceProfile` object is completley fine on non-hypershift cluster, but will fail badly on hypershift (since `PerformanceProfile` objects, are not …

CNF-11817: e2e: control and data planes clients

---

.snyk

The '.snyk' exclude these paths under the vendor directory:
ginkgo/v2/internal/suite.go
controller-runtime/pkg/log/log.go
jaypipes/ghw/pkg/block/block_linux.go
These paths trigger a warning related to the generation of error messages containing sensitive information.
Currently, there is no available fix for these issues.

[release-4.15] OCPBUGS-28368: Add a '.snyk' to silence static code analysis warnings

---

test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

The hwlatdetect tests were executed without a default window size. We need to make sure the window size is always consistent and same.

CNF-10616: e2e: Added hwlatdetect default window size

---

test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go

Covers the test failure when hyper-threading is enabled and cyclictest & oslat pods requires at least 4 CPUs

NO-JIRA:e2e: latency: Add negative tests

---

hack/run-test.sh
test/e2e/performanceprofile/functests/0_config/test_suite_performance_config_test.go
test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/1_performance/hugepages.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/functests/1_performance/netqueues.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/1_performance/rt-kernel.go
test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
test/e2e/performanceprofile/functests/9_reboot/devices.go
test/e2e/performanceprofile/functests/Z_deconfig/Z_deconfig_suite_test.go
test/e2e/performanceprofile/functests/Z_deconfig/deconfig.go
test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
test/e2e/performanceprofile/functests/utils/consts.go
test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
test/e2e/performanceprofile/functests/utils/node_inspector/inspector.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go
test/e2e/performanceprofile/functests/utils/systemd/systemd.go
test/e2e/performanceprofile/functests/utils/tuned/tuned.go
test/e2e/performanceprofile/functests/utils/utils.go

On hypershift there is no MCO, hence there are no machine-config-daemon pods.
A different resolution is needed for accessing the underlying node for inspecting configurations.
This commit introduces a node inspector implemented as a daemonset.
Upon execution of test suites, a pod with elevated privileges and host filesystem mounted will be deployed on every node.
Also I have added Z-deconfig suite ('Z' prefix, will guarantee that it will be the last suite run) that will be used for cleanup.
This API will be used for both hypershift and non-hypershift systems.

CNF-11815: e2e: Added node inspector for inspecting nodes configuration

---

.snyk

The '.snyk' exclude these paths under the vendor directory:
ginkgo/v2/internal/suite.go
controller-runtime/pkg/log/log.go
jaypipes/ghw/pkg/block/block_linux.go
These paths trigger a warning related to the generation of error messages containing sensitive information.
Currently, there is no available fix for these issues.

 [release-4.14]  OCPBUGS-25137: Add a '.snyk' to silence static code analysis warnings

---

Makefile
pkg/operator/controller.go
pkg/operator/profilecalculator.go
pkg/operator/profilecalculator_test.go
pkg/tuned/controller.go

The PR #1019 includes a fair bit of cleanup and preparation code which may merge independently because these improvements are [liked anyway](https://github.com/openshift/cluster-node-tuning-operator/pull/1019#pullrequestreview-2073382408), and doing so would simplify the review and finalization of #1019 itself.

OCPBUGS-28647: tuned: operand: deferred updates prepare: cleanups from #1019

---

pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/functests/1_performance/netqueues.go

Negative net interface name does not reduce queues
This is a semi-automated cherry-pick of #973 and replaces #1062
The internal regular expression has duplicated exclamation mark that breaks the pattern.

[release-4.15] OCPBUGS-33929: Negative net interface name fix

---

Dockerfile

In the `go.mod` file, we are using the `toolchain` directive, which is not recognized by golang 1.20.

NO-JIRA:Dockerfile:bump go-builder to 1.22

---

cmd/cluster-node-tuning-operator/main.go

remove code which was meant to handle the upgrade
from 4.13 to 4.14. We're at least two version past that.

NO-JIRA: remove 4.13->4.14 compatibility code

---

test/e2e/performanceprofile/functests/utils/label/label.go

Platform labels are used to indicate that test are only valid for a specific platform.
A test which doens't contain any `Platfrom` label, is a platform agnostic test.
These new label type will use to filter/focus e2e tests, based on the tested platform.

NO-JIRA: e2e:labels: add platform type labels

---

pkg/performanceprofile/controller/performanceprofile/components/handler/handler.go
pkg/performanceprofile/controller/performanceprofile/resources/resources.go
pkg/performanceprofile/controller/performanceprofile/status/writer.go
pkg/performanceprofile/controller/performanceprofile_controller.go

Increase the verbosiness required to emit log messages to reduce the log amount.
Note this change doesn't address the reason for periodic reconciles, we only review the verbosiness of log messages.

OCPBUGS-34972: perfprof: bump verbosiness of logs

---

pkg/util/manifests.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go

We're facing issues with the existing regex pattern,
so let's perform the check properly, by decoding the output
and compare the values.
on other tests we would have to extend the regex, because decoding the output is too complex in the 
current circumstances

NO-JIRA: e2e:performance: handle regex failures in tests

---

hack/run-test.sh

We are usually having a mismatch between the ginkgo CLI and ginkgo package, because we are updating the ginkgo package on the go.mod but forget to do the same on our test's script.
something like:
```
Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:
Ginkgo CLI Version:
2.6.1
Mismatched package versions found:
2.17.1 used by 0_config, 1_performance, 6_mustgather_testing, 10_performance_ppc
```
let's automate the process to save some work and avoid bugs that might happens due to breaking changes between versions which are not matching

No-JIRA: e2e:run-test.sh: match ginkgo CLI to ginkgo package

---

test/e2e/performanceprofile/functests/utils/nodepools/nodepools.go

Due to the latest changes in the hypershift nodepool conditions API (https://github.com/openshift/hypershift/commit/05a7fa17c8156585658b72fa9453a569963ee2bd) in order to check that the tuning has completed and the nodepool is ready, we need to change our check accordingly - check that the condition is false instead of missing.

NO-JIRA: hypershift: check updatingConfig condition to be false instead of missing

---

cmd/cluster-node-tuning-operator/main.go
pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift_test.go
pkg/performanceprofile/controller/performanceprofile_controller.go
test/e2e/performanceprofile/functests/utils/client/dataplane.go

On hypershift many objects are encapsulated in ConfigMaps.
So if we're given the name of the encapsulated object,
trying to get the ConfigMap with same name is not enough,
because the internal object's name and the ConfigMap name
doesn't have to be equal.
Hence, the client have to `List()` all the ConfigMaps in the
hosted control plane namespace, extracts the data and
compares the names.
In case it was not found, it mimics an IsNotFound error
to be compatible with the error returned from the API server.
The implementation can be improved, by caching some of the information,
but before we come with "fancy-but-not-proved-to-be-efficent" solutions
let's evaluate the simplest solution first and iterate later if needed.

NO-JIRA:pao:hypershift: fix client implementation

---

hack/dockerfile_install_support.sh

Fix requested profile doesn't exist for upstream builds.  Upstream `TuneD` now ships system profiles in /usr/lib/tuned/profiles vs /usr/lib/tuned.

NO-JIRA: Fix requested profile doesn't exist

---

pkg/performanceprofile/controller/performanceprofile/components/handler/handler.go
pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
pkg/performanceprofile/controller/performanceprofile/status/writer.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go
pkg/performanceprofile/utils/testing/testing.go

We want same unit tests to be running for hypershift,
so we convert the tests into table and added one entry for OCP and one for HCP.
As for now most of the tests are not supported/qualified to be running on HCP and
are skipped for now.
But it is better and safer to have a low coverage than nothing.
We'll work to support additional tests in future PRs

NO-JIRA: hypershift:unitests: adjust controller unit-tests

---

Makefile
test/e2e/performanceprofile/functests/0_config/config.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/1_performance/hugepages.go
test/e2e/performanceprofile/functests/1_performance/irqbalance.go
test/e2e/performanceprofile/functests/1_performance/netqueues.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/1_performance/rt-kernel.go
test/e2e/performanceprofile/functests/1_performance/test_suite_performance_test.go
test/e2e/performanceprofile/functests/3_performance_status/status.go
test/e2e/performanceprofile/functests/utils/client/clients.go
test/e2e/performanceprofile/functests/utils/cluster/cluster.go
test/e2e/performanceprofile/functests/utils/discovery/discovery.go
test/e2e/performanceprofile/functests/utils/mcps/mcps.go
test/e2e/performanceprofile/functests/utils/nodepools/nodepools.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go
test/e2e/performanceprofile/functests/utils/pods/pods.go
test/e2e/performanceprofile/functests/utils/profiles/profiles.go
test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go
test/e2e/performanceprofile/functests/utils/tuned/tuned.go

This PR includes all the necessary adaptations for the `1_performance` suite to be compatible with Hypershift. These changes encompass modifications to some of the utility functions used by the suite, as well as updates to the tests within the suite itself. Additionally, this PR integrates this suite to run alongside the `0_config` suite in the Hypershift lane.

CNF-7123: Enable and adjust 1_performance suite on Hypershift

---

Makefile

0_config requires now `pkg/manifests`, so we need
to make sure bindata is generated
extracted from #1019 because it helps other PRs too: https://github.com/openshift/cluster-node-tuning-operator/pull/1019#discussion_r1686007433 (xref: #1089)

NO-JIRA: makefile: ensure bindata

---

Makefile
hack/build-pao-test-bin.sh
manifests/20-profile.crd.yaml
pkg/apis/tuned/v1/tuned_types.go
pkg/operator/controller.go
pkg/operator/profilecalculator.go
pkg/tuned/cmd/render/render.go
pkg/tuned/controller.go
pkg/tuned/controller_test.go
pkg/tuned/status.go
pkg/tuned/status_test.go
pkg/tuned/tuned_parser.go
pkg/util/annotations.go
pkg/util/annotations_test.go
test/e2e/basic/rollback.go
test/e2e/deferred/basic.go
test/e2e/deferred/non_regression.go
test/e2e/deferred/operator_test.go
test/e2e/deferred/restart.go
test/e2e/testing_manifests/deferred/tuned-basic-00.yaml
test/e2e/testing_manifests/deferred/tuned-basic-10.yaml
test/e2e/testing_manifests/deferred/tuned-basic-20.yaml
test/e2e/util/ready/node.go
test/e2e/util/ready/pod.go
test/e2e/util/util.go
test/e2e/util/verification.go
test/e2e/util/wait/node.go
test/e2e/util/wait/pod.go

Users are able to make tuning changes through NTO/TuneD by updating the CRs on a running system.
When the tuning change is done, the NTO causes the tuned process to restarts, whose unwanted side effect is the tuned process rolling back ALL the tuning and then reapplying it.
In some key use cases, this disrupts the workload behavior.
We add an annotation that cause the update not to be applied immediately, but to be deferred till the next node restart. The NTO operator will continue handle the tuned objects as it does today.
This includes unpacking all profiles on the node.
The deferred annotation would be deduplicated from the `tuned` object to all the contained `tunedprofiles`. If the recommended profile computed for a node is originated from a `tuned` object which has the annotation, …

OCPBUGS-28647: tuned: operand: add support for deferred updates

---

hack/dockerfile_install_support.sh

#1058 introduced an issue, where assets meant to be copied to /usr/local/bin were being copied to /usr/local/bin/bin.  Fix this.  Additional cleanup (duplicate statements in if/else) to follow.
/cc @jupierce

NO-JIRA: Fix the destination of asset's copy

---

manifests/20-profile.crd.yaml
pkg/apis/tuned/v1/tuned_types.go
pkg/apis/tuned/v1/zz_generated.deepcopy.go
pkg/generated/informers/externalversions/factory.go
pkg/manifests/manifests.go
pkg/operator/controller.go
pkg/operator/hypershift.go
pkg/operator/profilecalculator.go
pkg/operator/profilecalculator_test.go
pkg/tuned/cmd/render/render.go
pkg/tuned/controller.go
test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go

This is a manual backport of https://github.com/openshift/cluster-node-tuning-operator/pull/1036 .  Changes from #1036: using the current (deprecated) `k8s.io/utils/pointer` package and adjusted the test code to use it.
The NTO operand is controlled by the operator by updates to two resources.  Its corresponding k8s Tuned Profile resource and tuned/rendered object, which contains a list of all TuneD (daemon) profiles.
While this setup works for most cases, there is a problem with this approach when a cluster administator changes both a current TuneD profile content and (at the same) time switches to a new TuneD profile completely.  Then, depending on the k8s object update timing, we could see two TuneD daemon reloads instead of just one.
Remove the tuned/rendered object and carry TuneD …

OCPBUGS-36870: Remove tuned/rendered object

---

Makefile
pkg/tuned/cmd/render/render.go
pkg/tuned/controller.go
test/e2e/deferred/basic.go
test/e2e/deferred/non_regression.go
test/e2e/deferred/restart.go

cleanups suggested late in the #1019 cycle or emerged after the first nightly CI run

OCPBUGS-28647: deferred updates: cleanups

---

cmd/cluster-node-tuning-operator/main.go
pkg/performanceprofile/controller/performanceprofile/components/components.go
pkg/performanceprofile/controller/performanceprofile/components/handler/handler.go
pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
pkg/performanceprofile/controller/performanceprofile_controller.go

In order to support feature gate on Hypershift,
we need to build and provide an `eventRecorder` for the `featureGateAccessor`.
The `eventRecorder` uses the controllerRef of NTO pod when it emits an event:
https://github.com/openshift/cluster-node-tuning-operator/blob/81b7b9d35113848bbcf96758829a4cb54ac5b784/vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go#L199
In order to get the controllerRef, we need to `Get()` NTO pod and extract
the ownerReference from it's metadata:
https://github.com/openshift/cluster-node-tuning-operator/blob/81b7b9d35113848bbcf96758829a4cb54ac5b784/vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go#L76
Theoretically, on Hypershift we need to use the MNG client to `Get()`
NTO pod, hence we should also pass the rest config …

CNF-12711: hypershift: enable feature gate support

---

pkg/operator/hypershift.go
pkg/performanceprofile/controller/performanceprofile_controller.go

The predicate addition will trigger the reconciliation loop every time there's a change in the `ConfigMap` that holds the `containerruntimeconfig`.
Signed-off-by: Talor Itzhak [titzhak@redhat.com](mailto:titzhak@redhat.com)

CNF-13530: controller: predicate for `containerruntimeconfig`

---

assets/tuned/manifests/ds-tuned.yaml
manifests/50-operator-ibm-cloud-managed.yaml
manifests/50-operator.yaml

[OCPBUGS-37306](https://issues.redhat.com/browse/OCPBUGS-37306
)
Manual cherry-pick of [#968](https://github.com/openshift/cluster-node-tuning-operator/pull/968)

[release-4.15] OCPBUGS-37306: set required-scc for openshift workloads

---

test/e2e/performanceprofile/functests/0_config/config.go
test/e2e/performanceprofile/functests/utils/hypershift/hypershift.go

* Remove deprecated environment variables in the e2e tests.
* Rename environment variables in the e2e tests to represents their meaning in more accurate way.
More details in the commits themselves.

NO-JIRA:e2e:hypershift: remove/rename deprecated env variables

---

Dockerfile
Dockerfile.rhel8
Dockerfile.rhel9
assets/performanceprofile/configs/ocp-tuned-one-shot.service
pkg/metrics/server.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/tuned/cmd/operand/cmd.go
pkg/tuned/cmd/render/render.go
pkg/tuned/controller.go
pkg/tuned/run.go
pkg/util/os.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

Manual backport of #1045 due to changes in Dockerfile and deprecated k8s.io/utils/pointer Go module.
Motivation.  In case of node reboots, all pods restart again in random order. Since there's no control on pod restart order, it is possible that tuned pods will start after the workload pods.  This means the workload pods can start with partial tuning which can result in degraded performance or even cause the workload pods crash.
This change is intended mostly for Telco use cases where PerformanceProfiles are used.  To minimize the risk of affecting other deployments by backporting this code, TuneD will start prior to kubelet only when PerformanceProfiles are used.
Changes:
* Switch to /var/lib/ocp-tuned as the home directory for the operand (TuneD) pod on the host.  This directory now …

OCPBUGS-36868: TuneD prior to kubelet in one-shot mode

---

test/e2e/performanceprofile/functests/README.md

Documents all the the environment variables that are required for running e2e locally when NTO is running on Hypershift platform.

NO-JIRA:e2e:document: how to run locally on HCP platform

---

pkg/metrics/server.go
pkg/operator/controller.go

Stop writing root certificate bundle of the metrics server for client authentication to /tmp.  There are two reasons for this.  Firstly, it is racy and it could cause the operator to temporarily start without client authentication.  Secondly, it prevents us from making the operator more secure by setting its container securityContext.readOnlyRootFilesystem=true.
Resolves: OCPBUGS-34917

OCPBUGS-34917: Operator: do not use /tmp

---

pkg/operator/controller.go
pkg/operator/profilecalculator.go
pkg/tuned/controller.go
pkg/tuned/controller_test.go
pkg/util/annotations.go
pkg/util/annotations_test.go
test/e2e/deferred/basic.go
test/e2e/deferred/non_regression.go
test/e2e/deferred/operator_test.go
test/e2e/deferred/restart.go
test/e2e/deferred/updates.go
test/e2e/testing_manifests/deferred/tuned-basic-updates-00.yaml
test/e2e/testing_manifests/deferred/tuned-basic-updates-10.yaml

To fully support the usecase described in OCPBUGS-28647 and fix
the issue, we need to further distinguish between first-time
profile change and (in-place) profile change. This is required to
better support a GitOps flow.
The key distinction is if the recommended profile changes or not,
and there's a desire to defer application of changes only when a
profile is updated (e.g. sysctl modified), not the first time it
is applied.
Thus:
- first-time profile change is a change which triggers a change of the recommended profile.
- (in-place) profile update is a change which does NOT cause a switch to a different TuneD profile. This usually, but not exclusively, involve changes of the sysctls.
We change the way the annotation is used. We now require a value,
which can be either
- always: every …

OCPBUGS-28647: tuned: distinguish deferred updates

---

test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go

Remove vestiges of annotation ignore-cgroups-version from tests
Annotation performance.openshift.io/ignore-cgroups-version was added as
a switch that could be used during development of cgroups v2 related
code. One of the E2E tests was not cleaned up when support for the
annotation was removed. Clean up this E2E test now.

NO-JIRA: Remove vestiges of annotation ignore-cgroups-version from tests

---

manifests/50-operator-ibm-cloud-managed.yaml
manifests/50-operator.yaml

This change switches the operator's `securityContext.readOnlyRootFilesystem` to `true`.  This is in line with the OCP's Control Plane required privileges policy,

PSAP-1428: Read-only filesystem for the operator

---

manifests/20-profile.crd.yaml
pkg/apis/tuned/v1/tuned_types.go
pkg/apis/tuned/v1/zz_generated.deepcopy.go
pkg/manifests/manifests.go
pkg/operator/controller.go
pkg/operator/hypershift.go
pkg/operator/profilecalculator.go
pkg/operator/profilecalculator_test.go
pkg/tuned/controller.go
test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go

This is a backport #1110 of which resolved OCPBUGS-36870 in 4.15.
The NTO operand is controlled by the operator by updates to two resources.  Its corresponding k8s Tuned Profile resource and tuned/rendered object, which contains a list of all TuneD (daemon) profiles.
While this setup works for most cases, there is a problem with this approach when a cluster administator changes both a current TuneD profile content and (at the same) time switches to a new TuneD profile completely.  Then, depending on the k8s object update timing, we could see two TuneD daemon reloads instead of just one.
Remove the tuned/rendered object and carry TuneD (daemon) profiles directly in the Tuned Profile k8s objects.
Resolves: OCPBUGS-37754

OCPBUGS-37754: Remove tuned/rendered object

---

Dockerfile
HACKING.md
Makefile

- Makefile will now use the value from GOARCH to set the target architecture
- If not specified then it will use the architecture of the running system
- Add relevant documentation to HACKING

CNF-13014: Add cross compiling support to Makefile

---

Dockerfile
Dockerfile.rhel8
Dockerfile.rhel9
assets/performanceprofile/configs/ocp-tuned-one-shot.service
pkg/metrics/server.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/tuned/cmd/operand/cmd.go
pkg/tuned/controller.go
pkg/tuned/run.go
pkg/util/os.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

Manual backport of #1125 which fixed OCPBUGS-36868 for 4.15.
Motivation.  In case of node reboots, all pods restart again in random order. Since there's no control on pod restart order, it is possible that tuned pods will start after the workload pods.  This means the workload pods can start with partial tuning which can result in degraded performance or even cause the workload pods crash.
This change is intended mostly for Telco use cases where PerformanceProfiles are used.  To minimize the risk of affecting other deployments by backporting this code, TuneD will start prior to kubelet only when PerformanceProfiles are used.
Changes:
* Switch to /var/lib/ocp-tuned as the home directory for the operand (TuneD) pod on the host.  This directory now holds configuration for the TuneD daemon …

OCPBUGS-38629: TuneD prior to kubelet in one-shot mode

---

HACKING.md
Makefile
hack/deploy-custom-nto.sh

- Since $TAG by default is using the local git branch name, this can cause problems if special characters (notably '/') are used
- Add section to HACKING.md about the potential error

CNF-13014: Allow specifying $TAG separately from the full image path

---

manifests/20-profile.crd.yaml
manifests/20-tuned.crd.yaml
pkg/apis/tuned/v1/tuned_types.go
pkg/operator/controller.go
pkg/operator/profilecalculator.go
pkg/tuned/controller.go
pkg/util/log.go

This adds support for setting NTO operand (ocp-tuned) klog logging verbosity via configuring Tuned CR.
Example recommend section:
```
recommend:
- match:
- label: profile
priority: 20
profile: openshift-profile
operand:
verbosity: 2
```
This is on a per Profile/node basis and no operand/`TuneD` restarts are required.

PSAP-1471: Add support for setting operand verbosity

---

pkg/tuned/controller.go
test/e2e/deferred/basic.go
test/e2e/deferred/operator_test.go

Process recommended profile change even when the profile itself has not changed itself. The internal profile fingerprint tracking was not updated during recommended profile update with no internal changes.

OCPBUGS-38795: Fix defer status during recommended profile change

---

assets/performanceprofile/configs/ocp-tuned-one-shot.service
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

Add cluster-wide proxy environment file /etc/mco/proxy.env to ocp-tuned-one-shot.service file.  This allows podman to pull NTO image in environments which need to use http(s) proxy for out-of-cluster connections.
Resolves: OCPBUGS-39005

OCPBUGS-39005: Add cluster-wide proxy env file

---

pkg/performanceprofile/controller/performanceprofile/components/utils.go
pkg/performanceprofile/controller/performanceprofile/components/utils_test.go

The padding size was hardcoded to support max 64 nibbles which is equivalent to 256 cpus (%064x). Any mask bigger than this that was not itself 32 cpu aligned broke the chunking algorithm.

OCPBUGS-36431: Fix generated cpu mask for 512+ cpus

---

Dockerfile

Since we are using a multi stage builds in the Dockerfile (2 builds), and we need to use the tuned submodule also in the second layer, we must ensure we copy the directory from the builder image (where we initialize the tuned submodule), to the final image.
This PR eliminates building errors using the `make local-image` target like we had before:
```
+ cd /root/assets/tuned/tuned
+ LC_COLLATE=C
+ cat ../patches/030-no-bootloader-errors.diff
+ patch -Np1
can't find file to patch at input line 10
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|NTO currently supports the bootloader plugin only on RHCOS via the integration
|with MCO.  Disable patching of BLS entries and grub configuration files so
|that error messages from the …
```

OCPBUGS-41995:  Fixing empty tuned submodule when using Dockerfile

---

pkg/tuned/controller.go
test/e2e/deferred/basic.go
test/e2e/deferred/non_regression.go
test/e2e/deferred/operator_test.go
test/e2e/deferred/restart.go
test/e2e/deferred/updates.go
test/e2e/testing_manifests/deferred/tuned-basic-00.yaml
test/e2e/testing_manifests/deferred/tuned-basic-10.yaml
test/e2e/testing_manifests/deferred/tuned-basic-20.yaml
test/e2e/testing_manifests/deferred/tuned-basic-updates-00.yaml
test/e2e/testing_manifests/deferred/tuned-basic-updates-10.yaml

There are conditions on which we should not set the reload flag. This avoid regression in the test
"Profile deferred when applied should trigger changes when applied fist, then deferred when edited, if tuned restart should be kept deferred"

NO-JIRA: deferred updates: fix in-place update handling on reboot

---

Makefile

This infrastructure is required to run the performance profile update suite on the U/S CI Hypershift lane. Currently, the test execution has been commented out until full support is available.
Needed for: https://github.com/openshift/release/pull/56871

CNF-14557:hypershift: make target for perf profile update suites

---

HACKING.md
Makefile
hack/deploy-custom-nto.sh
hack/test-tuned-fdp.sh
pkg/tuned/controller.go

This change adds a script to test internal TuneD FDP releases
`hack/test-tuned-fdp.sh`.  The script builds on top of
`hack/deploy-custom-nto.sh` script, but it makes use of `Dockerfile.rhel9`
versus the default upstream `Dockerfile`.
For detail on how to use it, refer to "Example invocation" section within
the script.  At a minimum, you'll typically want to supply your quay.io
username and baseurl to the TuneD FDP repository.

NO-JIRA: Add a script to test internal TuneD FDP releases

---

assets/performanceprofile/configs/ocp-tuned-one-shot.service
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

This is a manual backport of https://github.com/openshift/cluster-node-tuning-operator/pull/1166
Add cluster-wide proxy environment file `/etc/mco/proxy.env` to `ocp-tuned-one-shot.service` file.  This allows podman to pull NTO image in environments which need to use http(s) proxy for out-of-cluster connections.
Resolves: OCPBUGS-42284

OCPBUGS-42284: Add cluster-wide proxy env file

---

test/e2e/performanceprofile/functests/1_performance/performance.go

Recent MCO change https://github.com/openshift/machine-config-operator/pull/4557 enforced custom MCP to have worker label.  This caused an issue with "Create second performance profiles on a cluster" pao-functest. Adjust the tests's MachineConfigPool Spec to use MatchExpressions instead of MatchLabels, so that the new MCO requirement "All custom MachineConfigPools must inherit from the worker pool and must have a machineConfigSelector that matches for a
'machineconfiguration.openshift.io/role: worker' label" is met.

NO-JIRA: Fix failing pao-functests after a MCO change

---

test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

During testing on x86_64 cluster from an arm64 host, I've
observed strange context deadlines when enabling stdin in
ExecCommandOnPod() function.
Disable stdin as it is not needed during non-interactive tests.
Other changes:
* Drop obsolete test "test_id:32375".
* Drop unnecessary "/bin/bash -c" in some tests.
Further cleanup possible, but it could make code
slightly less readable, so avoiding it for now.

NO-JIRA: Fix context deadlines in ExecCommandOnPod()

---

pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler_test.go
pkg/performanceprofile/controller/performanceprofile/hypershift/consts/consts.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go

According to https://github.com/openshift/enhancements/pull/1671
HyperShift operator will mirror KubeletConfig's ConfigMap to the hosted clusters.
In order to identify the desired ConfigMaps in efficient way,
HyperShift operator lists the ConfigMaps by this unique label.
KubeletConfig's ConfigMap which is generated by NTO should be mirror as well
hence the reason for adding the label.

NO-JIRA: hypershift:handler: add KubeletConfig unique label

---

pkg/operator/controller.go
pkg/operator/profilecalculator.go
pkg/tuned/controller.go
pkg/tuned/controller_test.go
pkg/util/annotations.go
pkg/util/annotations_test.go
test/e2e/deferred/basic.go
test/e2e/deferred/non_regression.go
test/e2e/deferred/operator_test.go
test/e2e/deferred/restart.go
test/e2e/deferred/updates.go
test/e2e/testing_manifests/deferred/tuned-basic-00.yaml
test/e2e/testing_manifests/deferred/tuned-basic-10.yaml
test/e2e/testing_manifests/deferred/tuned-basic-20.yaml
test/e2e/testing_manifests/deferred/tuned-basic-updates-00.yaml
test/e2e/testing_manifests/deferred/tuned-basic-updates-10.yaml

This is a manual cherry pick of:
https://github.com/openshift/cluster-node-tuning-operator/pull/1129 OCPBUGS-28647: tuned: distinguish deferred updates
https://github.com/openshift/cluster-node-tuning-operator/pull/1142 OCPBUGS-38795: Fix defer status during recommended profile change 
https://github.com/openshift/cluster-node-tuning-operator/pull/1162 NO-JIRA: deferred updates: fix in-place update handling on reboot

[release-4.17] OCPBUGS-38721: tuned: distinguish deferred updates

---

assets/performanceprofile/configs/ocp-tuned-one-shot.service
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

This is a manual backport of https://github.com/openshift/cluster-node-tuning-operator/pull/1171
Add cluster-wide proxy environment file /etc/mco/proxy.env to ocp-tuned-one-shot.service file.  This allows podman to pull NTO image in environments which need to use http(s) proxy for out-of-cluster connections.
Resolves: OCPBUGS-42567

OCPBUGS-42567: Add cluster-wide proxy env file

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

When using a PerformanceProfile, a TuneD scheduler was setting sched_migration_cost_ns.  This setting was previously used by throughput-performance and latency-performance profiles.  However, it was dropped from these profiles based on performance evaluation for RHEL-9 as discussed in rhbz#1957829.
Setting sched_migration_cost_ns causes issues when SecureBoot/kernel_lockdown is in effect.  Do not set this tunable when using PerformanceProfiles.
Resolves: OCPBUGS-38900

OCPBUGS-38900: Drop sched_migration_cost_ns setting

---

assets/performanceprofile/configs/ocp-tuned-one-shot.service
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

There are known podman [issues/races](https://github.com/containers/podman/pull/23524), which may cause "podman run" failures (e.g. OCPBUGS-42492).  While the correct approach is to fix podman and its configuration, this does not prevent against unknown/future podman issues which can easily be resolved by retries.
Add restart on failure for ocp-tuned-one-shot.service and a 5s wait between retries.
Resolves: OCPBUGS-42492

OCPBUGS-42492: Make ocp-tuned-one-shot.service restart on-failure

---

pkg/performanceprofile/controller/performanceprofile_controller.go

A case when tuned profile exists, but there's no performance profile, is completely valid state.
We should not log error in that case.
This casues spamming NTO pod's logs.

NO-JIRA: logs: avoid spamming when PerformanceProfile is missing

---

hack/deploy-custom-nto.sh

This improves the hack/deploy-custom-nto.sh script to not require the ORG variable all the time. It defaults to username which users commonly use for their quay.io as well.
The second change makes sure the newly built image has an unique tag formed of short git hash and build timestamp. This helps when systems are configured to use cached images. Each tag is unique and so the cluster will always pull the new build.

NO-JIRA: Default to username and timestamp for custom NTO push

---

pkg/apis/performanceprofile/v2/performanceprofile_types.go
pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go

- Include valid sizes for both x86 and aarch64 in the validation check
- Included notes for aarch64 where each kernel page size includes only a single valid hugepage size
- After discusion on Slack I have also added some additional validations:
-- Verify all nodes in the list have the same cpu architecture
-- Verify all nodes in the list have the same cpu capacity
-- Verify that the selected hugepage size is valid for the cpu architecture

CNF-13193: Update NTO Hugepages size validation

---

assets/performanceprofile/tuned/openshift-node-performance
assets/performanceprofile/tuned/openshift-node-performance-amd-x86
assets/performanceprofile/tuned/openshift-node-performance-arm-aarch64
assets/performanceprofile/tuned/openshift-node-performance-intel-x86
pkg/performanceprofile/controller/performanceprofile/components/consts.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

- This makes use of a new helper function in tuned that was added in tuned 2.24 to get cpu information from lscpu
- Adds separate tuning files for AMD/X86, ARM/AArch64, and Intel/X86
- Platform specific tuning can be added to the appropriate tuning file and will loaded automatically by the openshift-node-performance profile
- Tuning for AMD and ARM should be considered not final at this time

CNF-14090: Add vendor and architecture specific tuning options

---

assets/performanceprofile/tuned/openshift-node-performance-amd-x86
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

- "=on" is not a valid value for amd_iommu
- amd_iommu is enabled by default unless you specify "amd_iommu=off", unlike intel
- See kernel docs for more information (https://docs.kernel.org/admin-guide/kernel-parameters.html)

OCPBUGS-43665: Drop amd_iommu=on from amd tuning

---

assets/performanceprofile/tuned/openshift-node-performance
assets/performanceprofile/tuned/openshift-node-performance-intel-x86
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

An upgrade from previous version causes one extra reboot due to differently ordered kernel arguments. This is a side effect of platform specific tuned profile split we merged in https://github.com/openshift/cluster-node-tuning-operator/pull/1083
This fix updates the Intel specific tuned profile to follow the same ordering that was used in the past.
It does so by exploiting a specific tuned behavior of the bootloader plugin. It orders the kernel argument cmdline_suffix keys based on the order of first appearance. Any additional appearance just changes the value, but not the ordering.
The change is only needed for Intel, because we have never supported other platforms before and so upgrade is not an issue.

OCPBUGS-43666: Fix kernel arguments ordering on Intel

---

Dockerfile

- Since master branch is used for 4.18, we should be using the 4.18 OCP image here like we do in Dockerfile.rhel9 and .ci-operator.yaml

CNF-13014: Align dockerfile ocp version

---

test/e2e/performanceprofile/functests/utils/node_inspector/inspector.go

We need to ensure the node inspector is fully deleted when a suite ends; otherwise, the subsequent suite may encounter an error if it attempts to create the namespace while it's still in the termination process.

OCPBUGS-43992: e2e: wait for node inspector deletion

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go

This is a minumum change to unblock 4.16 CI based on #1182  to skip OCPBUGS-43280 while the investigation of the real issue continues.

OCPBUGS-44180: Unblock 4.16 CI

---

test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
test/e2e/performanceprofile/functests/utils/node_inspector/inspector.go

Using the global namespace object leads to an error
when trying to recreate the namespace againg.
This is becuase when the first `Create` call return
the object is fullfiled with some metadata from the API server
like `resourceVersion`.
This in turn leads to error when trying to reuse the object for creation
becuase the API doesn't expect the `resourceVersion` to be set.

NO-JIRA: nodeInspector: do not reuse namespace

---

Dockerfile
Dockerfile.rhel8
Dockerfile.rhel9

This is a manual backport of #1061.
The new TuneD option profile_dirs defines custom TuneD directories. Fix the order of the directories so that the system TuneD directory (/usr/lib/tuned) is the first one (searched last), and the custom TuneD directory (/var/lib/ocp-tuned/profiles) is the last one (searched first).
Resolves: OCPBUGS-44283

OCPBUGS-44283: right-hand-side profile_dirs take precedence

---

Dockerfile
Dockerfile.rhel9
assets/performanceprofile/configs/ocp-tuned-one-shot.service
assets/tuned/manifests/ds-tuned.yaml
hack/dockerfile_install_support.sh
pkg/tuned/cmd/render/render.go
pkg/tuned/controller.go
pkg/tuned/run.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml

In line with the "Principle of least privilege", add
readOnlyRootFilesystem to the NTO operand's container securityContext.
Key changes:
* NTO's operand daemonset sets the readOnlyRootFilesystem container
securityContext.
* Use memory-backed emptyDir for /etc/tuned.
* /tmp uses memory-backed emptyDir now to allow the operand's TuneD
daemon writing temporary files when using profiles such as the
cpu-partitioning profile.
* TuneD container's home directory is now /run/ocp-tuned with a link to
host's ocp-tuned persistent directory:
persist -> /host/var/lib/ocp-tuned
* Make /var/lib/tuned directory persistent on the host by:
/var/lib/tuned -> /host/var/lib/tuned
The persistent directory is populated by files such as ksm-masked coming
from cpu-partitioning profile.
* Change the …

PSAP-1428: read only root filesystem

---

Makefile

Setting the value explicitly causes issues during cross-building and running tests from other OSes, such as darwin.  Drop this explicit setting.

NO-JIRA: Drop GOOS=linux from Makefile

---

pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go

- Attempting to validate the performance profile's fields in an external context without a validatorClient was causing a nil pointer dereference
- If the validatorClient is not present then skip the validation that would required it and log a warning message (CPU arch, CPU capacity)

OCPBUGS-44477: Fix nil pointer dereference caused by external calling of validation function

---

assets/performanceprofile/tuned/openshift-node-performance
pkg/generated/informers/externalversions/factory.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

This is a manual backport of #1203.
When using a PerformanceProfile, a TuneD scheduler was setting sched_migration_cost_ns.  This setting was previously used by throughput-performance and latency-performance profiles.  However, it was dropped from these profiles based on performance evaluation for RHEL-9 as discussed in rhbz#1957829.
Setting sched_migration_cost_ns causes issues when SecureBoot/kernel_lockdown is in effect.  Do not set this tunable when using PerformanceProfiles.
Resolves: OCPBUGS-44275

OCPBUGS-44275: Drop sched_migration_cost_ns setting

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

This is a manual backport of #1203.
When using a PerformanceProfile, a TuneD scheduler was setting sched_migration_cost_ns.  This setting was previously used by throughput-performance and latency-performance profiles.  However, it was dropped from these profiles based on performance evaluation for RHEL-9 as discussed in rhbz#1957829.
Setting sched_migration_cost_ns causes issues when SecureBoot/kernel_lockdown is in effect.  Do not set this tunable when using PerformanceProfiles.
Resolves: OCPBUGS-44506

OCPBUGS-44506: Drop sched_migration_cost_ns setting

---

pkg/performanceprofile/profilecreator/profilecreator.go
pkg/performanceprofile/profilecreator/profilecreator_test.go

ProcessorCore.Index indicates the zero-based index of the core in the
Cores slice. While core might be shown in a different order, they can still
be equivalent. See: jaypipes/ghw#346.
Adjust the equality check to skip this field to fix this:
```
Error: targeted nodes differ: nodes host1.development.lab and host2.development.lab have different topology: the CPU cores differ: processor core #20 (2 threads), logical processors [2 66] vs processor core #20 (2 threads), logical processors [2 66]
```
And add a unit test to cover this scenario and the sortTopology function. 
Signed-off-by: Shereen Haj <shajmakh@redhat.com>

OCPBUGS-44372: PPC: skip comparing ProcessorCore.Index between NUMA cores 

---

Makefile
test/e2e/performanceprofile/functests/12_hypershift/12_hypershift_suite_test.go
test/e2e/performanceprofile/functests/12_hypershift/hypershift.go
test/e2e/performanceprofile/functests/utils/nodepools/nodepools.go

- Added tests for Multiple Performance Profile under different nodepools
- Adjusted nodepool utility to handle multiple nodepool
- Added test suite run in makefile

OCPBUGS-43832: E2E: Add tests to support NTO over hypershift with multi nodepools.

---

hack/dockerfile_install_support.sh

PR #1099 broke upstream and OKD builds as it added a dependency on rsync.  quay.io/centos/centos:stream9 image does not ship rsync by default.
Once we can use the new golang's recursive copy (CopyFS) functionality in go 1.23 (https://github.com/golang/go/issues/62484), use it and remove the dependency on rsync.

NO-JIRA: Fix upstream and OKD builds

---

pkg/performanceprofile/profilecreator/profilecreator.go

Copy-paste mistake in reporting the difference in logical processors list; replace `.NumThreads` with `.LogicalProcessors`.

NO-JIRA: PPC: fix error message

---

pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go

Previously the isolated cpu list was passed verbatim as the user entered it. This could have resulted in very long kernel command line.
Example: 10,9,8,7,6,5,4,3,2,1 (imagine 500+ cpus)
This change consolidates the parsing logic in the Tuned templating and generates simply the following in such case.
Example: 1-10

OCPBUGS-45264: Normalize cpu sets when rendering to Tuned profiles

---

Makefile
pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go

This fix ensures that the input for any CPU set field is valid. If an invalid string that does not represent a valid CPU set is provided, the admission webhook will return an appropriate error, such as:
`spec.cpu: Internal error: strconv.Atoi: parsing "garbage": invalid syntax`
This replaces the previous behavior where the server would return an error like: 
`Error from server: error when creating "pp.yaml": admission webhook "vwb.performance.openshift.io" denied the request: panic: runtime error: invalid memory address or nil pointer dereference [recovered].`
Moreover, fuzz tests have been added to ensure we exercise all errors when executing the validation function on valid and invalid inputs, ensuring no panic occurs during execution.

OCPBUGS-45346: performanceprofile cpuset input validation

---

cmd/performance-profile-creator/cmd/root.go
pkg/performanceprofile/profilecreator/helper.go
pkg/performanceprofile/profilecreator/profilecreator.go
pkg/performanceprofile/profilecreator/profilecreator_test.go

Problem: In a system with a specific number of cores per socket the host gives each core a number. So far PPC would generate performance profile only after verifying that the nodes pointed to by the specified node pool are all of the same hardware and topology. That is because the performance profile will apply the same configuration on all these nodes and it is most important that they have same structure, CPUs distribution across NUMAs and CPUs availability. This by default includes having same core IDs for each CPU in the same NUMA cells for all the compute nodes. for instance:
Worker-0 has NUMA-0 on which the CPUs siblings [2,66] is coupled in one core numbered 18`.
All other workers should have this info true for them, otherwise the tool would fail.
It was observed (for example on …

OCPBUGS-44372: cmd: PPC: support tolerating heterogeneous core IDs

---

test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/utils/infrastructure/vm.go

* Addressed a corner case where nodes based on VMs would always log a warning without verifying if the profile was degraded. This incorrect behavior has been fixed to properly check the profile state before logging warnings.
* Modified isVM func to execute "systemd-detect-virt" command after chroot to rootfs. This will ensures accurate virtualization detection by running the command in the host's context instead of the container.

OCPBUGS-45971: e2e: tuned degraded test fix

---

pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go

Previously the isolated cpu list was passed verbatim as the user entered it. This could have resulted in very long kernel command line.
Example: 10,9,8,7,6,5,4,3,2,1 (imagine 500+ cpus)
This change consolidates the parsing logic in the Tuned templating and generates simply the following in such case.
Example: 1-10

[release-4.17] OCPBUGS-45627: Normalize cpu sets when rendering to Tuned profiles

---

assets/performanceprofile/tuned/openshift-node-performance
assets/performanceprofile/tuned/openshift-node-performance-amd-x86
assets/performanceprofile/tuned/openshift-node-performance-arm-aarch64
assets/performanceprofile/tuned/openshift-node-performance-intel-x86
pkg/performanceprofile/controller/performanceprofile/components/consts.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

* [CNF-14090](https://issues.redhat.com//browse/CNF-14090): Add vendor and architecture specific tuning options
- Performance tuning support for 3 platforms (amd/x86,arm/aarch64,intel/x86) is added in this change
- When a valid platform is detected the additional platform specific tuning will be imported alongside the default tuning
- This makes use of a new helper function added to tuned to detect the system name and architecture
- Update unit tests to account for the various changes
- Add new unit tests to cover the platform specific tuning
* [CNF-14090](https://issues.redhat.com//browse/CNF-14090): Re-sync e2e test yaml for tuning changes
* [CNF-14090](https://issues.redhat.com//browse/CNF-14090): Use variable composition for idle_poll
- idle=poll is only supported on x86
- Update …

[release-4.17] OCPBUGS-43664: Add vendor and architecture specific tuning options

---

test/e2e/performanceprofile/functests/0_config/config.go

This implements a workaround to prevent CI failures on specific hardware using an Intel E810 network card.
When UserLevelNetworking is set to True, tuned attempts to set the combined channel count equal to the reserved CPUs but fails with the following error:
tuned.utils.commands: Executing 'ethtool -L ens2f0 combined 1' error: netlink error: Device or resource busy
The error occurs because the ice driver: ens2f0: Cannot change channels when RDMA is active.
This issue causes the tuned profile to degrade.
As a temporary solution, by adding 'module_blacklist=irdma' to the kernel Args we will block RDMA, to avoid these errors.

OCPBUGS-46426: e2e: add irdma to module_blacklist kernel args

---

test/e2e/performanceprofile/functests/utils/label/label.go

small typo fixes and added a missing type declaration.

NO-JIRA:e2e:labels: fix typo and adding type

---

test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
test/e2e/performanceprofile/functests/utils/poolname/poolname.go

On OpenShift we're looking for the MCP associated with the
nodes affected by the profile.
On HyperShift we're looking for the nodePool associated the
nodes affected by the profile.
This commit introduce a function to get the pool name
which is essentially MCP/NodePool name depending on
the platform detected at runtime.

NO-JIRA: e2e: common way to fetch poolName

---

pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
test/e2e/performanceprofile/functests/utils/nodepools/nodepools.go

The container runtime configuration test was omitted during the HyperShift adjustments, as it was initially deemed unsuitable for HyperShift. This change introduces support for it.

CNF-16063: E2E: Add hypershift support to container runtime config tests

---

test/e2e/performanceprofile/functests/11_mixedcpus/11_mixedcpus_suite_test.go
test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go

- Performance Profile applying is made consistent with mcp and nodepool based environments
- Removed deprecated API client.
- Added test suite run in makefile

OCPBUGS-42365: E2E: Adjusted mixed_cpus suite for hypershift

---

test/e2e/performanceprofile/functests/2_performance_update/tuned_deferred.go
test/e2e/performanceprofile/functests/utils/label/label.go

This PR implements functional tests for the Tuned deferred annotation feature, developed in response to the bug OCPBUGS-28647.

CNF-15494: E2E:  Tuned deferred test automation

---

test/e2e/performanceprofile/functests/utils/nodes/nodes.go
test/e2e/performanceprofile/functests/utils/pods/pods.go

Manual and partial backport of https://github.com/openshift/cluster-node-tuning-operator/pull/1189

OCPBUGS-47658: [release-4.16][manual]: Fix context deadlines in ExecCommandOnPod()

---

test/e2e/performanceprofile/functests/utils/pods/pods.go

Manual and partial backport of https://github.com/openshift/cluster-node-tuning-operator/pull/1263

OCPBUGS-47683: [release-4.15][manual]: Fix context deadlines in ExecCommandOnPod()

---

cmd/performance-profile-creator/cmd/root.go
pkg/performanceprofile/profilecreator/helper.go
pkg/performanceprofile/profilecreator/profilecreator.go
pkg/performanceprofile/profilecreator/profilecreator_test.go

manual cherrypick of https://github.com/openshift/cluster-node-tuning-operator/pull/1252

OCPBUGS-47701:[release-4.16] cmd: PPC: support tolerating heterogeneous core IDs

---

cmd/performance-profile-creator/cmd/root.go

By mistake this was overridden to always `true` in this PR: #1236 Correct this by setting the value equal to the passed value from the parsed data.
Signed-off-by: Shereen Haj <shajmakh@redhat.com>
(cherry picked from commit 827db751f72744e72c8d04458eca5985f9096391)

OCPBUGS-45903: [release-4.18] PPC: correct EnableHardwareTuning flag value

---

cmd/performance-profile-creator/cmd/root.go

By mistake this was overridden to always `true` in this PR: #1236 Correct this by setting the value equal to the passed value from the parsed data.
Signed-off-by: Shereen Haj <shajmakh@redhat.com>
(cherry picked from commit 827db751f72744e72c8d04458eca5985f9096391) (cherry picked from commit fc95cb0cca16e6f8bd76c1f19229ef5e227e8843)

OCPBUGS-44644: [release-4.17] PPC: correct EnableHardwareTuning flag value

---

pkg/util/manifests.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go

manual cherry-pick of: https://github.com/openshift/cluster-node-tuning-operator/pull/1091
we need this one to be backport up until 4.14 because we're facing the similar issue in [cnf-feature-deploy ci](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-kni_cnf-features-deploy/2135/pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests/1875935067373572096 )
```
[FAILED] Expected
<string>: {
"kind": "KubeletConfiguration",
"apiVersion": "kubelet.config.k8s.io/v1beta1",
"staticPodPath": "/etc/kubernetes/manifests",
"syncFrequency": "0s",
"fileCheckFrequency": "0s",
"httpCheckFrequency": "0s",
"tlsCipherSuites": [
"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
to match regular expression
<string>: "reservedSystemCPUs": ?"0"
```

OCPBUGS-48144:[release-4.16][manual]:e2e:performance: decode to valid kubeletconfig object

---

pkg/util/manifests.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go

manual cherry-pick of: https://github.com/openshift/cluster-node-tuning-operator/pull/1273
we need this one to be backport up until 4.14 because we're facing the similar issue in [cnf-feature-deploy ci](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-kni_cnf-features-deploy/2135/pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests/1875935067373572096)
```
[FAILED] Expected
<string>: {
"kind": "KubeletConfiguration",
"apiVersion": "kubelet.config.k8s.io/v1beta1",
"staticPodPath": "/etc/kubernetes/manifests",
"syncFrequency": "0s",
"fileCheckFrequency": "0s",
"httpCheckFrequency": "0s",
"tlsCipherSuites": [
"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
to match regular expression
<string>: "reservedSystemCPUs": ?"0"
```

OCPBUGS-48207:[release-4.15][manual]e2e:performance: decode to valid kubeletconfig object

---

pkg/util/manifest.go
test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go

manual cherry-pick of: https://github.com/openshift/cluster-node-tuning-operator/pull/1275
we need this one to be backport up until 4.14 because we're facing the similar issue in [cnf-feature-deploy ci](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-kni_cnf-features-deploy/2135/pull-ci-openshift-kni-cnf-features-deploy-release-4.14-e2e-aws-ci-tests/1875935067373572096)
```
[FAILED] Expected
<string>: {
"kind": "KubeletConfiguration",
"apiVersion": "kubelet.config.k8s.io/v1beta1",
"staticPodPath": "/etc/kubernetes/manifests",
"syncFrequency": "0s",
"fileCheckFrequency": "0s",
"httpCheckFrequency": "0s",
"tlsCipherSuites": [
"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
to match regular expression
<string>: "reservedSystemCPUs": ?"0"
```

OCPBUGS-48208: [release-4.14][manual]:e2e:performance: decode to valid kubeletconfig object

---

test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/functests/utils/infrastructure/vm.go

This is a manual backport of #1259.
* Addressed a corner case where nodes based on VMs would always log a warning without verifying if the profile was degraded. This incorrect behavior has been fixed to properly check the profile state before logging warnings.
* Modified isVM func to execute "systemd-detect-virt" command after chroot to rootfs. This will ensures accurate virtualization detection by running the command in the host's context instead of the container.

OCPBUGS-48422: [release-4.16]  e2e: tuned degraded test fix

---

hack/test-tuned-fdp.sh

When testing new TuneD releases, we use the official `Dockerfile.rhel9`. The official Containerfile uses
`registry.ci.openshift.org/ocp/<OCP-VERSION>:base-rhel<RHEL-VERSION>` images.  These images use a wrapper for dnf/yum commands.  The purpose of that wrapper to wrap yum/dnf invocations that are issued by CI workloads or local docker builds of OCP components.
While the wrapper is useful to build an image identical or close to identical to the actual ART releases, it will ignore any custom repositories supplied to it via the "podman build" process and volume mounting `/etc/yum.repos.d`.
The behaviour of the wrapper dnf/yum script can be modified by supplying it `ART_DNF_WRAPPER_POLICY` variable.  Setting the value "append" to this variable does exactly what we need -- do not remove base …

NO-JIRA: Fix hack/test-tuned-fdp.sh

---

hack/render-sync.sh
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go
test/e2e/performanceprofile/cluster-setup/manual-cluster/arm/kustomization.yaml
test/e2e/performanceprofile/cluster-setup/manual-cluster/arm/performance_profile.yaml
test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_runtimeclass.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_tuned.yaml

This PR introduces support for selecting hugepage sizes on ARM-based clusters. It complements the work done in #1086  and ensures that hugepage configurations are correctly applied.
E2E tests are planned to be added in a future update.

OCPBUGS-49823: Support hugepage size selection for ARM-based clusters

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go

Adding a test to verify that runc does not use CPUs assigned to guaranteed pods.
Original bug link - https://bugzilla.redhat.com/show_bug.cgi?id=1910386
**What this test verifies:**
- It checks the configuration flow from kubelet -> cri-o -> runc, ensuring the correct CPU
configuration is provided to runc during the container creation process.
What this test does **NOT** verify:
- It does not monitor the actual CPU usage during the container creation process or track
the CPUs used by any intermediate forks.

OCPBUGS-35911: E2E: Add test to verify runc process excludes the cpus used by pod.

---

go.mod
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go

* Generalized GetHugepagesSizeKilobytes function to handle various inputs. This allows us to use more possible hugepages size (e.g 512M on ARM). Pleas note we expect the validation to ensure the node arch + hugepage size combination is valid. Therefore, this function assumes a valid input, so it can safely convert it to bytes.
* This is done by using the `github.com/docker/go-units` which we should vet.

OCPBUGS-49823: machineconfig: add support for various hugepage sizes

---

docs/performanceprofile/performance_profile.md
pkg/apis/performanceprofile/v2/performanceprofile_types.go
pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go

This PR includes these changes:
* Corrected valid huge page sizes for ARM.
* Improved huge pages validation to depend on the configured kernelPageSize.
* Added unit tests to validate all `kernelPageSize` and `hugepages` combinations, covering both valid and invalid cases.
This improves validation coverage and prevents misconfiguration.
The validation for this work can be found in the Jira ticket.

CNF-16742: kernelPageSize + hugepages combinations validation

---

Dockerfile

This change is necessary to enable building images for architectures like ARM. This is already been done in production Dockerfile.rhel9. The current Dockerfile does not support multi-architecture builds.

CNF-12525: Switch builder image to multi-arch image

---

.gitignore
pkg/performanceprofile/profilecreator/profilecreator.go
pkg/performanceprofile/profilecreator/profilecreator_test.go

The node topology contains several slices that later on are sorted and used to determine whether two nodes are equal. Add a unit test to verify this sorting is done as expected.

NO-JIRA: PPC: unit: test sortTopology for expected output

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

We are commonly testing on two different ARM based platforms that use different cpu architecture designators ARM and APM.
The per-platform tuning profile selector did not expect APM and failed to include the proper profile.
Since we currently do not distinguish between the ARN vendors in any way, the patch changes the detection to be based on Architecture instead of on Vendor ID.

OCPBUGS-52352: Treat all aarch64 platforms as equals in tuned

---

manifests/20-profile.crd.yaml
pkg/apis/tuned/v1/tuned_types.go
pkg/tuned/controller.go

`profiles.tuned.openshift.io` are managed both by the NTO operator and the operands.  The operator manages the `.Spec` part, while the operand reports the status of the TuneD profile application via the `.Status` part.
As it is impossible to tell whether the current `.Status` reflects potential `.Spec` changes without `.Status.ObservedGeneration`, introduce the new field.

NO-JIRA: Add observedGeneration to Profile status

---

hack/render-sync.sh
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
pkg/performanceprofile/controller/performanceprofile/components/profile/profile.go
test/e2e/performanceprofile/cluster-setup/manual-cluster/performance-norps/kustomization.yaml
test/e2e/performanceprofile/cluster-setup/manual-cluster/performance-norps/performance_profile.yaml
test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
test/e2e/performanceprofile/functests/1_performance/performance.go
test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_node.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_runtimeclass.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_tuned.yaml

Centralize the RPS enabled logic into just one function and add a way to force RPS off.
This is prep-work for disabling RPS globally for all use cases.

CNF-16638: Reduce code duplication of RPS enabled checks

---

assets/performanceprofile/tuned/openshift-node-performance
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml

Manual backport of https://github.com/openshift/cluster-node-tuning-operator/pull/1303/
We are commonly testing on two different ARM based platforms that use different cpu architecture designators ARM and APM.
The per-platform tuning profile selector did not expect APM and failed to include the proper profile.
Since we currently do not distinguish between the ARM vendors in any way, the patch changes the detection to be based on Architecture instead of on Vendor ID.

OCPBUGS-52484: Treat all aarch64 platforms as equals in tuned [4.18]

---

test/e2e/performanceprofile/functests/1_performance/irqbalance.go

Upstream ci lanes are failing because of the OCPBUGS-53466 bug, hence skipping the test.

NO-JIRA: e2e: skip irqbalance tests due to known issue

---

Makefile
test/e2e/performanceprofile/functests/14_arm/kernelpagesize.go
test/e2e/performanceprofile/functests/14_arm/test_suite_arm_test.go
test/e2e/performanceprofile/functests/utils/label/label.go

This PR introduces the following changes:
* A new 14_arm directory, which contains the e2e test suite for validating support of the 64k kernelPageSize under PerformanceProfile for the aarch64 family of CPUs.
* A new test suite to validate, at the node level, the kernelPageSize values of 4k and 64k on aarch64. This is done by applying changes to the spec field and inspecting the node to verify that the correct values are reflected on the associated node.
The tests in the suite have been tested in an ARM cluster

CNF-16013: e2e: arm: Add arm kernelPageSize e2e testing suite

---

manifests/30-monitoring.yaml
pkg/operator/profilecalculator.go
pkg/operator/validator.go

The Pod label matching functionality has been mentioned as a candidate for deprecation since OCP 4.4.  Reasons for this change:
* the Pod label matching functionality does not scale well in larger clusters
* ease merging the two NTO control loops into one
Report Tuned CRs which use Pod label matching functionality as invalid and trigger an alert (NTOPodLabelsUsed) for this to give cluster administrators time to update their configuration.
Implements: [PSAP-1608](https://issues.redhat.com//browse/PSAP-1608)

PSAP-1608: Obsolete pod label-based matching

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go

In our tests, we usually create a ```TestPod``` and then configure the ```nodeSelector``` and ```namespace```. Consequently, the ```NodeName``` remains unset, which leads to the runtime utility function failing to retrieve the node. This PR improve the function to retrieve node from pod's ```nodeSelector``` .
Refrence test cases:
- cpu_management [Link](https://github.com/openshift/cluster-node-tuning-operator/blob/master/test/e2e/performanceprofile/functests/1_performance/cpu_management.go#L286)
- cgroups [Link](https://github.com/openshift/cluster-node-tuning-operator/blob/master/test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go#L302)
- workloadhints [Link](https://github.com/openshift/cluster-node-tuning-operator/blob/master/test/e2e/performanceprofile/functest …

CNF-17417: Enhanced utility function for fetching container runtime

---

hack/dockerfile_install_support.sh

This is a workaround not to pull `python3-perf` from CI's `*-server-ose*` repos.

NO-JIRA: Ignore *-server-ose* repos in the CI

---

hack/dockerfile_install_support.sh

While #1314 unblocked the CI pipeline, it broke production image generation due to using unbound $OPENSHIFT_CI variable.  Fix this.

NO-JIRA: Unblock production image generation

---

pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go

* Add a more descriptive error message to guide users on setting the correct 'kernelPageSize' in the PerformanceProfile when specifying a hugepage of a certain size. Since 'kernelPageSize' is a relatively new field, users might not be aware that they must set a corresponding value that supports the hugepage size.
* Improve clarity by printing the specific 'page.size' value instead of dumping the entire struct.

NO-JIRA: Enhance hugepages validation error message

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go

The test case associated with rcu_nocbs verification experienced flakiness due to incorrect parsing of the CPUs specified by the `rcu_nocbs` kernel parameter. Previously, the CPUs were parsed as a string, leading to mismatches with the isolated CPUs during string-based comparisons. This has been corrected by converting both values to **cpuset** type, ensuring accurate CPU set comparisons and improving test stability.

CNF-17656: Fix CPU parsing for `rcu_nocbs` kernel parameter

---

test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
test/e2e/performanceprofile/functests/utils/daemonset/daemonset.go
test/e2e/performanceprofile/functests/utils/images/prepull.go
test/e2e/performanceprofile/functests/utils/node_inspector/inspector.go

In case the DaemonSet's pods are not running for some reason,
we want to log the pod's phase and event for
better observability.
This could help us with finding the root cause
for the reason the pod didn't start.

NO-JIRA:e2e:daemonset: pod phase and events

---

test/e2e/performanceprofile/functests/14_arm/14_arm_suite_test.go

Fixed an issue where ginkgo didn't recognize the kernelPageSize suite running ```ginkgo -v --require 14_arm``` results in: ```Skipping ./test/e2e/performanceprofile/functests/14_arm (no test files)```. Changing the suite's file name to ```14_arm_suite_test.go``` instead of ```test_suite_arm_test.go``` and changing the package name to __arm_test fixes the issue and results in ginkgo recognizing the 14_arm suite.

OCPBUGS-56852: e2e: arm: fix ginkgo doesn't recognize kernelPageSize suite

---

go.mod
vendor/modules.txt

In https://github.com/openshift/cluster-node-tuning-operator/issues/1331 I reported that Go projects that reference github.com/openshift/cluster-node-tuning-operator as a library cannot use it because parts of the Go tooling fail due to go.mod containing references to git tags that do not exist. This causes errors in Go tooling like for example when running "go list -m -json all" where it ends up failing indicating that the non existing revisions do not exist. This errors occur even when the dependencies have a corresponding replace statement replacing to an existing reference. See that issue for details on how to reproduce the error.
This commit updates the go.mod to remove any dependencies references to non existing git tags. Specifically, the non existing references have been updating …

OCPBUGS-56902: fix: stop referencing non existing git references in go.mod

---

cmd/cluster-node-tuning-operator/main.go
pkg/metrics/server.go

Set the minimum default version to TLS 1.3.  PQ algorithms will only be supported in TLS 1.3+.  Hybrid key agreements for TLS 1.3 X25519MLKEM768 is automatically supported by default in go 1.24.
See: [OCPSTRAT-1858](https://issues.redhat.com//browse/OCPSTRAT-1858)

NO-JIRA: Set minimum TLS 1.3 for metrics and webhook servers

---

test/e2e/performanceprofile/functests/13_llc/llc.go

bootstrap the tests which actually run pods and check the CPU (and thus the L3/LLC) allocation.
Start with the trivial sanity tests, adding a good chunk of required infra utilities along the way.

OCPBUGS-57520: e2e: llc: initial tests for cpu allocation

---

docs/performanceprofile/performance_profile.md
manifests/20-performance-profile.crd.yaml
pkg/apis/performanceprofile/v2/performanceprofile_types.go
pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
pkg/apis/performanceprofile/v2/zz_generated.deepcopy.go
pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
pkg/performanceprofile/controller/performanceprofile_controller_test.go

This PR is a backport of #1262 and introduces the following changes:
* KernelPageSize field has been added to performance profile API.
This field defines the kernel page size: for x86/amd64, the only valid value is 4k, while for aarch64, the valid values are 4k, 64k.
The default value is 4k if none is specified.
* Validation has been added
* Modified [kernel Type](https://github.com/openshift/machine-config-operator/blob/f0d60f54b8318a84c4d6e6e9e54319b02bdc4dc9/pkg/controller/common/constants.go#L26-L32) selection process, adding the new kernel type `64k-pages` alongside `default` and `realtime` 
* Documented this

[release-4.18] OCPBUGS-57947: CNF-18142: Add kernel page size field [1/3]

---

hack/render-sync.sh
pkg/performanceprofile/controller/performanceprofile_controller_test.go
test/e2e/performanceprofile/cluster-setup/manual-cluster/arm/kustomization.yaml
test/e2e/performanceprofile/cluster-setup/manual-cluster/arm/performance_profile.yaml
test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_kubeletconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_machineconfig.yaml
test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_runtimeclass.yaml

This PR is a backport #1294. It introduces support for selecting hugepage sizes on ARM-based clusters. It complements the work done in https://github.com/openshift/cluster-node-tuning-operator/pull/1086 and ensures that hugepage configurations are correctly applied.
E2E tests are planned to be added in a future update.

[release-4.18]: OCPBUGS-57947: Support hugepage size selection for ARM-based clusters [2/3]

---

docs/performanceprofile/performance_profile.md
pkg/apis/performanceprofile/v2/performanceprofile_types.go
pkg/apis/performanceprofile/v2/performanceprofile_validation.go
pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go

This PR is a backport of #296. It includes these changes:
* Corrected valid huge page sizes for ARM.
* Improved huge pages validation to depend on the configured kernelPageSize.
* Added unit tests to validate all `kernelPageSize` and `hugepages` combinations, covering both valid and invalid cases.
This improves validation coverage and prevents misconfiguration.

[release-4.18]: OCPBUGS-57947: kernelPageSize + hugepages combinations validation [3/3]

---

pkg/tuned/controller.go
pkg/tuned/run.go
pkg/util/os.go
pkg/util/os_test.go

This PR adds support for running binaries from NVIDIA driver directory mounted by NVIDIA GPU operator to `/run/nvidia/driver/usr/bin`.  This is in support of the new TuneD functionality requested by [RHEL-88914](https://issues.redhat.com//browse/RHEL-88914) and supports both one-shot and daemon mode TuneD invocations.

NO-JIRA: Add support for running binaries from NVIDIA driver directory

---

Makefile
test/e2e/performanceprofile/functests/14_arm/14_arm_suite_test.go
test/e2e/performanceprofile/functests/14_arm/kernelpagesize.go
test/e2e/performanceprofile/functests/utils/label/label.go

Manual backport of #1307 combined with #1330 to backport e2e tests for kernelPageSize on arm

OCPBUGS-58346: [release-4.18] [manual] e2e: arm: Add arm kernelPageSize e2e testing suite

---

Dockerfile

Use the same version of go in the upstream Containerfile (1.24) as in the downstream.

NO-JIRA: Sync the upstream and downstream Containerfiles

---

test/e2e/performanceprofile/functests/14_arm/14_arm_suite_test.go
test/e2e/performanceprofile/functests/14_arm/hugepages.go
test/e2e/performanceprofile/functests/14_arm/kernelpagesize.go
test/e2e/performanceprofile/functests/utils/label/label.go

Adding tests for all supported HugepageSizes.
Please see commit for more info.

OCPBUGS-60838: e2e: arm: add validation tests for hugepages with 4k and 64k kernelPageSize

---

test/e2e/performanceprofile/functests/1_performance/cpu_management.go
test/e2e/performanceprofile/functests/utils/nodes/nodes.go

The GetSMTLevel util function previously used gomega assertions which could cause panics when called outside of Ginkgo It blocks.
This PR addresses:
- Modified the GetSMTLevel signature to return (int, error)
- Replaced ExpectWithOffset assertions with standard error handling
- Updated all function refrences to handle the error return

OCPBUGS-62605: e2e: refactor GetSMTLevel to remove Gomega assertions
